//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECCentral.Portal.UI.MKT.NeweggCN.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResBuyLimitRule {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ResBuyLimitRule()
        {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ECCentral.Portal.UI.MKT.NeweggCN.Resources.ResBuyLimitRule", typeof(ResBuyLimitRule).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建.
        /// </summary>
        public static string Button_Create {
            get {
                return ResourceManager.GetString("Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑.
        /// </summary>
        public static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询.
        /// </summary>
        public static string Button_Search {
            get {
                return ResourceManager.GetString("Button_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询结果.
        /// </summary>
        public static string Expander_QueryResultTitle {
            get {
                return ResourceManager.GetString("Expander_QueryResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询条件.
        /// </summary>
        public static string Expander_QueryTitle {
            get {
                return ResourceManager.GetString("Expander_QueryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始时间.
        /// </summary>
        public static string Grid_BeginDate {
            get {
                return ResourceManager.GetString("Grid_BeginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑时间.
        /// </summary>
        public static string Grid_EditDate {
            get {
                return ResourceManager.GetString("Grid_EditDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑人.
        /// </summary>
        public static string Grid_EditUser {
            get {
                return ResourceManager.GetString("Grid_EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结束时间.
        /// </summary>
        public static string Grid_EndDate {
            get {
                return ResourceManager.GetString("Grid_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品名称/套餐名称.
        /// </summary>
        public static string Grid_ItemName {
            get {
                return ResourceManager.GetString("Grid_ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品ID/套餐编号.
        /// </summary>
        public static string Grid_ItemSysNo {
            get {
                return ResourceManager.GetString("Grid_ItemSysNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 限购类型.
        /// </summary>
        public static string Grid_LimitType {
            get {
                return ResourceManager.GetString("Grid_LimitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 限购上限.
        /// </summary>
        public static string Grid_MaxQty {
            get {
                return ResourceManager.GetString("Grid_MaxQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 会员卡类型.
        /// </summary>
        public static string Grid_MemberCardTypes {
            get {
                return ResourceManager.GetString("Grid_MemberCardTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 会员等级.
        /// </summary>
        public static string Grid_MemberRanks {
            get {
                return ResourceManager.GetString("Grid_MemberRanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 限购下限.
        /// </summary>
        public static string Grid_MinQty {
            get {
                return ResourceManager.GetString("Grid_MinQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作.
        /// </summary>
        public static string Grid_Operation {
            get {
                return ResourceManager.GetString("Grid_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 限购次数.
        /// </summary>
        public static string Grid_OrderTimes {
            get {
                return ResourceManager.GetString("Grid_OrderTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状态.
        /// </summary>
        public static string Grid_Status {
            get {
                return ResourceManager.GetString("Grid_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建限购规则成功。.
        /// </summary>
        public static string Info_AddSuccess {
            get {
                return ResourceManager.GetString("Info_AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新限购规则成功。.
        /// </summary>
        public static string Info_EditSuccess {
            get {
                return ResourceManager.GetString("Info_EditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始时间：.
        /// </summary>
        public static string Label_BeginDate {
            get {
                return ResourceManager.GetString("Label_BeginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 套餐名称：.
        /// </summary>
        public static string Label_ComboName {
            get {
                return ResourceManager.GetString("Label_ComboName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 套餐编号：.
        /// </summary>
        public static string Label_ComboSysNo {
            get {
                return ResourceManager.GetString("Label_ComboSysNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结束时间：.
        /// </summary>
        public static string Label_EndDate {
            get {
                return ResourceManager.GetString("Label_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 限购时间：.
        /// </summary>
        public static string Label_LimitDate {
            get {
                return ResourceManager.GetString("Label_LimitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 限购类型：.
        /// </summary>
        public static string Label_LimitType {
            get {
                return ResourceManager.GetString("Label_LimitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 限购上限：.
        /// </summary>
        public static string Label_MaxQty {
            get {
                return ResourceManager.GetString("Label_MaxQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 会员卡类型：.
        /// </summary>
        public static string Label_MemberCardTypes {
            get {
                return ResourceManager.GetString("Label_MemberCardTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 会员等级：.
        /// </summary>
        public static string Label_MemberRanks {
            get {
                return ResourceManager.GetString("Label_MemberRanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 限购下限：.
        /// </summary>
        public static string Label_MinQty {
            get {
                return ResourceManager.GetString("Label_MinQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 限购次数：.
        /// </summary>
        public static string Label_OrderTimes {
            get {
                return ResourceManager.GetString("Label_OrderTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品：.
        /// </summary>
        public static string Label_Product {
            get {
                return ResourceManager.GetString("Label_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状态：.
        /// </summary>
        public static string Label_Status {
            get {
                return ResourceManager.GetString("Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建限购规则.
        /// </summary>
        public static string PageTitle_Add {
            get {
                return ResourceManager.GetString("PageTitle_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 维护限购规则.
        /// </summary>
        public static string PageTitle_Edit {
            get {
                return ResourceManager.GetString("PageTitle_Edit", resourceCulture);
            }
        }
    }
}
