<?xml version="1.0" encoding="utf-8"?><Database Name="NeweggCentral" Class="ControlPanelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=S1DSQL07\D2whp01;Initial Catalog=NeweggCentral;Persist Security Info=True;User ID=NCDbo" SettingsObjectName="Newegg.Oversea.Silverlight.ControlPanel.Service.Properties.Settings" SettingsPropertyName="NeweggCentralConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ControlPanelConfiguration" Member="ConfigurationEntities">
    <Type Name="ConfigurationEntity">
      <Column Name="ConfigId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ApplicationId" Type="System.String" DbType="Char(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DomainName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ConfigKey" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ConfigValue" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ConfigDescription" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="InDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="InUser" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="EditDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="EditUser" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="" Member="ControlPanelLocalizedMenuEntities">
    <Type Name="ControlPanelLocalizedMenuEntity" Id="ID1">
      <Column Name="MenuId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="false" />
      <Column Name="DisplayName" Type="System.String" DbType="NVarChar(200) " CanBeNull="false" />
      <Column Name="MenuDescription" Member="Description" Storage="_MenuDescription" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="IconStyle" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="LinkPath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MenuType" Member="TypeCode" Storage="_MenuType" Type="System.String" DbType="Char(1)" CanBeNull="false" />
      <Column Name="AuthKey" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="IsDisplay" Member="IsDisplayCode" Storage="_IsDisplay" Type="System.String" DbType="Char(1)" CanBeNull="false" />
      <Column Name="Status" Member="StatusCode" Storage="_Status" Type="System.String" DbType="Char(1) " CanBeNull="false" />
      <Column Name="ParentMenuId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="SortIndex" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ApplicationId" Member="ApplicationId2" Storage="_ApplicationId" Type="System.String" DbType="Char(50)" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ControlPanelProfile" Member="ProfileEntities">
    <Type Name="ProfileEntity">
      <Column Name="ProfileId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ApplicationId" Member="ApplicationId2" Type="System.String" DbType="Char(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ProfileType" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ProfileValue" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ProfileItemGuid" Member="ProfileItemGuid2" Type="System.String" DbType="Char(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="InDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="InUser" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.ControlPanelMenu" Member="ControlPanelMenuEntities">
    <Type Name="ControlPanelMenuEntity">
      <Column Name="MenuId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DisplayName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="MenuDescription" Member="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="IconStyle" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="LinkPath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MenuType" Member="TypeCode" Type="System.String" DbType="Char(1) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="AuthKey" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsDisplay" Member="IsDisplayCode" Type="System.String" DbType="Char(1) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Status" Member="StatusCode" Type="System.String" DbType="Char(1) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ParentMenuId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SortIndex" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ApplicationId" Member="ApplicationId2" Type="System.String" DbType="Char(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="LanguageCode" Member="LanguageCode2" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="InDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="InUser" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="EditDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="EditUser" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.ControlPanelMenuLocalizedRes" Member="ControlPanelMenuLocalizedRes">
    <Type Name="ControlPanelMenuLocalizedRes">
      <Column Name="TransactionNumber" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ReferenceMenuId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DisplayName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="MenuDescription" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="IconStyle" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="LinkPath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="LanguageCode" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="InDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="InUser" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="EditDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EditUser" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.FN_ControlPanelMenuWithLocalizedRes" Method="FN_ControlPanelMenuWithLocalizedRes" IsComposable="true">
    <Parameter Name="LanguageCode" Parameter="languageCode" Type="System.String" DbType="Char(5)" />
    <ElementType IdRef="ID1" />
  </Function>
</Database>