//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Newegg.Oversea.Silverlight.ControlPanel.Impl.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public MessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Newegg.Oversea.Silverlight.ControlPanel.Impl.Resources.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Panel.
        /// </summary>
        public static string AuthManager_ControlPanel {
            get {
                return ResourceManager.GetString("AuthManager_ControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Profile.
        /// </summary>
        public static string AuthManager_ItemProfile {
            get {
                return ResourceManager.GetString("AuthManager_ItemProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Order.
        /// </summary>
        public static string AuthManager_SalesOrder {
            get {
                return ResourceManager.GetString("AuthManager_SalesOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomePage_Title {
            get {
                return ResourceManager.GetString("HomePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading... {0}%.
        /// </summary>
        public static string LoadingComponent_Loading {
            get {
                return ResourceManager.GetString("LoadingComponent_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close all tabs (Ctrl+Alt+A).
        /// </summary>
        public static string PageBrowser_CloseAllTabs_Title {
            get {
                return ResourceManager.GetString("PageBrowser_CloseAllTabs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close other tabs (Ctrl+Alt+X).
        /// </summary>
        public static string PageBrowser_CloseOtherTabs_Title {
            get {
                return ResourceManager.GetString("PageBrowser_CloseOtherTabs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to close current page?.
        /// </summary>
        public static string PageBrowser_CloseTab_ConfirmContent {
            get {
                return ResourceManager.GetString("PageBrowser_CloseTab_ConfirmContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string PageBrowser_CloseTab_ConfirmTitle {
            get {
                return ResourceManager.GetString("PageBrowser_CloseTab_ConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close tab (Ctrl+Alt+C).
        /// </summary>
        public static string PageBrowser_CloseTab_Title {
            get {
                return ResourceManager.GetString("PageBrowser_CloseTab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close (Ctrl+Alt+C).
        /// </summary>
        public static string PageBrowser_CloseTabTip_Title {
            get {
                return ResourceManager.GetString("PageBrowser_CloseTabTip_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to close all tabs?.
        /// </summary>
        public static string PageBrowser_Confirm_CloseAllTabs {
            get {
                return ResourceManager.GetString("PageBrowser_Confirm_CloseAllTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate (Ctrl+Alt+D).
        /// </summary>
        public static string PageBrowser_Duplicate_Title {
            get {
                return ResourceManager.GetString("PageBrowser_Duplicate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page tab&apos;s total is more than maximum total!.
        /// </summary>
        public static string PageBrowser_Error_MoreThanMaxPageTabTotal {
            get {
                return ResourceManager.GetString("PageBrowser_Error_MoreThanMaxPageTabTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string PageBrowser_Home {
            get {
                return ResourceManager.GetString("PageBrowser_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll tab list backward.
        /// </summary>
        public static string PageBrowser_LeftScroller {
            get {
                return ResourceManager.GetString("PageBrowser_LeftScroller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string PageBrowser_LoadingSpin_Title {
            get {
                return ResourceManager.GetString("PageBrowser_LoadingSpin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string PageBrowser_MessageBox_Error {
            get {
                return ResourceManager.GetString("PageBrowser_MessageBox_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error：.
        /// </summary>
        public static string PageBrowser_MessageBox_Error_Title {
            get {
                return ResourceManager.GetString("PageBrowser_MessageBox_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string PageBrowser_MessageBox_Information {
            get {
                return ResourceManager.GetString("PageBrowser_MessageBox_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string PageBrowser_MessageBox_Success {
            get {
                return ResourceManager.GetString("PageBrowser_MessageBox_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success：.
        /// </summary>
        public static string PageBrowser_MessageBox_Success_Title {
            get {
                return ResourceManager.GetString("PageBrowser_MessageBox_Success_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string PageBrowser_MessageBox_Warning {
            get {
                return ResourceManager.GetString("PageBrowser_MessageBox_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning：.
        /// </summary>
        public static string PageBrowser_MessageBox_Warning_Title {
            get {
                return ResourceManager.GetString("PageBrowser_MessageBox_Warning_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string PageBrowser_Refresh {
            get {
                return ResourceManager.GetString("PageBrowser_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload (Ctrl+Alt+R).
        /// </summary>
        public static string PageBrowser_Reload_Title {
            get {
                return ResourceManager.GetString("PageBrowser_Reload_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scoll tab list forward.
        /// </summary>
        public static string PageBrowser_RightScroller {
            get {
                return ResourceManager.GetString("PageBrowser_RightScroller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string PageBrowser_Unknown {
            get {
                return ResourceManager.GetString("PageBrowser_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current url can not resolved..
        /// </summary>
        public static string PageException_BadRequest_Message {
            get {
                return ResourceManager.GetString("PageException_BadRequest_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request.
        /// </summary>
        public static string PageException_BadRequest_Title {
            get {
                return ResourceManager.GetString("PageException_BadRequest_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access is Denied!.
        /// </summary>
        public static string PageException_DeniedAccess_Message {
            get {
                return ResourceManager.GetString("PageException_DeniedAccess_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denied Access.
        /// </summary>
        public static string PageException_DeniedAccess_Title {
            get {
                return ResourceManager.GetString("PageException_DeniedAccess_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current amssbly is  initialize failure..
        /// </summary>
        public static string PageException_ModuleInitializeError_Message {
            get {
                return ResourceManager.GetString("PageException_ModuleInitializeError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Initialize Error.
        /// </summary>
        public static string PageException_ModuleInitializeError_Ttitle {
            get {
                return ResourceManager.GetString("PageException_ModuleInitializeError_Ttitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current page is initialize failure..
        /// </summary>
        public static string PageException_PageInitializeError_Message {
            get {
                return ResourceManager.GetString("PageException_PageInitializeError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Initialize Error.
        /// </summary>
        public static string PageException_PageInitializeError_Ttitle {
            get {
                return ResourceManager.GetString("PageException_PageInitializeError_Ttitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current page is loading  Failure..
        /// </summary>
        public static string PageException_PageLoadFailure_Message {
            get {
                return ResourceManager.GetString("PageException_PageLoadFailure_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Loading Failure.
        /// </summary>
        public static string PageException_PageLoadFailure_Title {
            get {
                return ResourceManager.GetString("PageException_PageLoadFailure_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string PageException_PageNoFound_Title {
            get {
                return ResourceManager.GetString("PageException_PageNoFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation time out, please try again..
        /// </summary>
        public static string PageException_Timeout_Message {
            get {
                return ResourceManager.GetString("PageException_Timeout_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current page you are look for might has been removed, had its name changed..
        /// </summary>
        public static string PageExcepton_PageNotFound_Message {
            get {
                return ResourceManager.GetString("PageExcepton_PageNotFound_Message", resourceCulture);
            }
        }
    }
}
