//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Newegg.Oversea.Silverlight.CommonDomain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class QueryReportResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public QueryReportResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Newegg.Oversea.Silverlight.CommonDomain.Resources.QueryReportResource", typeof(QueryReportResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Chart_Label_Date {
            get {
                return ResourceManager.GetString("Chart_Label_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Count.
        /// </summary>
        public static string Chart_Label_LoginCount {
            get {
                return ResourceManager.GetString("Chart_Label_LoginCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visits.
        /// </summary>
        public static string Chart_Title_LoginCount {
            get {
                return ResourceManager.GetString("Chart_Title_LoginCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique Visits.
        /// </summary>
        public static string Chart_Title_UniqueLoginCount {
            get {
                return ResourceManager.GetString("Chart_Title_UniqueLoginCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string DataGrid_ColumnHeader_Action {
            get {
                return ResourceManager.GetString("DataGrid_ColumnHeader_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string DataGrid_ColumnHeader_Count {
            get {
                return ResourceManager.GetString("DataGrid_ColumnHeader_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        public static string DataGrid_ColumnHeader_ID {
            get {
                return ResourceManager.GetString("DataGrid_ColumnHeader_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string DataGrid_ColumnHeader_Label {
            get {
                return ResourceManager.GetString("DataGrid_ColumnHeader_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string DataGrid_ColumnHeader_Page {
            get {
                return ResourceManager.GetString("DataGrid_ColumnHeader_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pageviews.
        /// </summary>
        public static string DataGrid_ColumnHeader_PageViews {
            get {
                return ResourceManager.GetString("DataGrid_ColumnHeader_PageViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pageviews(%).
        /// </summary>
        public static string DataGrid_ColumnHeader_Percentage {
            get {
                return ResourceManager.GetString("DataGrid_ColumnHeader_Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique Pageviews.
        /// </summary>
        public static string DataGrid_ColumnHeader_UniquePageViews {
            get {
                return ResourceManager.GetString("DataGrid_ColumnHeader_UniquePageViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string DataGrid_ColumnHeader_Url {
            get {
                return ResourceManager.GetString("DataGrid_ColumnHeader_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string DataGrid_ColumnHeader_User {
            get {
                return ResourceManager.GetString("DataGrid_ColumnHeader_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visits Statistics.
        /// </summary>
        public static string Expander_Header_LoginStatistics {
            get {
                return ResourceManager.GetString("Expander_Header_LoginStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Action Statistics.
        /// </summary>
        public static string Expander_Header_PageActionStatistics {
            get {
                return ResourceManager.GetString("Expander_Header_PageActionStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Views List.
        /// </summary>
        public static string Expander_Header_PageViewsList {
            get {
                return ResourceManager.GetString("Expander_Header_PageViewsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Expander_Header_Search {
            get {
                return ResourceManager.GetString("Expander_Header_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related User Statistics.
        /// </summary>
        public static string Expander_Header_UserPageViews {
            get {
                return ResourceManager.GetString("Expander_Header_UserPageViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string Lb_DateFrom {
            get {
                return ResourceManager.GetString("Lb_DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string Lb_DateTo {
            get {
                return ResourceManager.GetString("Lb_DateTo", resourceCulture);
            }
        }
    }
}
