//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECCentral.Portal.UI.MKT.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResBanner {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ResBanner()
        {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ECCentral.Portal.UI.MKT.Resources.ResBanner", typeof(ResBanner).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑.
        /// </summary>
        public static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建.
        /// </summary>
        public static string Button_New {
            get {
                return ResourceManager.GetString("Button_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询.
        /// </summary>
        public static string Button_Search {
            get {
                return ResourceManager.GetString("Button_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作废.
        /// </summary>
        public static string Button_Void {
            get {
                return ResourceManager.GetString("Button_Void", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此位置区域已经有{0}个有效的Banner存在,请确定是否继续添加?.
        /// </summary>
        public static string Confirm_AlreadyExists {
            get {
                return ResourceManager.GetString("Confirm_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定要执行作废操作吗？.
        /// </summary>
        public static string Confirm_Void {
            get {
                return ResourceManager.GetString("Confirm_Void", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询条件.
        /// </summary>
        public static string Expander_SearchCondition {
            get {
                return ResourceManager.GetString("Expander_SearchCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询结果.
        /// </summary>
        public static string Expander_SearchResult {
            get {
                return ResourceManager.GetString("Expander_SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 广告展示.
        /// </summary>
        public static string Grid_BannerShow {
            get {
                return ResourceManager.GetString("Grid_BannerShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 广告标题.
        /// </summary>
        public static string Grid_BannerTitle {
            get {
                return ResourceManager.GetString("Grid_BannerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 广告类型.
        /// </summary>
        public static string Grid_BannerType {
            get {
                return ResourceManager.GetString("Grid_BannerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始日期.
        /// </summary>
        public static string Grid_BeginDate {
            get {
                return ResourceManager.GetString("Grid_BeginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所属渠道.
        /// </summary>
        public static string Grid_Channel {
            get {
                return ResourceManager.GetString("Grid_Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建日期.
        /// </summary>
        public static string Grid_CreateDate {
            get {
                return ResourceManager.GetString("Grid_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建人.
        /// </summary>
        public static string Grid_CreateUser {
            get {
                return ResourceManager.GetString("Grid_CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尺寸.
        /// </summary>
        public static string Grid_Dimension {
            get {
                return ResourceManager.GetString("Grid_Dimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑日期.
        /// </summary>
        public static string Grid_EditDate {
            get {
                return ResourceManager.GetString("Grid_EditDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑人.
        /// </summary>
        public static string Grid_EditUser {
            get {
                return ResourceManager.GetString("Grid_EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结束日期.
        /// </summary>
        public static string Grid_EndDate {
            get {
                return ResourceManager.GetString("Grid_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主要投放区域.
        /// </summary>
        public static string Grid_MainArea {
            get {
                return ResourceManager.GetString("Grid_MainArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作.
        /// </summary>
        public static string Grid_Operation {
            get {
                return ResourceManager.GetString("Grid_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页面编号.
        /// </summary>
        public static string Grid_PageID {
            get {
                return ResourceManager.GetString("Grid_PageID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页面类型.
        /// </summary>
        public static string Grid_PageType {
            get {
                return ResourceManager.GetString("Grid_PageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页面位置.
        /// </summary>
        public static string Grid_Position {
            get {
                return ResourceManager.GetString("Grid_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 优先级.
        /// </summary>
        public static string Grid_Priority {
            get {
                return ResourceManager.GetString("Grid_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状态.
        /// </summary>
        public static string Grid_Status {
            get {
                return ResourceManager.GetString("Grid_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编号.
        /// </summary>
        public static string Grid_SysNo {
            get {
                return ResourceManager.GetString("Grid_SysNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加成功。.
        /// </summary>
        public static string Info_AddSuccess {
            get {
                return ResourceManager.GetString("Info_AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 资源地址不能为空。.
        /// </summary>
        public static string Info_BannerResourceUrlRequired {
            get {
                return ResourceManager.GetString("Info_BannerResourceUrlRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑成功。.
        /// </summary>
        public static string Info_EditSuccess {
            get {
                return ResourceManager.GetString("Info_EditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作废成功。.
        /// </summary>
        public static string Info_VoidSuccessfully {
            get {
                return ResourceManager.GetString("Info_VoidSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不限制.
        /// </summary>
        public static string TextBlock_AreaNoLimit {
            get {
                return ResourceManager.GetString("TextBlock_AreaNoLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 链接地址:.
        /// </summary>
        public static string TextBlock_BannerLink {
            get {
                return ResourceManager.GetString("TextBlock_BannerLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 广告脚本:.
        /// </summary>
        public static string TextBlock_BannerOnClick {
            get {
                return ResourceManager.GetString("TextBlock_BannerOnClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 资源地址:.
        /// </summary>
        public static string TextBlock_BannerResourceUrl {
            get {
                return ResourceManager.GetString("TextBlock_BannerResourceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 广告内容:.
        /// </summary>
        public static string TextBlock_BannerText {
            get {
                return ResourceManager.GetString("TextBlock_BannerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 广告标题:.
        /// </summary>
        public static string TextBlock_BannerTitle {
            get {
                return ResourceManager.GetString("TextBlock_BannerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 广告类型:.
        /// </summary>
        public static string TextBlock_BannerType {
            get {
                return ResourceManager.GetString("TextBlock_BannerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始日期:.
        /// </summary>
        public static string TextBlock_BeginDate {
            get {
                return ResourceManager.GetString("TextBlock_BeginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结束日期:.
        /// </summary>
        public static string TextBlock_EndDate {
            get {
                return ResourceManager.GetString("TextBlock_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排除页面编号:.
        /// </summary>
        public static string TextBlock_ExceptPageID {
            get {
                return ResourceManager.GetString("TextBlock_ExceptPageID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主要投放区域:.
        /// </summary>
        public static string TextBlock_MainArea {
            get {
                return ResourceManager.GetString("TextBlock_MainArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页面类型:.
        /// </summary>
        public static string TextBlock_PageType {
            get {
                return ResourceManager.GetString("TextBlock_PageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页面位置:.
        /// </summary>
        public static string TextBlock_Position {
            get {
                return ResourceManager.GetString("TextBlock_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 优先级:.
        /// </summary>
        public static string TextBlock_Priority {
            get {
                return ResourceManager.GetString("TextBlock_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 广告比率(%):.
        /// </summary>
        public static string TextBlock_Ratio {
            get {
                return ResourceManager.GetString("TextBlock_Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 相关标签:.
        /// </summary>
        public static string TextBlock_RelativeTags {
            get {
                return ResourceManager.GetString("TextBlock_RelativeTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状态:.
        /// </summary>
        public static string TextBlock_Status {
            get {
                return ResourceManager.GetString("TextBlock_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所属渠道:.
        /// </summary>
        public static string TextBlock_WebChannel {
            get {
                return ResourceManager.GetString("TextBlock_WebChannel", resourceCulture);
            }
        }
    }
}
