//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECCentral.Portal.UI.MKT.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResFloorMaintain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ResFloorMaintain()
        {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ECCentral.Portal.UI.MKT.Resources.ResFloorMaintain", typeof(ResFloorMaintain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加广告.
        /// </summary>
        public static string Button_AddBanner {
            get {
                return ResourceManager.GetString("Button_AddBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加品牌.
        /// </summary>
        public static string Button_AddBrand {
            get {
                return ResourceManager.GetString("Button_AddBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加文本链接.
        /// </summary>
        public static string Button_AddLink {
            get {
                return ResourceManager.GetString("Button_AddLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加商品.
        /// </summary>
        public static string Button_AddProduct {
            get {
                return ResourceManager.GetString("Button_AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 批量添加.
        /// </summary>
        public static string Button_BatchAddProduct {
            get {
                return ResourceManager.GetString("Button_BatchAddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建.
        /// </summary>
        public static string Button_Reset {
            get {
                return ResourceManager.GetString("Button_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存配置.
        /// </summary>
        public static string ButtonSavaConfig {
            get {
                return ResourceManager.GetString("ButtonSavaConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据维护.
        /// </summary>
        public static string Expander_MaintainTitle {
            get {
                return ResourceManager.GetString("Expander_MaintainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标签列表：.
        /// </summary>
        public static string Expander_TagListTitle {
            get {
                return ResourceManager.GetString("Expander_TagListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string Grid_ButtonDelete {
            get {
                return ResourceManager.GetString("Grid_ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑.
        /// </summary>
        public static string Grid_ButtonEdit {
            get {
                return ResourceManager.GetString("Grid_ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 广告图片.
        /// </summary>
        public static string Grid_HeaderBannerImg {
            get {
                return ResourceManager.GetString("Grid_HeaderBannerImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文字内容.
        /// </summary>
        public static string Grid_HeaderBannerText {
            get {
                return ResourceManager.GetString("Grid_HeaderBannerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 品牌编号.
        /// </summary>
        public static string Grid_HeaderBrandSysNo {
            get {
                return ResourceManager.GetString("Grid_HeaderBrandSysNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文字内容.
        /// </summary>
        public static string Grid_HeaderBrandText {
            get {
                return ResourceManager.GetString("Grid_HeaderBrandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片.
        /// </summary>
        public static string Grid_HeaderImageSrc {
            get {
                return ResourceManager.GetString("Grid_HeaderImageSrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片.
        /// </summary>
        public static string Grid_HeaderImageUrl {
            get {
                return ResourceManager.GetString("Grid_HeaderImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标记热点.
        /// </summary>
        public static string Grid_HeaderIsHot {
            get {
                return ResourceManager.GetString("Grid_HeaderIsHot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 位置.
        /// </summary>
        public static string Grid_HeaderItemPosition {
            get {
                return ResourceManager.GetString("Grid_HeaderItemPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 链接地址.
        /// </summary>
        public static string Grid_HeaderLinkUrl {
            get {
                return ResourceManager.GetString("Grid_HeaderLinkUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标题.
        /// </summary>
        public static string Grid_HeaderMainTitle {
            get {
                return ResourceManager.GetString("Grid_HeaderMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作.
        /// </summary>
        public static string Grid_HeaderOperating {
            get {
                return ResourceManager.GetString("Grid_HeaderOperating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 价格.
        /// </summary>
        public static string Grid_HeaderPrice {
            get {
                return ResourceManager.GetString("Grid_HeaderPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 优先级.
        /// </summary>
        public static string Grid_HeaderPriority {
            get {
                return ResourceManager.GetString("Grid_HeaderPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品编号.
        /// </summary>
        public static string Grid_HeaderProductSysNo {
            get {
                return ResourceManager.GetString("Grid_HeaderProductSysNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择.
        /// </summary>
        public static string Grid_HeaderSelect {
            get {
                return ResourceManager.GetString("Grid_HeaderSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状态.
        /// </summary>
        public static string Grid_HeaderStatus {
            get {
                return ResourceManager.GetString("Grid_HeaderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 副标题.
        /// </summary>
        public static string Grid_HeaderSubTitle {
            get {
                return ResourceManager.GetString("Grid_HeaderSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文字内容.
        /// </summary>
        public static string Grid_HeaderText {
            get {
                return ResourceManager.GetString("Grid_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称.
        /// </summary>
        public static string Grid_HeaderTitle {
            get {
                return ResourceManager.GetString("Grid_HeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标签基础信息.
        /// </summary>
        public static string GroupBox_TagBasic {
            get {
                return ResourceManager.GetString("GroupBox_TagBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标签内容列表.
        /// </summary>
        public static string GroupBox_TagData {
            get {
                return ResourceManager.GetString("GroupBox_TagData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 推荐广告.
        /// </summary>
        public static string Head_BannerSection {
            get {
                return ResourceManager.GetString("Head_BannerSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 推荐品牌.
        /// </summary>
        public static string Head_BrandSection {
            get {
                return ResourceManager.GetString("Head_BrandSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加商品.
        /// </summary>
        public static string Head_ProductAdd {
            get {
                return ResourceManager.GetString("Head_ProductAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 推荐商品.
        /// </summary>
        public static string Head_ProductSection {
            get {
                return ResourceManager.GetString("Head_ProductSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 推荐文本链接.
        /// </summary>
        public static string Head_TextLinkSection {
            get {
                return ResourceManager.GetString("Head_TextLinkSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定要删除吗？.
        /// </summary>
        public static string Info_ConfirmDelete {
            get {
                return ResourceManager.GetString("Info_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建成功！.
        /// </summary>
        public static string Info_CreateSuccess {
            get {
                return ResourceManager.GetString("Info_CreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑成功！.
        /// </summary>
        public static string Info_EditSuccess {
            get {
                return ResourceManager.GetString("Info_EditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已经存在相同推荐商品，是否继续？.
        /// </summary>
        public static string Info_ExistsProduct {
            get {
                return ResourceManager.GetString("Info_ExistsProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先选中需要维护的标签！.
        /// </summary>
        public static string Info_SectionChecked {
            get {
                return ResourceManager.GetString("Info_SectionChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称:.
        /// </summary>
        public static string TextBlock_Name {
            get {
                return ResourceManager.GetString("TextBlock_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 优先级：.
        /// </summary>
        public static string TextBlock_Priority {
            get {
                return ResourceManager.GetString("TextBlock_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状态:.
        /// </summary>
        public static string TextBlock_Status {
            get {
                return ResourceManager.GetString("TextBlock_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 推荐广告：.
        /// </summary>
        public static string TextBlock_TitleBanner {
            get {
                return ResourceManager.GetString("TextBlock_TitleBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 推荐品牌：.
        /// </summary>
        public static string TextBlock_TitleBrand {
            get {
                return ResourceManager.GetString("TextBlock_TitleBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文本链接：.
        /// </summary>
        public static string TextBlock_TitleLink {
            get {
                return ResourceManager.GetString("TextBlock_TitleLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 推荐商品：.
        /// </summary>
        public static string TextBlock_TitleProduct {
            get {
                return ResourceManager.GetString("TextBlock_TitleProduct", resourceCulture);
            }
        }
    }
}
