//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECCentral.Portal.UI.MKT.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResGroupBuyingFeedbackQuery {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ResGroupBuyingFeedbackQuery()
        {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ECCentral.Portal.UI.MKT.Resources.ResGroupBuyingFeedbackQuery", typeof(ResGroupBuyingFeedbackQuery).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 批量设置已阅读.
        /// </summary>
        public static string Button_BatchSetReaded {
            get {
                return ResourceManager.GetString("Button_BatchSetReaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询.
        /// </summary>
        public static string Button_Query {
            get {
                return ResourceManager.GetString("Button_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询条件.
        /// </summary>
        public static string Expander_QueryBuiler {
            get {
                return ResourceManager.GetString("Expander_QueryBuiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询结果.
        /// </summary>
        public static string Expander_QueryResult {
            get {
                return ResourceManager.GetString("Expander_QueryResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 联系方式.
        /// </summary>
        public static string Grid_ContactMethod {
            get {
                return ResourceManager.GetString("Grid_ContactMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 反馈内容.
        /// </summary>
        public static string Grid_Content {
            get {
                return ResourceManager.GetString("Grid_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 反馈时间.
        /// </summary>
        public static string Grid_CreateDate {
            get {
                return ResourceManager.GetString("Grid_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑.
        /// </summary>
        public static string Grid_Edit {
            get {
                return ResourceManager.GetString("Grid_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 阅读时间.
        /// </summary>
        public static string Grid_EditDate {
            get {
                return ResourceManager.GetString("Grid_EditDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 阅读人.
        /// </summary>
        public static string Grid_EditUser {
            get {
                return ResourceManager.GetString("Grid_EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 反馈状态.
        /// </summary>
        public static string Grid_Status {
            get {
                return ResourceManager.GetString("Grid_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统编号.
        /// </summary>
        public static string Grid_SysNo {
            get {
                return ResourceManager.GetString("Grid_SysNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 反馈类型.
        /// </summary>
        public static string Grid_Type {
            get {
                return ResourceManager.GetString("Grid_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择要操作的数据！.
        /// </summary>
        public static string Info_SelectData {
            get {
                return ResourceManager.GetString("Info_SelectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        public static string Info_Tips {
            get {
                return ResourceManager.GetString("Info_Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 反馈时间：.
        /// </summary>
        public static string TextBlock_CreateDate {
            get {
                return ResourceManager.GetString("TextBlock_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 阅读时间：.
        /// </summary>
        public static string TextBlock_ReadDate {
            get {
                return ResourceManager.GetString("TextBlock_ReadDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 反馈状态：.
        /// </summary>
        public static string TextBlock_Status {
            get {
                return ResourceManager.GetString("TextBlock_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 反馈类型：.
        /// </summary>
        public static string TextBlock_Type {
            get {
                return ResourceManager.GetString("TextBlock_Type", resourceCulture);
            }
        }
    }
}
