//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECCentral.Portal.UI.Invoice.NeweggCN.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResInvoiceSelfPrint {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ResInvoiceSelfPrint() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ECCentral.Portal.UI.Invoice.NeweggCN.Resources.ResInvoiceSelfPrint", typeof(ResInvoiceSelfPrint).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询.
        /// </summary>
        public static string Button_Query {
            get {
                return ResourceManager.GetString("Button_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询结果.
        /// </summary>
        public static string Button_QueryResult {
            get {
                return ResourceManager.GetString("Button_QueryResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开票金额.
        /// </summary>
        public static string Grid_InvoiceAmount {
            get {
                return ResourceManager.GetString("Grid_InvoiceAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发票代码.
        /// </summary>
        public static string Grid_InvoiceCode {
            get {
                return ResourceManager.GetString("Grid_InvoiceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开票日期.
        /// </summary>
        public static string Grid_InvoiceDate {
            get {
                return ResourceManager.GetString("Grid_InvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发票号码.
        /// </summary>
        public static string Grid_InvoiceNumber {
            get {
                return ResourceManager.GetString("Grid_InvoiceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发票状态.
        /// </summary>
        public static string Grid_InvoiceStatus {
            get {
                return ResourceManager.GetString("Grid_InvoiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发票类型.
        /// </summary>
        public static string Grid_InvoiceType {
            get {
                return ResourceManager.GetString("Grid_InvoiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否红冲.
        /// </summary>
        public static string Grid_IsNegativeInvoice {
            get {
                return ResourceManager.GetString("Grid_IsNegativeInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否重打.
        /// </summary>
        public static string Grid_IsRePrint {
            get {
                return ResourceManager.GetString("Grid_IsRePrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 订单编号.
        /// </summary>
        public static string Grid_OrderID {
            get {
                return ResourceManager.GetString("Grid_OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出库时间.
        /// </summary>
        public static string Grid_OutStockTime {
            get {
                return ResourceManager.GetString("Grid_OutStockTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仓库:.
        /// </summary>
        public static string TextBlock_Compartment {
            get {
                return ResourceManager.GetString("TextBlock_Compartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发票号码:.
        /// </summary>
        public static string TextBlock_InvoiceNo {
            get {
                return ResourceManager.GetString("TextBlock_InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开票日期:.
        /// </summary>
        public static string TextBlock_InvoiceTime {
            get {
                return ResourceManager.GetString("TextBlock_InvoiceTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 订单编号:.
        /// </summary>
        public static string TextBlock_OrderID {
            get {
                return ResourceManager.GetString("TextBlock_OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出库日期:.
        /// </summary>
        public static string TextBlock_OutStockTime {
            get {
                return ResourceManager.GetString("TextBlock_OutStockTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (多个单据间用.分割):.
        /// </summary>
        public static string TextBlock_SplitWithDot {
            get {
                return ResourceManager.GetString("TextBlock_SplitWithDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询条件.
        /// </summary>
        public static string Toolkit_Condition {
            get {
                return ResourceManager.GetString("Toolkit_Condition", resourceCulture);
            }
        }
    }
}
