//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECCentral.Portal.UI.Invoice.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResPayQuery {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ResPayQuery() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ECCentral.Portal.UI.Invoice.Resources.ResPayQuery", typeof(ResPayQuery).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 批量录入发票.
        /// </summary>
        public static string Button_BatchInputInvoice {
            get {
                return ResourceManager.GetString("Button_BatchInputInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询.
        /// </summary>
        public static string Button_Search {
            get {
                return ResourceManager.GetString("Button_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 失败原因.
        /// </summary>
        public static string Dialog_FailedDetail {
            get {
                return ResourceManager.GetString("Dialog_FailedDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应付款发票状态维护.
        /// </summary>
        public static string Dialog_InvoiceMaintain {
            get {
                return ResourceManager.GetString("Dialog_InvoiceMaintain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询条件.
        /// </summary>
        public static string Expander_QueryBuilder {
            get {
                return ResourceManager.GetString("Expander_QueryBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询结果.
        /// </summary>
        public static string Expander_QueryResult {
            get {
                return ResourceManager.GetString("Expander_QueryResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已付.
        /// </summary>
        public static string Grid_AlreadyPayAmt {
            get {
                return ResourceManager.GetString("Grid_AlreadyPayAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应付时间.
        /// </summary>
        public static string Grid_CreateDate {
            get {
                return ResourceManager.GetString("Grid_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 货币.
        /// </summary>
        public static string Grid_Currency {
            get {
                return ResourceManager.GetString("Grid_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑.
        /// </summary>
        public static string Grid_Edit {
            get {
                return ResourceManager.GetString("Grid_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预估付款时间.
        /// </summary>
        public static string Grid_EGP {
            get {
                return ResourceManager.GetString("Grid_EGP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EIMS编号.
        /// </summary>
        public static string Grid_EIMSNoList {
            get {
                return ResourceManager.GetString("Grid_EIMSNoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预计付款时间.
        /// </summary>
        public static string Grid_ETP {
            get {
                return ResourceManager.GetString("Grid_ETP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入库(结算)金额.
        /// </summary>
        public static string Grid_InstockAmt {
            get {
                return ResourceManager.GetString("Grid_InstockAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入库时间.
        /// </summary>
        public static string Grid_InStockTime {
            get {
                return ResourceManager.GetString("Grid_InStockTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发票状态.
        /// </summary>
        public static string Grid_InvoiceStatus {
            get {
                return ResourceManager.GetString("Grid_InvoiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作.
        /// </summary>
        public static string Grid_Operate {
            get {
                return ResourceManager.GetString("Grid_Operate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单据编号.
        /// </summary>
        public static string Grid_OrderID {
            get {
                return ResourceManager.GetString("Grid_OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单据状态.
        /// </summary>
        public static string Grid_OrderStatus {
            get {
                return ResourceManager.GetString("Grid_OrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单据类型.
        /// </summary>
        public static string Grid_OrderType {
            get {
                return ResourceManager.GetString("Grid_OrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应付.
        /// </summary>
        public static string Grid_PayableAmt {
            get {
                return ResourceManager.GetString("Grid_PayableAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 付款结算公司.
        /// </summary>
        public static string Grid_PaySettleCompany {
            get {
                return ResourceManager.GetString("Grid_PaySettleCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 付款状态.
        /// </summary>
        public static string Grid_PayStatus {
            get {
                return ResourceManager.GetString("Grid_PayStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 付款类型.
        /// </summary>
        public static string Grid_PayStyle {
            get {
                return ResourceManager.GetString("Grid_PayStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 剩余未付款.
        /// </summary>
        public static string Grid_Remainder {
            get {
                return ResourceManager.GetString("Grid_Remainder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用返点.
        /// </summary>
        public static string Grid_ReturnPoint {
            get {
                return ResourceManager.GetString("Grid_ReturnPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP凭证号.
        /// </summary>
        public static string Grid_SAPDocNo {
            get {
                return ResourceManager.GetString("Grid_SAPDocNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP导入结果.
        /// </summary>
        public static string Grid_SapImportedStatus {
            get {
                return ResourceManager.GetString("Grid_SapImportedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入失败原因.
        /// </summary>
        public static string Grid_SapInFailedReason {
            get {
                return ResourceManager.GetString("Grid_SapInFailedReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP导入时间.
        /// </summary>
        public static string Grid_SAPPostDate {
            get {
                return ResourceManager.GetString("Grid_SAPPostDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户.
        /// </summary>
        public static string Grid_UserName {
            get {
                return ResourceManager.GetString("Grid_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 供应商.
        /// </summary>
        public static string Grid_VendorName {
            get {
                return ResourceManager.GetString("Grid_VendorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 供应商编号.
        /// </summary>
        public static string Grid_VendorSysNo {
            get {
                return ResourceManager.GetString("Grid_VendorSysNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 调整单状态:.
        /// </summary>
        public static string Label_BalanceOrderStatus {
            get {
                return ResourceManager.GetString("Label_BalanceOrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建人:.
        /// </summary>
        public static string Label_CreatePM {
            get {
                return ResourceManager.GetString("Label_CreatePM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 货币类型:.
        /// </summary>
        public static string Label_Currency {
            get {
                return ResourceManager.GetString("Label_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本页统计 --- 应付: {0} 已付: {1} 未付: {2} SAP金额: {3}.
        /// </summary>
        public static string Label_CurrentPageStatistic {
            get {
                return ResourceManager.GetString("Label_CurrentPageStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 财务月结单状态:.
        /// </summary>
        public static string Label_FinanceSettleOrderStatus {
            get {
                return ResourceManager.GetString("Label_FinanceSettleOrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建时间:.
        /// </summary>
        public static string Label_InDate {
            get {
                return ResourceManager.GetString("Label_InDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入库时间:.
        /// </summary>
        public static string Label_InStockDate {
            get {
                return ResourceManager.GetString("Label_InStockDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发票状态:.
        /// </summary>
        public static string Label_InvoiceStatus {
            get {
                return ResourceManager.GetString("Label_InvoiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未入库.
        /// </summary>
        public static string Label_IsNotInStock {
            get {
                return ResourceManager.GetString("Label_IsNotInStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仅负单据.
        /// </summary>
        public static string Label_IsOnlyNegativeOrder {
            get {
                return ResourceManager.GetString("Label_IsOnlyNegativeOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应付时间:.
        /// </summary>
        public static string Label_OrderDate {
            get {
                return ResourceManager.GetString("Label_OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单据编号:.
        /// </summary>
        public static string Label_OrderID {
            get {
                return ResourceManager.GetString("Label_OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账期类型:.
        /// </summary>
        public static string Label_PayPeriodType {
            get {
                return ResourceManager.GetString("Label_PayPeriodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 付款结算公司:.
        /// </summary>
        public static string Label_PaySettleCompany {
            get {
                return ResourceManager.GetString("Label_PaySettleCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 付款状态:.
        /// </summary>
        public static string Label_PayStatus {
            get {
                return ResourceManager.GetString("Label_PayStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 付款类型:.
        /// </summary>
        public static string Label_PayStyle {
            get {
                return ResourceManager.GetString("Label_PayStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 归属PM:.
        /// </summary>
        public static string Label_POBelongPM {
            get {
                return ResourceManager.GetString("Label_POBelongPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预估付款时间:.
        /// </summary>
        public static string Label_POEGPDate {
            get {
                return ResourceManager.GetString("Label_POEGPDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预计付款时间:.
        /// </summary>
        public static string Label_POETPDate {
            get {
                return ResourceManager.GetString("Label_POETPDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO状态:.
        /// </summary>
        public static string Label_POStatus {
            get {
                return ResourceManager.GetString("Label_POStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO类型:.
        /// </summary>
        public static string Label_POType {
            get {
                return ResourceManager.GetString("Label_POType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仓库:.
        /// </summary>
        public static string Label_Stock {
            get {
                return ResourceManager.GetString("Label_Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有统计 --- 应付: {0} 已付: {1} 未付: {2} SAP金额: {3}.
        /// </summary>
        public static string Label_TotalStatistic {
            get {
                return ResourceManager.GetString("Label_TotalStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 供应商:.
        /// </summary>
        public static string Label_Vendor {
            get {
                return ResourceManager.GetString("Label_Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 供应商结算单状态:.
        /// </summary>
        public static string Label_VendorSettleStatus {
            get {
                return ResourceManager.GetString("Label_VendorSettleStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所属渠道:.
        /// </summary>
        public static string Label_WebChannel {
            get {
                return ResourceManager.GetString("Label_WebChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单据类型:.
        /// </summary>
        public static string Lable_OrderType {
            get {
                return ResourceManager.GetString("Lable_OrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未处理.
        /// </summary>
        public static string Msg_SapImportUnhandled {
            get {
                return ResourceManager.GetString("Msg_SapImportUnhandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先选择要处理的数据!.
        /// </summary>
        public static string Msg_SelectData {
            get {
                return ResourceManager.GetString("Msg_SelectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入数字，多个查询条件用(.)分隔!.
        /// </summary>
        public static string Msg_ValidateNoList {
            get {
                return ResourceManager.GetString("Msg_ValidateNoList", resourceCulture);
            }
        }
    }
}
