//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECCentral.Portal.UI.Invoice.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResPayItemQuery {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ResPayItemQuery() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ECCentral.Portal.UI.Invoice.Resources.ResPayItemQuery", typeof(ResPayItemQuery).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加付款单.
        /// </summary>
        public static string Button_Add {
            get {
                return ResourceManager.GetString("Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 批量付款.
        /// </summary>
        public static string Button_BatchPay {
            get {
                return ResourceManager.GetString("Button_BatchPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询.
        /// </summary>
        public static string Button_Search {
            get {
                return ResourceManager.GetString("Button_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置凭证号.
        /// </summary>
        public static string Button_SetReferenceID {
            get {
                return ResourceManager.GetString("Button_SetReferenceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合计选择项.
        /// </summary>
        public static string Button_TotalCalc {
            get {
                return ResourceManager.GetString("Button_TotalCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 过滤作废状态的付款单.
        /// </summary>
        public static string CheckBox_IsFilterAbandonItem {
            get {
                return ResourceManager.GetString("CheckBox_IsFilterAbandonItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 到期的未付款采购单明细.
        /// </summary>
        public static string CheckBox_IsFilterPOETP {
            get {
                return ResourceManager.GetString("CheckBox_IsFilterPOETP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未入库（PO）.
        /// </summary>
        public static string CheckBox_NotInStockPO {
            get {
                return ResourceManager.GetString("CheckBox_NotInStockPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询条件.
        /// </summary>
        public static string Expander_QueryFilter {
            get {
                return ResourceManager.GetString("Expander_QueryFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询结果.
        /// </summary>
        public static string Expander_QueryResult {
            get {
                return ResourceManager.GetString("Expander_QueryResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 银行记账科目.
        /// </summary>
        public static string Grid_BankGLAccount {
            get {
                return ResourceManager.GetString("Grid_BankGLAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建时间.
        /// </summary>
        public static string Grid_CreateTime {
            get {
                return ResourceManager.GetString("Grid_CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 货币.
        /// </summary>
        public static string Grid_Currency {
            get {
                return ResourceManager.GetString("Grid_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预计付款时间.
        /// </summary>
        public static string Grid_EstimatePayTime {
            get {
                return ResourceManager.GetString("Grid_EstimatePayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发票状态.
        /// </summary>
        public static string Grid_InvoiceStatus {
            get {
                return ResourceManager.GetString("Grid_InvoiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发票状态修改.
        /// </summary>
        public static string Grid_InvoiceUpdate {
            get {
                return ResourceManager.GetString("Grid_InvoiceUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作.
        /// </summary>
        public static string Grid_Operate {
            get {
                return ResourceManager.GetString("Grid_Operate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单据编号.
        /// </summary>
        public static string Grid_OrderID {
            get {
                return ResourceManager.GetString("Grid_OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 付款金额.
        /// </summary>
        public static string Grid_PayAmt {
            get {
                return ResourceManager.GetString("Grid_PayAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统编号.
        /// </summary>
        public static string Grid_PayItemSysNo {
            get {
                return ResourceManager.GetString("Grid_PayItemSysNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 付款结算公司.
        /// </summary>
        public static string Grid_PaySettleCompany {
            get {
                return ResourceManager.GetString("Grid_PaySettleCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 付款状态.
        /// </summary>
        public static string Grid_PayStatus {
            get {
                return ResourceManager.GetString("Grid_PayStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支付类型.
        /// </summary>
        public static string Grid_PayStyle {
            get {
                return ResourceManager.GetString("Grid_PayStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 付款时间.
        /// </summary>
        public static string Grid_PayTime {
            get {
                return ResourceManager.GetString("Grid_PayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 凭证号.
        /// </summary>
        public static string Grid_ReferenceID {
            get {
                return ResourceManager.GetString("Grid_ReferenceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 返点.
        /// </summary>
        public static string Grid_ReturnPoint {
            get {
                return ResourceManager.GetString("Grid_ReturnPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP凭证号.
        /// </summary>
        public static string Grid_SAPDocNo {
            get {
                return ResourceManager.GetString("Grid_SAPDocNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP导入结果.
        /// </summary>
        public static string Grid_SapImportedStatus {
            get {
                return ResourceManager.GetString("Grid_SapImportedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP导入时间.
        /// </summary>
        public static string Grid_SAPPostDate {
            get {
                return ResourceManager.GetString("Grid_SAPPostDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 供应商.
        /// </summary>
        public static string Grid_Vendor {
            get {
                return ResourceManager.GetString("Grid_Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 供应商编号.
        /// </summary>
        public static string Grid_VendorSysNo {
            get {
                return ResourceManager.GetString("Grid_VendorSysNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑.
        /// </summary>
        public static string Hyperlink_Edit {
            get {
                return ResourceManager.GetString("Hyperlink_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 批量设置凭证号.
        /// </summary>
        public static string Message_BatchSetReferenceIDDlgTitle {
            get {
                return ResourceManager.GetString("Message_BatchSetReferenceIDDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 现金单据{0}不支持批量付.
        /// </summary>
        public static string Message_CashCannotBatchPayDlgTitle {
            get {
                return ResourceManager.GetString("Message_CashCannotBatchPayDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认要进行批量付款操作?.
        /// </summary>
        public static string Message_ConfirmBatchPayDlgTitle {
            get {
                return ResourceManager.GetString("Message_ConfirmBatchPayDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发票状态修改.
        /// </summary>
        public static string Message_InvoiceStatusModifyDlgTitle {
            get {
                return ResourceManager.GetString("Message_InvoiceStatusModifyDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未处理.
        /// </summary>
        public static string Message_SapImportUnhandled {
            get {
                return ResourceManager.GetString("Message_SapImportUnhandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置凭证号.
        /// </summary>
        public static string Message_SetReferenceIDDlgTitle {
            get {
                return ResourceManager.GetString("Message_SetReferenceIDDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本页合计: {0} 当前选择了{1}条, 合计:{2}
        ///所有合计: {3}.
        /// </summary>
        public static string Message_StatisticInfo {
            get {
                return ResourceManager.GetString("Message_StatisticInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入数字，多个查询条件用(.)分隔!.
        /// </summary>
        public static string Msg_ValidateNoList {
            get {
                return ResourceManager.GetString("Msg_ValidateNoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建时间:.
        /// </summary>
        public static string TextBlock_CreateDate {
            get {
                return ResourceManager.GetString("TextBlock_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预计付款时间:.
        /// </summary>
        public static string TextBlock_EstimatePayDate {
            get {
                return ResourceManager.GetString("TextBlock_EstimatePayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 到期付款日:.
        /// </summary>
        public static string TextBlock_ETP {
            get {
                return ResourceManager.GetString("TextBlock_ETP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发票状态修改时间:.
        /// </summary>
        public static string TextBlock_InvoiceEditDate {
            get {
                return ResourceManager.GetString("TextBlock_InvoiceEditDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发票状态:.
        /// </summary>
        public static string TextBlock_InvoiceStatus {
            get {
                return ResourceManager.GetString("TextBlock_InvoiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 备注:.
        /// </summary>
        public static string TextBlock_Note {
            get {
                return ResourceManager.GetString("TextBlock_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单据编号:.
        /// </summary>
        public static string TextBlock_OrderID {
            get {
                return ResourceManager.GetString("TextBlock_OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单据类型:.
        /// </summary>
        public static string TextBlock_OrderType {
            get {
                return ResourceManager.GetString("TextBlock_OrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 付款时间:.
        /// </summary>
        public static string TextBlock_PayDate {
            get {
                return ResourceManager.GetString("TextBlock_PayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 付款结算公司:.
        /// </summary>
        public static string TextBlock_PaySettleCompany {
            get {
                return ResourceManager.GetString("TextBlock_PaySettleCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 付款类型:.
        /// </summary>
        public static string TextBlock_PayStyle {
            get {
                return ResourceManager.GetString("TextBlock_PayStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 凭证号:.
        /// </summary>
        public static string TextBlock_ReferenceID {
            get {
                return ResourceManager.GetString("TextBlock_ReferenceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 付款状态:.
        /// </summary>
        public static string TextBlock_Status {
            get {
                return ResourceManager.GetString("TextBlock_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仓库:.
        /// </summary>
        public static string TextBlock_Stock {
            get {
                return ResourceManager.GetString("TextBlock_Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 供应商:.
        /// </summary>
        public static string TextBlock_Vendor {
            get {
                return ResourceManager.GetString("TextBlock_Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所属渠道:.
        /// </summary>
        public static string TextBlock_WebChannel {
            get {
                return ResourceManager.GetString("TextBlock_WebChannel", resourceCulture);
            }
        }
    }
}
