//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECCentral.Portal.UI.Invoice.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResSalesStatisticsReport {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ResSalesStatisticsReport()
        {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ECCentral.Portal.UI.Invoice.Resources.ResSalesStatisticsReport", typeof(ResSalesStatisticsReport).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询.
        /// </summary>
        public static string Button_Query {
            get {
                return ResourceManager.GetString("Button_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始时间.
        /// </summary>
        public static string Grid_BeginDate {
            get {
                return ResourceManager.GetString("Grid_BeginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BM编号.
        /// </summary>
        public static string Grid_BMCode {
            get {
                return ResourceManager.GetString("Grid_BMCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 品牌.
        /// </summary>
        public static string Grid_Brand {
            get {
                return ResourceManager.GetString("Grid_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一级分类.
        /// </summary>
        public static string Grid_C1 {
            get {
                return ResourceManager.GetString("Grid_C1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 二级分类.
        /// </summary>
        public static string Grid_C2 {
            get {
                return ResourceManager.GetString("Grid_C2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 三级分类.
        /// </summary>
        public static string Grid_C3 {
            get {
                return ResourceManager.GetString("Grid_C3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结束时间.
        /// </summary>
        public static string Grid_EndDate {
            get {
                return ResourceManager.GetString("Grid_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支付方式.
        /// </summary>
        public static string Grid_PayType {
            get {
                return ResourceManager.GetString("Grid_PayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 销售成本.
        /// </summary>
        public static string Grid_ProductCost {
            get {
                return ResourceManager.GetString("Grid_ProductCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品毛利.
        /// </summary>
        public static string Grid_ProductGrossMargin {
            get {
                return ResourceManager.GetString("Grid_ProductGrossMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品ID.
        /// </summary>
        public static string Grid_ProductID {
            get {
                return ResourceManager.GetString("Grid_ProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品名称.
        /// </summary>
        public static string Grid_ProductName {
            get {
                return ResourceManager.GetString("Grid_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 销售金额.
        /// </summary>
        public static string Grid_ProductPriceAmount {
            get {
                return ResourceManager.GetString("Grid_ProductPriceAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性1.
        /// </summary>
        public static string Grid_ProductProperty1 {
            get {
                return ResourceManager.GetString("Grid_ProductProperty1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性2.
        /// </summary>
        public static string Grid_ProductProperty2 {
            get {
                return ResourceManager.GetString("Grid_ProductProperty2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 实际销售金额.
        /// </summary>
        public static string Grid_ProductSaleAmount {
            get {
                return ResourceManager.GetString("Grid_ProductSaleAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 优惠金额.
        /// </summary>
        public static string Grid_PromotionDiscountAmount {
            get {
                return ResourceManager.GetString("Grid_PromotionDiscountAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数量.
        /// </summary>
        public static string Grid_Quantity {
            get {
                return ResourceManager.GetString("Grid_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仓库.
        /// </summary>
        public static string Grid_StockName {
            get {
                return ResourceManager.GetString("Grid_StockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 供应商.
        /// </summary>
        public static string Grid_Vendor {
            get {
                return ResourceManager.GetString("Grid_Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}： --- 销售成本：{1}  销售金额：{2}  优惠金额：{3}  实际销售金额：{4}  商品毛利：{5}.
        /// </summary>
        public static string Message_StatisticInfo {
            get {
                return ResourceManager.GetString("Message_StatisticInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 品牌：.
        /// </summary>
        public static string TextBlock_Brand {
            get {
                return ResourceManager.GetString("TextBlock_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分类：.
        /// </summary>
        public static string TextBlock_Category {
            get {
                return ResourceManager.GetString("TextBlock_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品ID：.
        /// </summary>
        public static string TextBlock_ProductID {
            get {
                return ResourceManager.GetString("TextBlock_ProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 销售日期：.
        /// </summary>
        public static string TextBlock_SODate {
            get {
                return ResourceManager.GetString("TextBlock_SODate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 订单状态 :.
        /// </summary>
        public static string TextBlock_SOStatus {
            get {
                return ResourceManager.GetString("TextBlock_SOStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仓库：.
        /// </summary>
        public static string TextBlock_Stock {
            get {
                return ResourceManager.GetString("TextBlock_Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 供应商：.
        /// </summary>
        public static string TextBlock_Vendor {
            get {
                return ResourceManager.GetString("TextBlock_Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询条件.
        /// </summary>
        public static string Toolkit_QueryCondition {
            get {
                return ResourceManager.GetString("Toolkit_QueryCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询结果.
        /// </summary>
        public static string Toolkit_QueryResult {
            get {
                return ResourceManager.GetString("Toolkit_QueryResult", resourceCulture);
            }
        }
    }
}
