//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECCentral.Portal.UI.Invoice.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResUCPOVendorInvoiceMaintain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ResUCPOVendorInvoiceMaintain()
        {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ECCentral.Portal.UI.Invoice.Resources.ResUCPOVendorInvoiceMaintain", typeof(ResUCPOVendorInvoiceMaintain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字段不能为空!.
        /// </summary>
        public static string Message_CurrencyRequird {
            get {
                return ResourceManager.GetString("Message_CurrencyRequird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 审核时间:.
        /// </summary>
        public static string TextBlock_AuditTime {
            get {
                return ResourceManager.GetString("TextBlock_AuditTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 审核者:.
        /// </summary>
        public static string TextBlock_AuditUser {
            get {
                return ResourceManager.GetString("TextBlock_AuditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 货款额:.
        /// </summary>
        public static string TextBlock_GoodsAmt {
            get {
                return ResourceManager.GetString("TextBlock_GoodsAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发票录入时间:.
        /// </summary>
        public static string TextBlock_InputTime {
            get {
                return ResourceManager.GetString("TextBlock_InputTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发票录入者:.
        /// </summary>
        public static string TextBlock_InputUser {
            get {
                return ResourceManager.GetString("TextBlock_InputUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发票号:.
        /// </summary>
        public static string TextBlock_InvoiceNumber {
            get {
                return ResourceManager.GetString("TextBlock_InvoiceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发票开票时间:.
        /// </summary>
        public static string TextBlock_InvoiceTime {
            get {
                return ResourceManager.GetString("TextBlock_InvoiceTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 备注:.
        /// </summary>
        public static string TextBlock_Note {
            get {
                return ResourceManager.GetString("TextBlock_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仓库:.
        /// </summary>
        public static string TextBlock_Stock {
            get {
                return ResourceManager.GetString("TextBlock_Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 税额:.
        /// </summary>
        public static string TextBlock_TaxAmt {
            get {
                return ResourceManager.GetString("TextBlock_TaxAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总额:.
        /// </summary>
        public static string TextBlock_TotalAmt {
            get {
                return ResourceManager.GetString("TextBlock_TotalAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新时间:.
        /// </summary>
        public static string TextBlock_UpdateTime {
            get {
                return ResourceManager.GetString("TextBlock_UpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新者:.
        /// </summary>
        public static string TextBlock_UpdateUser {
            get {
                return ResourceManager.GetString("TextBlock_UpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 供应商:.
        /// </summary>
        public static string TextBlock_Vendor {
            get {
                return ResourceManager.GetString("TextBlock_Vendor", resourceCulture);
            }
        }
    }
}
