//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECCentral.Portal.UI.Inventory.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResTransferStockingCenter {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ResTransferStockingCenter()
        {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ECCentral.Portal.UI.Inventory.Resources.ResTransferStockingCenter", typeof(ResTransferStockingCenter).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空采购数量.
        /// </summary>
        public static string Button_ClearPurchase {
            get {
                return ResourceManager.GetString("Button_ClearPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 采购.
        /// </summary>
        public static string Button_Purchaset {
            get {
                return ResourceManager.GetString("Button_Purchaset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移仓.
        /// </summary>
        public static string Button_Shift {
            get {
                return ResourceManager.GetString("Button_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 立即同步.
        /// </summary>
        public static string Button_Sync {
            get {
                return ResourceManager.GetString("Button_Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当日备货提醒.
        /// </summary>
        public static string Button_TransferStockingAlert {
            get {
                return ResourceManager.GetString("Button_TransferStockingAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看采购篮.
        /// </summary>
        public static string Button_ViewBasket {
            get {
                return ResourceManager.GetString("Button_ViewBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看移仓篮.
        /// </summary>
        public static string Button_ViewShift {
            get {
                return ResourceManager.GetString("Button_ViewShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入格式正确!.
        /// </summary>
        public static string ErrorMsg_ValidateDecimal {
            get {
                return ResourceManager.GetString("ErrorMsg_ValidateDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总可用库存.
        /// </summary>
        public static string Info_AllAvailableQty {
            get {
                return ResourceManager.GetString("Info_AllAvailableQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当天出库量.
        /// </summary>
        public static string Info_AllOutStockQuantity {
            get {
                return ResourceManager.GetString("Info_AllOutStockQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 香港可用库存.
        /// </summary>
        public static string Info_BJ_AvailableQty {
            get {
                return ResourceManager.GetString("Info_BJ_AvailableQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 香港仓可销售天数.
        /// </summary>
        public static string Info_BJ_AvailableSalesDays {
            get {
                return ResourceManager.GetString("Info_BJ_AvailableSalesDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可移库存.
        /// </summary>
        public static string Info_BJ_AvailableShifOutQty {
            get {
                return ResourceManager.GetString("Info_BJ_AvailableShifOutQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 香港仓覆盖区域日均销量.
        /// </summary>
        public static string Info_BJ_AVGDailySales {
            get {
                return ResourceManager.GetString("Info_BJ_AVGDailySales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 香港仓代销库存数量.
        /// </summary>
        public static string Info_BJ_ConsignQty {
            get {
                return ResourceManager.GetString("Info_BJ_ConsignQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 香港D1.
        /// </summary>
        public static string Info_BJ_D1 {
            get {
                return ResourceManager.GetString("Info_BJ_D1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 香港D2.
        /// </summary>
        public static string Info_BJ_D2 {
            get {
                return ResourceManager.GetString("Info_BJ_D2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 香港D3.
        /// </summary>
        public static string Info_BJ_D3 {
            get {
                return ResourceManager.GetString("Info_BJ_D3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 香港D4.
        /// </summary>
        public static string Info_BJ_D4 {
            get {
                return ResourceManager.GetString("Info_BJ_D4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 香港D5.
        /// </summary>
        public static string Info_BJ_D5 {
            get {
                return ResourceManager.GetString("Info_BJ_D5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 香港D6.
        /// </summary>
        public static string Info_BJ_D6 {
            get {
                return ResourceManager.GetString("Info_BJ_D6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 香港D7.
        /// </summary>
        public static string Info_BJ_D7 {
            get {
                return ResourceManager.GetString("Info_BJ_D7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否中转.
        /// </summary>
        public static string Info_BJ_IsNeedBuffer {
            get {
                return ResourceManager.GetString("Info_BJ_IsNeedBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 香港最后一次采购时间.
        /// </summary>
        public static string Info_BJ_Lastintime {
            get {
                return ResourceManager.GetString("Info_BJ_Lastintime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 香港最后一次采购价格.
        /// </summary>
        public static string Info_BJ_LastPrice {
            get {
                return ResourceManager.GetString("Info_BJ_LastPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 香港M1.
        /// </summary>
        public static string Info_BJ_M1 {
            get {
                return ResourceManager.GetString("Info_BJ_M1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 香港仓覆盖地区M1.
        /// </summary>
        public static string Info_BJ_M1RegionSalesQty {
            get {
                return ResourceManager.GetString("Info_BJ_M1RegionSalesQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 香港M2.
        /// </summary>
        public static string Info_BJ_M2 {
            get {
                return ResourceManager.GetString("Info_BJ_M2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 香港M3.
        /// </summary>
        public static string Info_BJ_M3 {
            get {
                return ResourceManager.GetString("Info_BJ_M3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 京仓被订购数量.
        /// </summary>
        public static string Info_BJ_OrderQty {
            get {
                return ResourceManager.GetString("Info_BJ_OrderQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 香港采购单据数量.
        /// </summary>
        public static string Info_BJ_PurchaseInQty {
            get {
                return ResourceManager.GetString("Info_BJ_PurchaseInQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 采购价格.
        /// </summary>
        public static string Info_BJ_PurchasePrice {
            get {
                return ResourceManager.GetString("Info_BJ_PurchasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 采购数量.
        /// </summary>
        public static string Info_BJ_PurchaseQty {
            get {
                return ResourceManager.GetString("Info_BJ_PurchaseQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 香港采购信息设置.
        /// </summary>
        public static string Info_BJ_SetPurchaseInfo {
            get {
                return ResourceManager.GetString("Info_BJ_SetPurchaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 香港移仓信息设置.
        /// </summary>
        public static string Info_BJ_SetShiftInfo {
            get {
                return ResourceManager.GetString("Info_BJ_SetShiftInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移仓出库仓.
        /// </summary>
        public static string Info_BJ_ShifOutStock {
            get {
                return ResourceManager.GetString("Info_BJ_ShifOutStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移仓数量.
        /// </summary>
        public static string Info_BJ_ShifQty {
            get {
                return ResourceManager.GetString("Info_BJ_ShifQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 香港移仓在途数量.
        /// </summary>
        public static string Info_BJ_ShiftInQty {
            get {
                return ResourceManager.GetString("Info_BJ_ShiftInQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 香港仓建议备货数量.
        /// </summary>
        public static string Info_BJ_SuggestQtyDisplay {
            get {
                return ResourceManager.GetString("Info_BJ_SuggestQtyDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 香港虚库库存.
        /// </summary>
        public static string Info_BJ_VirtualQty {
            get {
                return ResourceManager.GetString("Info_BJ_VirtualQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 香港W1.
        /// </summary>
        public static string Info_BJ_W1 {
            get {
                return ResourceManager.GetString("Info_BJ_W1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 香港仓覆盖地区W1.
        /// </summary>
        public static string Info_BJ_W1RegionSalesQty {
            get {
                return ResourceManager.GetString("Info_BJ_W1RegionSalesQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 香港W2.
        /// </summary>
        public static string Info_BJ_W2 {
            get {
                return ResourceManager.GetString("Info_BJ_W2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 香港W3.
        /// </summary>
        public static string Info_BJ_W3 {
            get {
                return ResourceManager.GetString("Info_BJ_W3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 香港W4.
        /// </summary>
        public static string Info_BJ_W4 {
            get {
                return ResourceManager.GetString("Info_BJ_W4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 品牌.
        /// </summary>
        public static string Info_Brand {
            get {
                return ResourceManager.GetString("Info_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可移库存.
        /// </summary>
        public static string Info_BS_AvailableShifOutQty {
            get {
                return ResourceManager.GetString("Info_BS_AvailableShifOutQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本采购数量.
        /// </summary>
        public static string Info_BS_PurchaseQty {
            get {
                return ResourceManager.GetString("Info_BS_PurchaseQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本移仓信息设置.
        /// </summary>
        public static string Info_BS_SetPurchaseInfo {
            get {
                return ResourceManager.GetString("Info_BS_SetPurchaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移仓出库仓.
        /// </summary>
        public static string Info_BS_ShifOutStock {
            get {
                return ResourceManager.GetString("Info_BS_ShifOutStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移仓数量.
        /// </summary>
        public static string Info_BS_ShifQty {
            get {
                return ResourceManager.GetString("Info_BS_ShifQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成都可用库存.
        /// </summary>
        public static string Info_CD_AvailableQty {
            get {
                return ResourceManager.GetString("Info_CD_AvailableQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成都仓可销售天数.
        /// </summary>
        public static string Info_CD_AvailableSalesDays {
            get {
                return ResourceManager.GetString("Info_CD_AvailableSalesDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可移库存.
        /// </summary>
        public static string Info_CD_AvailableShifOutQty {
            get {
                return ResourceManager.GetString("Info_CD_AvailableShifOutQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成都仓覆盖区域日均销量.
        /// </summary>
        public static string Info_CD_AVGDailySales {
            get {
                return ResourceManager.GetString("Info_CD_AVGDailySales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成都仓代销库存数量.
        /// </summary>
        public static string Info_CD_ConsignQty {
            get {
                return ResourceManager.GetString("Info_CD_ConsignQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成都D1.
        /// </summary>
        public static string Info_CD_D1 {
            get {
                return ResourceManager.GetString("Info_CD_D1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成都D2.
        /// </summary>
        public static string Info_CD_D2 {
            get {
                return ResourceManager.GetString("Info_CD_D2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成都D3.
        /// </summary>
        public static string Info_CD_D3 {
            get {
                return ResourceManager.GetString("Info_CD_D3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成都D4.
        /// </summary>
        public static string Info_CD_D4 {
            get {
                return ResourceManager.GetString("Info_CD_D4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成都D5.
        /// </summary>
        public static string Info_CD_D5 {
            get {
                return ResourceManager.GetString("Info_CD_D5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成都D6.
        /// </summary>
        public static string Info_CD_D6 {
            get {
                return ResourceManager.GetString("Info_CD_D6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成都D7.
        /// </summary>
        public static string Info_CD_D7 {
            get {
                return ResourceManager.GetString("Info_CD_D7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否中转.
        /// </summary>
        public static string Info_CD_IsNeedBuffer {
            get {
                return ResourceManager.GetString("Info_CD_IsNeedBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成都最后一次采购时间.
        /// </summary>
        public static string Info_CD_Lastintime {
            get {
                return ResourceManager.GetString("Info_CD_Lastintime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成都最后一次采购价格.
        /// </summary>
        public static string Info_CD_LastPrice {
            get {
                return ResourceManager.GetString("Info_CD_LastPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成都M1.
        /// </summary>
        public static string Info_CD_M1 {
            get {
                return ResourceManager.GetString("Info_CD_M1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成都仓覆盖地区M1.
        /// </summary>
        public static string Info_CD_M1RegionSalesQty {
            get {
                return ResourceManager.GetString("Info_CD_M1RegionSalesQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成都M2.
        /// </summary>
        public static string Info_CD_M2 {
            get {
                return ResourceManager.GetString("Info_CD_M2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成都M3.
        /// </summary>
        public static string Info_CD_M3 {
            get {
                return ResourceManager.GetString("Info_CD_M3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成都仓被订购数量.
        /// </summary>
        public static string Info_CD_OrderQty {
            get {
                return ResourceManager.GetString("Info_CD_OrderQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成都采购单据数量.
        /// </summary>
        public static string Info_CD_PurchaseInQty {
            get {
                return ResourceManager.GetString("Info_CD_PurchaseInQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 采购价格.
        /// </summary>
        public static string Info_CD_PurchasePrice {
            get {
                return ResourceManager.GetString("Info_CD_PurchasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 采购数量.
        /// </summary>
        public static string Info_CD_PurchaseQty {
            get {
                return ResourceManager.GetString("Info_CD_PurchaseQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成都采购信息设置.
        /// </summary>
        public static string Info_CD_SetPurchaseInfo {
            get {
                return ResourceManager.GetString("Info_CD_SetPurchaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成都移仓信息设置.
        /// </summary>
        public static string Info_CD_SetShiftInfo {
            get {
                return ResourceManager.GetString("Info_CD_SetShiftInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移仓出库仓.
        /// </summary>
        public static string Info_CD_ShifOutStock {
            get {
                return ResourceManager.GetString("Info_CD_ShifOutStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移仓数量.
        /// </summary>
        public static string Info_CD_ShifQty {
            get {
                return ResourceManager.GetString("Info_CD_ShifQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成都移仓在途数量.
        /// </summary>
        public static string Info_CD_ShiftInQty {
            get {
                return ResourceManager.GetString("Info_CD_ShiftInQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成都仓建议备货数量.
        /// </summary>
        public static string Info_CD_SuggestQtyDisplay {
            get {
                return ResourceManager.GetString("Info_CD_SuggestQtyDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成都虚库库存.
        /// </summary>
        public static string Info_CD_VirtualQty {
            get {
                return ResourceManager.GetString("Info_CD_VirtualQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成都W1.
        /// </summary>
        public static string Info_CD_W1 {
            get {
                return ResourceManager.GetString("Info_CD_W1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成都仓覆盖地区W1.
        /// </summary>
        public static string Info_CD_W1RegionSalesQty {
            get {
                return ResourceManager.GetString("Info_CD_W1RegionSalesQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成都W2.
        /// </summary>
        public static string Info_CD_W2 {
            get {
                return ResourceManager.GetString("Info_CD_W2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成都W3.
        /// </summary>
        public static string Info_CD_W3 {
            get {
                return ResourceManager.GetString("Info_CD_W3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成都W4.
        /// </summary>
        public static string Info_CD_W4 {
            get {
                return ResourceManager.GetString("Info_CD_W4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总代销库存.
        /// </summary>
        public static string Info_ConsignQty {
            get {
                return ResourceManager.GetString("Info_ConsignQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 泰隆优选价格.
        /// </summary>
        public static string Info_CurrentPrice {
            get {
                return ResourceManager.GetString("Info_CurrentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 毛利率.
        /// </summary>
        public static string Info_GrossProfitRate {
            get {
                return ResourceManager.GetString("Info_GrossProfitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上海可用库存.
        /// </summary>
        public static string Info_GZ_AvailableQty {
            get {
                return ResourceManager.GetString("Info_GZ_AvailableQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上海仓可销售天数.
        /// </summary>
        public static string Info_GZ_AvailableSalesDays {
            get {
                return ResourceManager.GetString("Info_GZ_AvailableSalesDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可移库存.
        /// </summary>
        public static string Info_GZ_AvailableShifOutQty {
            get {
                return ResourceManager.GetString("Info_GZ_AvailableShifOutQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上海仓覆盖区域日均销量.
        /// </summary>
        public static string Info_GZ_AVGDailySales {
            get {
                return ResourceManager.GetString("Info_GZ_AVGDailySales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上海仓代销库存数量.
        /// </summary>
        public static string Info_GZ_ConsignQty {
            get {
                return ResourceManager.GetString("Info_GZ_ConsignQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上海D1.
        /// </summary>
        public static string Info_GZ_D1 {
            get {
                return ResourceManager.GetString("Info_GZ_D1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上海D2.
        /// </summary>
        public static string Info_GZ_D2 {
            get {
                return ResourceManager.GetString("Info_GZ_D2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上海D3.
        /// </summary>
        public static string Info_GZ_D3 {
            get {
                return ResourceManager.GetString("Info_GZ_D3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上海D4.
        /// </summary>
        public static string Info_GZ_D4 {
            get {
                return ResourceManager.GetString("Info_GZ_D4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上海D5.
        /// </summary>
        public static string Info_GZ_D5 {
            get {
                return ResourceManager.GetString("Info_GZ_D5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上海D6.
        /// </summary>
        public static string Info_GZ_D6 {
            get {
                return ResourceManager.GetString("Info_GZ_D6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上海D7.
        /// </summary>
        public static string Info_GZ_D7 {
            get {
                return ResourceManager.GetString("Info_GZ_D7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否中转.
        /// </summary>
        public static string Info_GZ_IsNeedBuffer {
            get {
                return ResourceManager.GetString("Info_GZ_IsNeedBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上海最后一次采购时间.
        /// </summary>
        public static string Info_GZ_Lastintime {
            get {
                return ResourceManager.GetString("Info_GZ_Lastintime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上海最后一次采购价格.
        /// </summary>
        public static string Info_GZ_LastPrice {
            get {
                return ResourceManager.GetString("Info_GZ_LastPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上海M1.
        /// </summary>
        public static string Info_GZ_M1 {
            get {
                return ResourceManager.GetString("Info_GZ_M1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上海仓覆盖地区M1.
        /// </summary>
        public static string Info_GZ_M1RegionSalesQty {
            get {
                return ResourceManager.GetString("Info_GZ_M1RegionSalesQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上海M2.
        /// </summary>
        public static string Info_GZ_M2 {
            get {
                return ResourceManager.GetString("Info_GZ_M2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上海M3.
        /// </summary>
        public static string Info_GZ_M3 {
            get {
                return ResourceManager.GetString("Info_GZ_M3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上海仓被订购数量.
        /// </summary>
        public static string Info_GZ_OrderQty {
            get {
                return ResourceManager.GetString("Info_GZ_OrderQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上海采购单据数量.
        /// </summary>
        public static string Info_GZ_PurchaseInQty {
            get {
                return ResourceManager.GetString("Info_GZ_PurchaseInQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 采购价格.
        /// </summary>
        public static string Info_GZ_PurchasePrice {
            get {
                return ResourceManager.GetString("Info_GZ_PurchasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 采购数量.
        /// </summary>
        public static string Info_GZ_PurchaseQty {
            get {
                return ResourceManager.GetString("Info_GZ_PurchaseQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上海采购信息设置.
        /// </summary>
        public static string Info_GZ_SetPurchaseInfo {
            get {
                return ResourceManager.GetString("Info_GZ_SetPurchaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上海移仓信息设置.
        /// </summary>
        public static string Info_GZ_SetShiftInfo {
            get {
                return ResourceManager.GetString("Info_GZ_SetShiftInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移仓出库仓.
        /// </summary>
        public static string Info_GZ_ShifOutStock {
            get {
                return ResourceManager.GetString("Info_GZ_ShifOutStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移仓数量.
        /// </summary>
        public static string Info_GZ_ShifQty {
            get {
                return ResourceManager.GetString("Info_GZ_ShifQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上海移仓在途数量.
        /// </summary>
        public static string Info_GZ_ShiftInQty {
            get {
                return ResourceManager.GetString("Info_GZ_ShiftInQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上海仓建议备货数量.
        /// </summary>
        public static string Info_GZ_SuggestQtyDisplay {
            get {
                return ResourceManager.GetString("Info_GZ_SuggestQtyDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上海虚库库存.
        /// </summary>
        public static string Info_GZ_VirtualQty {
            get {
                return ResourceManager.GetString("Info_GZ_VirtualQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上海W1.
        /// </summary>
        public static string Info_GZ_W1 {
            get {
                return ResourceManager.GetString("Info_GZ_W1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上海仓覆盖地区W1.
        /// </summary>
        public static string Info_GZ_W1RegionSalesQty {
            get {
                return ResourceManager.GetString("Info_GZ_W1RegionSalesQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上海W2.
        /// </summary>
        public static string Info_GZ_W2 {
            get {
                return ResourceManager.GetString("Info_GZ_W2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上海W3.
        /// </summary>
        public static string Info_GZ_W3 {
            get {
                return ResourceManager.GetString("Info_GZ_W3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上海W4.
        /// </summary>
        public static string Info_GZ_W4 {
            get {
                return ResourceManager.GetString("Info_GZ_W4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 库存同步数量.
        /// </summary>
        public static string Info_InventoryQty {
            get {
                return ResourceManager.GetString("Info_InventoryQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统编号.
        /// </summary>
        public static string Info_ItemSysNumber {
            get {
                return ResourceManager.GetString("Info_ItemSysNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可移库存.
        /// </summary>
        public static string Info_JD_AvailableShifQty {
            get {
                return ResourceManager.GetString("Info_JD_AvailableShifQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 嘉定采购数量.
        /// </summary>
        public static string Info_JD_PurchaseQty {
            get {
                return ResourceManager.GetString("Info_JD_PurchaseQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 嘉定移仓信息设置.
        /// </summary>
        public static string Info_JD_SetPurchaseInfo {
            get {
                return ResourceManager.GetString("Info_JD_SetPurchaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移仓出库仓.
        /// </summary>
        public static string Info_JD_ShifOutStock {
            get {
                return ResourceManager.GetString("Info_JD_ShifOutStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移仓数量.
        /// </summary>
        public static string Info_JD_ShifQty {
            get {
                return ResourceManager.GetString("Info_JD_ShifQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 京东价格.
        /// </summary>
        public static string Info_JDPrice {
            get {
                return ResourceManager.GetString("Info_JDPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昆明可用库存.
        /// </summary>
        public static string Info_KM_AvailableQty {
            get {
                return ResourceManager.GetString("Info_KM_AvailableQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昆明仓可销售天数.
        /// </summary>
        public static string Info_KM_AvailableSalesDays {
            get {
                return ResourceManager.GetString("Info_KM_AvailableSalesDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可移库存.
        /// </summary>
        public static string Info_KM_AvailableShifOutQty {
            get {
                return ResourceManager.GetString("Info_KM_AvailableShifOutQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昆明仓覆盖区域日均销量.
        /// </summary>
        public static string Info_KM_AVGDailySales {
            get {
                return ResourceManager.GetString("Info_KM_AVGDailySales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昆明仓代销库存数量.
        /// </summary>
        public static string Info_KM_ConsignQty {
            get {
                return ResourceManager.GetString("Info_KM_ConsignQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昆明D1.
        /// </summary>
        public static string Info_KM_D1 {
            get {
                return ResourceManager.GetString("Info_KM_D1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昆明D2.
        /// </summary>
        public static string Info_KM_D2 {
            get {
                return ResourceManager.GetString("Info_KM_D2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昆明D3.
        /// </summary>
        public static string Info_KM_D3 {
            get {
                return ResourceManager.GetString("Info_KM_D3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昆明D4.
        /// </summary>
        public static string Info_KM_D4 {
            get {
                return ResourceManager.GetString("Info_KM_D4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昆明D5.
        /// </summary>
        public static string Info_KM_D5 {
            get {
                return ResourceManager.GetString("Info_KM_D5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昆明D6.
        /// </summary>
        public static string Info_KM_D6 {
            get {
                return ResourceManager.GetString("Info_KM_D6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昆明D7.
        /// </summary>
        public static string Info_KM_D7 {
            get {
                return ResourceManager.GetString("Info_KM_D7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否中转.
        /// </summary>
        public static string Info_KM_IsNeedBuffer {
            get {
                return ResourceManager.GetString("Info_KM_IsNeedBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昆明最后一次采购时间.
        /// </summary>
        public static string Info_KM_Lastintime {
            get {
                return ResourceManager.GetString("Info_KM_Lastintime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昆明最后一次采购价格.
        /// </summary>
        public static string Info_KM_LastPrice {
            get {
                return ResourceManager.GetString("Info_KM_LastPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昆明M1.
        /// </summary>
        public static string Info_KM_M1 {
            get {
                return ResourceManager.GetString("Info_KM_M1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昆明仓覆盖地区M1.
        /// </summary>
        public static string Info_KM_M1RegionSalesQty {
            get {
                return ResourceManager.GetString("Info_KM_M1RegionSalesQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昆明M2.
        /// </summary>
        public static string Info_KM_M2 {
            get {
                return ResourceManager.GetString("Info_KM_M2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昆明M3.
        /// </summary>
        public static string Info_KM_M3 {
            get {
                return ResourceManager.GetString("Info_KM_M3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 京仓被订购数量.
        /// </summary>
        public static string Info_KM_OrderQty {
            get {
                return ResourceManager.GetString("Info_KM_OrderQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昆明采购单据数量.
        /// </summary>
        public static string Info_KM_PurchaseInQty {
            get {
                return ResourceManager.GetString("Info_KM_PurchaseInQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 采购价格.
        /// </summary>
        public static string Info_KM_PurchasePrice {
            get {
                return ResourceManager.GetString("Info_KM_PurchasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 采购数量.
        /// </summary>
        public static string Info_KM_PurchaseQty {
            get {
                return ResourceManager.GetString("Info_KM_PurchaseQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昆明采购信息设置.
        /// </summary>
        public static string Info_KM_SetPurchaseInfo {
            get {
                return ResourceManager.GetString("Info_KM_SetPurchaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昆明移仓信息设置.
        /// </summary>
        public static string Info_KM_SetShiftInfo {
            get {
                return ResourceManager.GetString("Info_KM_SetShiftInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移仓出库仓.
        /// </summary>
        public static string Info_KM_ShifOutStock {
            get {
                return ResourceManager.GetString("Info_KM_ShifOutStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移仓数量.
        /// </summary>
        public static string Info_KM_ShifQty {
            get {
                return ResourceManager.GetString("Info_KM_ShifQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昆明移仓在途数量.
        /// </summary>
        public static string Info_KM_ShiftInQty {
            get {
                return ResourceManager.GetString("Info_KM_ShiftInQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昆明仓建议备货数量.
        /// </summary>
        public static string Info_KM_SuggestQtyDisplay {
            get {
                return ResourceManager.GetString("Info_KM_SuggestQtyDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昆明虚库库存.
        /// </summary>
        public static string Info_KM_VirtualQty {
            get {
                return ResourceManager.GetString("Info_KM_VirtualQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昆明W1.
        /// </summary>
        public static string Info_KM_W1 {
            get {
                return ResourceManager.GetString("Info_KM_W1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昆明仓覆盖地区W1.
        /// </summary>
        public static string Info_KM_W1RegionSalesQty {
            get {
                return ResourceManager.GetString("Info_KM_W1RegionSalesQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昆明W2.
        /// </summary>
        public static string Info_KM_W2 {
            get {
                return ResourceManager.GetString("Info_KM_W2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昆明W3.
        /// </summary>
        public static string Info_KM_W3 {
            get {
                return ResourceManager.GetString("Info_KM_W3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昆明W4.
        /// </summary>
        public static string Info_KM_W4 {
            get {
                return ResourceManager.GetString("Info_KM_W4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生产商.
        /// </summary>
        public static string Info_ManufacturerName {
            get {
                return ResourceManager.GetString("Info_ManufacturerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总被订购库存.
        /// </summary>
        public static string Info_OrderQty {
            get {
                return ResourceManager.GetString("Info_OrderQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 采购价格备注.
        /// </summary>
        public static string Info_PO_Memo {
            get {
                return ResourceManager.GetString("Info_PO_Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同步采购价格.
        /// </summary>
        public static string Info_PurchasePrice {
            get {
                return ResourceManager.GetString("Info_PurchasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有仓采购单据数量.
        /// </summary>
        public static string Info_PurchaseQty {
            get {
                return ResourceManager.GetString("Info_PurchaseQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询结果.
        /// </summary>
        public static string Info_SearchResult {
            get {
                return ResourceManager.GetString("Info_SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本可用库存.
        /// </summary>
        public static string Info_SH_AvailableQty {
            get {
                return ResourceManager.GetString("Info_SH_AvailableQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本仓可销售天数.
        /// </summary>
        public static string Info_SH_AvailableSalesDays {
            get {
                return ResourceManager.GetString("Info_SH_AvailableSalesDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本仓覆盖区域日均销量.
        /// </summary>
        public static string Info_SH_AVGDailySales {
            get {
                return ResourceManager.GetString("Info_SH_AVGDailySales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本仓代销库存数量.
        /// </summary>
        public static string Info_SH_ConsignQty {
            get {
                return ResourceManager.GetString("Info_SH_ConsignQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本D1.
        /// </summary>
        public static string Info_SH_D1 {
            get {
                return ResourceManager.GetString("Info_SH_D1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本D2.
        /// </summary>
        public static string Info_SH_D2 {
            get {
                return ResourceManager.GetString("Info_SH_D2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本D3.
        /// </summary>
        public static string Info_SH_D3 {
            get {
                return ResourceManager.GetString("Info_SH_D3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本D4.
        /// </summary>
        public static string Info_SH_D4 {
            get {
                return ResourceManager.GetString("Info_SH_D4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本D5.
        /// </summary>
        public static string Info_SH_D5 {
            get {
                return ResourceManager.GetString("Info_SH_D5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本D6.
        /// </summary>
        public static string Info_SH_D6 {
            get {
                return ResourceManager.GetString("Info_SH_D6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本D7.
        /// </summary>
        public static string Info_SH_D7 {
            get {
                return ResourceManager.GetString("Info_SH_D7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本最后一次采购时间.
        /// </summary>
        public static string Info_SH_Lastintime {
            get {
                return ResourceManager.GetString("Info_SH_Lastintime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本最后一次采购价格.
        /// </summary>
        public static string Info_SH_LastPrice {
            get {
                return ResourceManager.GetString("Info_SH_LastPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本M1.
        /// </summary>
        public static string Info_SH_M1 {
            get {
                return ResourceManager.GetString("Info_SH_M1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本仓覆盖地区M1.
        /// </summary>
        public static string Info_SH_M1RegionSalesQty {
            get {
                return ResourceManager.GetString("Info_SH_M1RegionSalesQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本M2.
        /// </summary>
        public static string Info_SH_M2 {
            get {
                return ResourceManager.GetString("Info_SH_M2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本M3.
        /// </summary>
        public static string Info_SH_M3 {
            get {
                return ResourceManager.GetString("Info_SH_M3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本仓被订购数量.
        /// </summary>
        public static string Info_SH_OrderQty {
            get {
                return ResourceManager.GetString("Info_SH_OrderQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本采购单据数量.
        /// </summary>
        public static string Info_SH_PurchaseInQty {
            get {
                return ResourceManager.GetString("Info_SH_PurchaseInQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本采购价格.
        /// </summary>
        public static string Info_SH_PurchasePrice {
            get {
                return ResourceManager.GetString("Info_SH_PurchasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本采购信息设置.
        /// </summary>
        public static string Info_SH_SetPurchaseInfo {
            get {
                return ResourceManager.GetString("Info_SH_SetPurchaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本移仓在途数量.
        /// </summary>
        public static string Info_SH_ShiftInQty {
            get {
                return ResourceManager.GetString("Info_SH_ShiftInQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本仓建议备货数量.
        /// </summary>
        public static string Info_SH_SuggestQty {
            get {
                return ResourceManager.GetString("Info_SH_SuggestQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本虚库库存.
        /// </summary>
        public static string Info_SH_VirtualQty {
            get {
                return ResourceManager.GetString("Info_SH_VirtualQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本W1.
        /// </summary>
        public static string Info_SH_W1 {
            get {
                return ResourceManager.GetString("Info_SH_W1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本仓覆盖地区W1.
        /// </summary>
        public static string Info_SH_W1RegionSalesQty {
            get {
                return ResourceManager.GetString("Info_SH_W1RegionSalesQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本W2.
        /// </summary>
        public static string Info_SH_W2 {
            get {
                return ResourceManager.GetString("Info_SH_W2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本W3.
        /// </summary>
        public static string Info_SH_W3 {
            get {
                return ResourceManager.GetString("Info_SH_W3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本W4.
        /// </summary>
        public static string Info_SH_W4 {
            get {
                return ResourceManager.GetString("Info_SH_W4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建议备货总数.
        /// </summary>
        public static string Info_SuggestQtyAllDisplay {
            get {
                return ResourceManager.GetString("Info_SuggestQtyAllDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深圳可用库存.
        /// </summary>
        public static string Info_SZ_AvailableQty {
            get {
                return ResourceManager.GetString("Info_SZ_AvailableQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深圳仓可销售天数.
        /// </summary>
        public static string Info_SZ_AvailableSalesDays {
            get {
                return ResourceManager.GetString("Info_SZ_AvailableSalesDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可移库存.
        /// </summary>
        public static string Info_SZ_AvailableShifOutQty {
            get {
                return ResourceManager.GetString("Info_SZ_AvailableShifOutQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深圳仓覆盖区域日均销量.
        /// </summary>
        public static string Info_SZ_AVGDailySales {
            get {
                return ResourceManager.GetString("Info_SZ_AVGDailySales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深圳仓代销库存数量.
        /// </summary>
        public static string Info_SZ_ConsignQty {
            get {
                return ResourceManager.GetString("Info_SZ_ConsignQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深圳D1.
        /// </summary>
        public static string Info_SZ_D1 {
            get {
                return ResourceManager.GetString("Info_SZ_D1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深圳D2.
        /// </summary>
        public static string Info_SZ_D2 {
            get {
                return ResourceManager.GetString("Info_SZ_D2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深圳D3.
        /// </summary>
        public static string Info_SZ_D3 {
            get {
                return ResourceManager.GetString("Info_SZ_D3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深圳D4.
        /// </summary>
        public static string Info_SZ_D4 {
            get {
                return ResourceManager.GetString("Info_SZ_D4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深圳D5.
        /// </summary>
        public static string Info_SZ_D5 {
            get {
                return ResourceManager.GetString("Info_SZ_D5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深圳D6.
        /// </summary>
        public static string Info_SZ_D6 {
            get {
                return ResourceManager.GetString("Info_SZ_D6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深圳D7.
        /// </summary>
        public static string Info_SZ_D7 {
            get {
                return ResourceManager.GetString("Info_SZ_D7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否中转.
        /// </summary>
        public static string Info_SZ_IsNeedBuffer {
            get {
                return ResourceManager.GetString("Info_SZ_IsNeedBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深圳最后一次采购时间.
        /// </summary>
        public static string Info_SZ_Lastintime {
            get {
                return ResourceManager.GetString("Info_SZ_Lastintime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深圳最后一次采购价格.
        /// </summary>
        public static string Info_SZ_LastPrice {
            get {
                return ResourceManager.GetString("Info_SZ_LastPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深圳M1.
        /// </summary>
        public static string Info_SZ_M1 {
            get {
                return ResourceManager.GetString("Info_SZ_M1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深圳仓覆盖地区M1.
        /// </summary>
        public static string Info_SZ_M1RegionSalesQty {
            get {
                return ResourceManager.GetString("Info_SZ_M1RegionSalesQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深圳M2.
        /// </summary>
        public static string Info_SZ_M2 {
            get {
                return ResourceManager.GetString("Info_SZ_M2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深圳M3.
        /// </summary>
        public static string Info_SZ_M3 {
            get {
                return ResourceManager.GetString("Info_SZ_M3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 京仓被订购数量.
        /// </summary>
        public static string Info_SZ_OrderQty {
            get {
                return ResourceManager.GetString("Info_SZ_OrderQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深圳采购单据数量.
        /// </summary>
        public static string Info_SZ_PurchaseInQty {
            get {
                return ResourceManager.GetString("Info_SZ_PurchaseInQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 采购价格.
        /// </summary>
        public static string Info_SZ_PurchasePrice {
            get {
                return ResourceManager.GetString("Info_SZ_PurchasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 采购数量.
        /// </summary>
        public static string Info_SZ_PurchaseQty {
            get {
                return ResourceManager.GetString("Info_SZ_PurchaseQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深圳采购信息设置.
        /// </summary>
        public static string Info_SZ_SetPurchaseInfo {
            get {
                return ResourceManager.GetString("Info_SZ_SetPurchaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深圳移仓信息设置.
        /// </summary>
        public static string Info_SZ_SetShiftInfo {
            get {
                return ResourceManager.GetString("Info_SZ_SetShiftInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移仓出库仓.
        /// </summary>
        public static string Info_SZ_ShifOutStock {
            get {
                return ResourceManager.GetString("Info_SZ_ShifOutStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移仓数量.
        /// </summary>
        public static string Info_SZ_ShifQty {
            get {
                return ResourceManager.GetString("Info_SZ_ShifQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深圳移仓在途数量.
        /// </summary>
        public static string Info_SZ_ShiftInQty {
            get {
                return ResourceManager.GetString("Info_SZ_ShiftInQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深圳仓建议备货数量.
        /// </summary>
        public static string Info_SZ_SuggestQtyDisplay {
            get {
                return ResourceManager.GetString("Info_SZ_SuggestQtyDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深圳虚库库存.
        /// </summary>
        public static string Info_SZ_VirtualQty {
            get {
                return ResourceManager.GetString("Info_SZ_VirtualQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深圳W1.
        /// </summary>
        public static string Info_SZ_W1 {
            get {
                return ResourceManager.GetString("Info_SZ_W1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深圳仓覆盖地区W1.
        /// </summary>
        public static string Info_SZ_W1RegionSalesQty {
            get {
                return ResourceManager.GetString("Info_SZ_W1RegionSalesQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深圳W2.
        /// </summary>
        public static string Info_SZ_W2 {
            get {
                return ResourceManager.GetString("Info_SZ_W2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深圳W3.
        /// </summary>
        public static string Info_SZ_W3 {
            get {
                return ResourceManager.GetString("Info_SZ_W3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深圳W4.
        /// </summary>
        public static string Info_SZ_W4 {
            get {
                return ResourceManager.GetString("Info_SZ_W4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中转仓库存.
        /// </summary>
        public static string Info_TransferStockQty {
            get {
                return ResourceManager.GetString("Info_TransferStockQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成本.
        /// </summary>
        public static string Info_UnitCost {
            get {
                return ResourceManager.GetString("Info_UnitCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 滞销库存.
        /// </summary>
        public static string Info_UnmarketableQty {
            get {
                return ResourceManager.GetString("Info_UnmarketableQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正常采购价格.
        /// </summary>
        public static string Info_VirtualPrice {
            get {
                return ResourceManager.GetString("Info_VirtualPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 武汉可用库存.
        /// </summary>
        public static string Info_WH_AvailableQty {
            get {
                return ResourceManager.GetString("Info_WH_AvailableQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 武汉仓可销售天数.
        /// </summary>
        public static string Info_WH_AvailableSalesDay {
            get {
                return ResourceManager.GetString("Info_WH_AvailableSalesDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可移库存.
        /// </summary>
        public static string Info_WH_AvailableShifOutQty {
            get {
                return ResourceManager.GetString("Info_WH_AvailableShifOutQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 武汉仓覆盖区域日均销量.
        /// </summary>
        public static string Info_WH_AVGDailySales {
            get {
                return ResourceManager.GetString("Info_WH_AVGDailySales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 武汉仓代销库存数量.
        /// </summary>
        public static string Info_WH_ConsignQty {
            get {
                return ResourceManager.GetString("Info_WH_ConsignQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 武汉D1.
        /// </summary>
        public static string Info_WH_D1 {
            get {
                return ResourceManager.GetString("Info_WH_D1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 武汉D2.
        /// </summary>
        public static string Info_WH_D2 {
            get {
                return ResourceManager.GetString("Info_WH_D2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 武汉D3.
        /// </summary>
        public static string Info_WH_D3 {
            get {
                return ResourceManager.GetString("Info_WH_D3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 武汉D4.
        /// </summary>
        public static string Info_WH_D4 {
            get {
                return ResourceManager.GetString("Info_WH_D4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 武汉D5.
        /// </summary>
        public static string Info_WH_D5 {
            get {
                return ResourceManager.GetString("Info_WH_D5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 武汉D6.
        /// </summary>
        public static string Info_WH_D6 {
            get {
                return ResourceManager.GetString("Info_WH_D6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 武汉D7.
        /// </summary>
        public static string Info_WH_D7 {
            get {
                return ResourceManager.GetString("Info_WH_D7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否中转.
        /// </summary>
        public static string Info_WH_IsNeedBuffer {
            get {
                return ResourceManager.GetString("Info_WH_IsNeedBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 武汉最后一次采购时间.
        /// </summary>
        public static string Info_WH_Lastintime {
            get {
                return ResourceManager.GetString("Info_WH_Lastintime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 武汉最后一次采购价.
        /// </summary>
        public static string Info_WH_LastPrice {
            get {
                return ResourceManager.GetString("Info_WH_LastPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 武汉M1.
        /// </summary>
        public static string Info_WH_M1 {
            get {
                return ResourceManager.GetString("Info_WH_M1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 武汉仓覆盖地区M1.
        /// </summary>
        public static string Info_WH_M1RegionSalesQty {
            get {
                return ResourceManager.GetString("Info_WH_M1RegionSalesQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 武汉M2.
        /// </summary>
        public static string Info_WH_M2 {
            get {
                return ResourceManager.GetString("Info_WH_M2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 武汉M3.
        /// </summary>
        public static string Info_WH_M3 {
            get {
                return ResourceManager.GetString("Info_WH_M3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 武汉仓被订购数量.
        /// </summary>
        public static string Info_WH_OrderQty {
            get {
                return ResourceManager.GetString("Info_WH_OrderQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 武汉采购单据数量.
        /// </summary>
        public static string Info_WH_PurchaseInQty {
            get {
                return ResourceManager.GetString("Info_WH_PurchaseInQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 采购价格.
        /// </summary>
        public static string Info_WH_PurchasePrice {
            get {
                return ResourceManager.GetString("Info_WH_PurchasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 采购数量.
        /// </summary>
        public static string Info_WH_PurchaseQty {
            get {
                return ResourceManager.GetString("Info_WH_PurchaseQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 武汉采购信息设置.
        /// </summary>
        public static string Info_WH_SetPurchaseInfo {
            get {
                return ResourceManager.GetString("Info_WH_SetPurchaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 武汉移仓信息设置.
        /// </summary>
        public static string Info_WH_SetShiftInfo {
            get {
                return ResourceManager.GetString("Info_WH_SetShiftInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移仓出库仓.
        /// </summary>
        public static string Info_WH_ShifOutStock {
            get {
                return ResourceManager.GetString("Info_WH_ShifOutStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移仓数量.
        /// </summary>
        public static string Info_WH_ShifQty {
            get {
                return ResourceManager.GetString("Info_WH_ShifQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 武汉移仓在途数量.
        /// </summary>
        public static string Info_WH_ShiftInQty {
            get {
                return ResourceManager.GetString("Info_WH_ShiftInQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 武汉仓建议备货数量.
        /// </summary>
        public static string Info_WH_SuggestQtyDisplay {
            get {
                return ResourceManager.GetString("Info_WH_SuggestQtyDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 武汉虚库库存.
        /// </summary>
        public static string Info_WH_VirtualQty {
            get {
                return ResourceManager.GetString("Info_WH_VirtualQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 武汉W1.
        /// </summary>
        public static string Info_WH_W1 {
            get {
                return ResourceManager.GetString("Info_WH_W1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 武汉仓覆盖地区W1.
        /// </summary>
        public static string Info_WH_W1RegionSalesQty {
            get {
                return ResourceManager.GetString("Info_WH_W1RegionSalesQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 武汉W2.
        /// </summary>
        public static string Info_WH_W2 {
            get {
                return ResourceManager.GetString("Info_WH_W2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 武汉W3.
        /// </summary>
        public static string Info_WH_W3 {
            get {
                return ResourceManager.GetString("Info_WH_W3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 武汉W4.
        /// </summary>
        public static string Info_WH_W4 {
            get {
                return ResourceManager.GetString("Info_WH_W4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 整网可销售天数.
        /// </summary>
        public static string LinkButton_AllStockAvailableSalesDays {
            get {
                return ResourceManager.GetString("LinkButton_AllStockAvailableSalesDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 整网日均销量.
        /// </summary>
        public static string LinkButton_AllStockAVGDailySales {
            get {
                return ResourceManager.GetString("LinkButton_AllStockAVGDailySales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item#.
        /// </summary>
        public static string LinkButton_ItemCode {
            get {
                return ResourceManager.GetString("LinkButton_ItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品名称.
        /// </summary>
        public static string LinkButton_ItemName {
            get {
                return ResourceManager.GetString("LinkButton_ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有仓采购单据数量.
        /// </summary>
        public static string LinkButton_PurchaseQty {
            get {
                return ResourceManager.GetString("LinkButton_PurchaseQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总虚库库存.
        /// </summary>
        public static string LinkButton_VirtualQty {
            get {
                return ResourceManager.GetString("LinkButton_VirtualQty", resourceCulture);
            }
        }
    }
}
