//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECCentral.Portal.UI.Inventory.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResVirtualRequestMemoQuery {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ResVirtualRequestMemoQuery() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ECCentral.Portal.UI.Inventory.Resources.ResVirtualRequestMemoQuery", typeof(ResVirtualRequestMemoQuery).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询.
        /// </summary>
        public static string Button_Search {
            get {
                return ResourceManager.GetString("Button_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询条件.
        /// </summary>
        public static string Expander_QueryBuilder {
            get {
                return ResourceManager.GetString("Expander_QueryBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 审核虚库变更.
        /// </summary>
        public static string Expander_QueryResult {
            get {
                return ResourceManager.GetString("Expander_QueryResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 虚库变更历史.
        /// </summary>
        public static string Expander_VirtualRequestMemoInfo {
            get {
                return ResourceManager.GetString("Expander_VirtualRequestMemoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 备注.
        /// </summary>
        public static string Grid_ActionMemo {
            get {
                return ResourceManager.GetString("Grid_ActionMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 存储变化量.
        /// </summary>
        public static string Grid_AdjustVirtualQty {
            get {
                return ResourceManager.GetString("Grid_AdjustVirtualQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置时间.
        /// </summary>
        public static string Grid_OperationDate {
            get {
                return ResourceManager.GetString("Grid_OperationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户.
        /// </summary>
        public static string Grid_OperationUser {
            get {
                return ResourceManager.GetString("Grid_OperationUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品编号.
        /// </summary>
        public static string Grid_ProductID {
            get {
                return ResourceManager.GetString("Grid_ProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品名称.
        /// </summary>
        public static string Grid_ProductName {
            get {
                return ResourceManager.GetString("Grid_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 虚库类型.
        /// </summary>
        public static string Grid_VirtualType {
            get {
                return ResourceManager.GetString("Grid_VirtualType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户:.
        /// </summary>
        public static string Label_CreateUser {
            get {
                return ResourceManager.GetString("Label_CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品编号:.
        /// </summary>
        public static string Label_ProductID {
            get {
                return ResourceManager.GetString("Label_ProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 备注:.
        /// </summary>
        public static string Label_RequestActionMemo {
            get {
                return ResourceManager.GetString("Label_RequestActionMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 申请时间:.
        /// </summary>
        public static string Label_RequestCreateDate {
            get {
                return ResourceManager.GetString("Label_RequestCreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 虚库状态:.
        /// </summary>
        public static string Label_RequestStatus {
            get {
                return ResourceManager.GetString("Label_RequestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 渠道仓库:.
        /// </summary>
        public static string Label_Stock {
            get {
                return ResourceManager.GetString("Label_Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 虚库类型:.
        /// </summary>
        public static string Label_VirtualType {
            get {
                return ResourceManager.GetString("Label_VirtualType", resourceCulture);
            }
        }
    }
}
