//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECCentral.Portal.UI.IM.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResProductCreate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ResProductCreate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ECCentral.Portal.UI.IM.Resources.ResProductCreate", typeof(ResProductCreate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 代收代付.
        /// </summary>
        public static string AgentBusiness {
            get {
                return ResourceManager.GetString("AgentBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 代收.
        /// </summary>
        public static string Collection {
            get {
                return ResourceManager.GetString("Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 代销.
        /// </summary>
        public static string Consignment {
            get {
                return ResourceManager.GetString("Consignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 经销.
        /// </summary>
        public static string Distribute {
            get {
                return ResourceManager.GetString("Distribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正常采购价必须为货币！.
        /// </summary>
        public static string Error_VirtualPriceMessage {
            get {
                return ResourceManager.GetString("Error_VirtualPriceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品展示信息.
        /// </summary>
        public static string Expander_Product_DisplayInfo {
            get {
                return ResourceManager.GetString("Expander_Product_DisplayInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品分组.
        /// </summary>
        public static string Expander_Product_Group {
            get {
                return ResourceManager.GetString("Expander_Product_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品规格描述信息.
        /// </summary>
        public static string Expander_Product_SpecificationInfo {
            get {
                return ResourceManager.GetString("Expander_Product_SpecificationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品编号.
        /// </summary>
        public static string Grid_ProductID {
            get {
                return ResourceManager.GetString("Grid_ProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关键字.
        /// </summary>
        public static string Grid_ProductKeyword {
            get {
                return ResourceManager.GetString("Grid_ProductKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品型号.
        /// </summary>
        public static string Grid_ProductModelNo {
            get {
                return ResourceManager.GetString("Grid_ProductModelNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品标题.
        /// </summary>
        public static string Grid_ProductTitle {
            get {
                return ResourceManager.GetString("Grid_ProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPC Code.
        /// </summary>
        public static string Grid_ProductUPCCode {
            get {
                return ResourceManager.GetString("Grid_ProductUPCCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品正常采购价格.
        /// </summary>
        public static string Grid_ProductVirtualPrice {
            get {
                return ResourceManager.GetString("Grid_ProductVirtualPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 团购.
        /// </summary>
        public static string GroupBuying {
            get {
                return ResourceManager.GetString("GroupBuying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存成功!.
        /// </summary>
        public static string Info_SaveSuccessfully {
            get {
                return ResourceManager.GetString("Info_SaveSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否拍照.
        /// </summary>
        public static string IsTakePictures {
            get {
                return ResourceManager.GetString("IsTakePictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BM Code：.
        /// </summary>
        public static string Label_BMCode {
            get {
                return ResourceManager.GetString("Label_BMCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 品牌:.
        /// </summary>
        public static string Label_Brand {
            get {
                return ResourceManager.GetString("Label_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类别:.
        /// </summary>
        public static string Label_Category {
            get {
                return ResourceManager.GetString("Label_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 代销属性:.
        /// </summary>
        public static string Label_ConsignFlag {
            get {
                return ResourceManager.GetString("Label_ConsignFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 产地：.
        /// </summary>
        public static string Label_Country {
            get {
                return ResourceManager.GetString("Label_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否显示图片.
        /// </summary>
        public static string Label_DisplayPictureView_Chb {
            get {
                return ResourceManager.GetString("Label_DisplayPictureView_Chb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分组属性1:.
        /// </summary>
        public static string Label_GroupProperty1 {
            get {
                return ResourceManager.GetString("Label_GroupProperty1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分组属性2:.
        /// </summary>
        public static string Label_GroupProperty2 {
            get {
                return ResourceManager.GetString("Label_GroupProperty2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关键字：.
        /// </summary>
        public static string Label_KeyWord {
            get {
                return ResourceManager.GetString("Label_KeyWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生产商:.
        /// </summary>
        public static string Label_Manufacturer {
            get {
                return ResourceManager.GetString("Label_Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否聚合.
        /// </summary>
        public static string Label_PolymericView_Chb {
            get {
                return ResourceManager.GetString("Label_PolymericView_Chb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM:.
        /// </summary>
        public static string Label_ProductManager {
            get {
                return ResourceManager.GetString("Label_ProductManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品型号:.
        /// </summary>
        public static string Label_ProductModelNo {
            get {
                return ResourceManager.GetString("Label_ProductModelNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品标题:.
        /// </summary>
        public static string Label_ProductTitle {
            get {
                return ResourceManager.GetString("Label_ProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品类型:.
        /// </summary>
        public static string Label_ProductType {
            get {
                return ResourceManager.GetString("Label_ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否拍照:.
        /// </summary>
        public static string Label_TakePictureFlag {
            get {
                return ResourceManager.GetString("Label_TakePictureFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPC Code：.
        /// </summary>
        public static string Label_UPCCode {
            get {
                return ResourceManager.GetString("Label_UPCCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品正常采购价格：.
        /// </summary>
        public static string Label_VirtualPrice {
            get {
                return ResourceManager.GetString("Label_VirtualPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入整数！.
        /// </summary>
        public static string Msg_IsInteger {
            get {
                return ResourceManager.GetString("Msg_IsInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正常品.
        /// </summary>
        public static string NormalGoods {
            get {
                return ResourceManager.GetString("NormalGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 产地不能为空！.
        /// </summary>
        public static string ProductCreate_CountryCodeEmpty {
            get {
                return ResourceManager.GetString("ProductCreate_CountryCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品型号不能为空！.
        /// </summary>
        public static string ProductCreate_ProductModelEmpty {
            get {
                return ResourceManager.GetString("ProductCreate_ProductModelEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品正常采购价格不能为空！.
        /// </summary>
        public static string ProductCreate_ProductPriceVirtualPriceEmpty {
            get {
                return ResourceManager.GetString("ProductCreate_ProductPriceVirtualPriceEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品正常采购价格必须为货币！.
        /// </summary>
        public static string ProductCreate_ProductPriceVirtualPriceInvalid {
            get {
                return ResourceManager.GetString("ProductCreate_ProductPriceVirtualPriceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品标题不能为空！.
        /// </summary>
        public static string ProductCreate_ProductTitleEmpty {
            get {
                return ResourceManager.GetString("ProductCreate_ProductTitleEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 二手品.
        /// </summary>
        public static string Secondhand {
            get {
                return ResourceManager.GetString("Secondhand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品正常采购价格必须输入大于等于0的整数！.
        /// </summary>
        public static string VirtualPriceInvalid {
            get {
                return ResourceManager.GetString("VirtualPriceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 虚拟商品.
        /// </summary>
        public static string VirtualProduct {
            get {
                return ResourceManager.GetString("VirtualProduct", resourceCulture);
            }
        }
    }
}
