//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECCentral.Portal.UI.IM.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResProductChannelManagementDetail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ResProductChannelManagementDetail() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ECCentral.Portal.UI.IM.Resources.ResProductChannelManagementDetail", typeof(ResProductChannelManagementDetail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string Btn_Cancel {
            get {
                return ResourceManager.GetString("Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 价格信息：.
        /// </summary>
        public static string Expander_PriceInfo {
            get {
                return ResourceManager.GetString("Expander_PriceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 库存信息：.
        /// </summary>
        public static string Expander_StockInfo {
            get {
                return ResourceManager.GetString("Expander_StockInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 渠道名称：.
        /// </summary>
        public static string Label_ChannelName {
            get {
                return ResourceManager.GetString("Label_ChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 渠道价格比例：.
        /// </summary>
        public static string Label_ChannelPricePercent {
            get {
                return ResourceManager.GetString("Label_ChannelPricePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可销售库存：.
        /// </summary>
        public static string Label_ChannelSellCount {
            get {
                return ResourceManager.GetString("Label_ChannelSellCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一致库存比例：.
        /// </summary>
        public static string Label_InventoryPercent {
            get {
                return ResourceManager.GetString("Label_InventoryPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否指定库存：.
        /// </summary>
        public static string Label_IsAppointInventory {
            get {
                return ResourceManager.GetString("Label_IsAppointInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否同步促销：.
        /// </summary>
        public static string Label_IsUsePromotionPrice {
            get {
                return ResourceManager.GetString("Label_IsUsePromotionPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最大分仓数：.
        /// </summary>
        public static string Label_MaxStockQty {
            get {
                return ResourceManager.GetString("Label_MaxStockQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 库存数量：.
        /// </summary>
        public static string Label_OnlineQty {
            get {
                return ResourceManager.GetString("Label_OnlineQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品ID：.
        /// </summary>
        public static string Label_ProductID {
            get {
                return ResourceManager.GetString("Label_ProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品名称：.
        /// </summary>
        public static string Label_ProductName {
            get {
                return ResourceManager.GetString("Label_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安全库存：.
        /// </summary>
        public static string Label_SafeInventoryQty {
            get {
                return ResourceManager.GetString("Label_SafeInventoryQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状态：.
        /// </summary>
        public static string Label_Status {
            get {
                return ResourceManager.GetString("Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 渠道商品ID：.
        /// </summary>
        public static string Label_SynProductID {
            get {
                return ResourceManager.GetString("Label_SynProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 淘宝SKU码；.
        /// </summary>
        public static string Label_TaoBaoSku {
            get {
                return ResourceManager.GetString("Label_TaoBaoSku", resourceCulture);
            }
        }
    }
}
