//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECCentral.Portal.UI.IM.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResProductGroupQuery {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ResProductGroupQuery()
        {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ECCentral.Portal.UI.IM.Resources.ResProductGroupQuery", typeof(ResProductGroupQuery).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 批量无效.
        /// </summary>
        public static string Button_BatchInvalid {
            get {
                return ResourceManager.GetString("Button_BatchInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 批量有效.
        /// </summary>
        public static string Button_BatchValid {
            get {
                return ResourceManager.GetString("Button_BatchValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建.
        /// </summary>
        public static string Button_New {
            get {
                return ResourceManager.GetString("Button_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询.
        /// </summary>
        public static string Button_Search {
            get {
                return ResourceManager.GetString("Button_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询条件.
        /// </summary>
        public static string Expander_QueryBuilder {
            get {
                return ResourceManager.GetString("Expander_QueryBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询结果.
        /// </summary>
        public static string Expander_QueryResult {
            get {
                return ResourceManager.GetString("Expander_QueryResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 品牌名称.
        /// </summary>
        public static string Grid_BrandName {
            get {
                return ResourceManager.GetString("Grid_BrandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类别名称.
        /// </summary>
        public static string Grid_C3Name {
            get {
                return ResourceManager.GetString("Grid_C3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建时间.
        /// </summary>
        public static string Grid_CreateDate {
            get {
                return ResourceManager.GetString("Grid_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建人.
        /// </summary>
        public static string Grid_CreateUser {
            get {
                return ResourceManager.GetString("Grid_CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新时间.
        /// </summary>
        public static string Grid_EditDate {
            get {
                return ResourceManager.GetString("Grid_EditDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新人.
        /// </summary>
        public static string Grid_EditUser {
            get {
                return ResourceManager.GetString("Grid_EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 组名称.
        /// </summary>
        public static string Grid_GroupName {
            get {
                return ResourceManager.GetString("Grid_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 组状态.
        /// </summary>
        public static string Grid_GroupStatus {
            get {
                return ResourceManager.GetString("Grid_GroupStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统编号.
        /// </summary>
        public static string Grid_GroupSysNo {
            get {
                return ResourceManager.GetString("Grid_GroupSysNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 多语言设置.
        /// </summary>
        public static string Grid_MultiLanguageEdit {
            get {
                return ResourceManager.GetString("Grid_MultiLanguageEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作.
        /// </summary>
        public static string Grid_Operation {
            get {
                return ResourceManager.GetString("Grid_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑.
        /// </summary>
        public static string Grid_OperationEdit {
            get {
                return ResourceManager.GetString("Grid_OperationEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 组型号.
        /// </summary>
        public static string Grid_ProductModel {
            get {
                return ResourceManager.GetString("Grid_ProductModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 品牌名称：.
        /// </summary>
        public static string Label_BrandName {
            get {
                return ResourceManager.GetString("Label_BrandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类别:.
        /// </summary>
        public static string Label_Category {
            get {
                return ResourceManager.GetString("Label_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建时间:.
        /// </summary>
        public static string Label_CreateDate {
            get {
                return ResourceManager.GetString("Label_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新时间:.
        /// </summary>
        public static string Label_EditDate {
            get {
                return ResourceManager.GetString("Label_EditDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 组名称:.
        /// </summary>
        public static string Label_ProductGroupName {
            get {
                return ResourceManager.GetString("Label_ProductGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 组状态:.
        /// </summary>
        public static string Label_ProductGroupStatus {
            get {
                return ResourceManager.GetString("Label_ProductGroupStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品ID:.
        /// </summary>
        public static string Label_ProductID {
            get {
                return ResourceManager.GetString("Label_ProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM:.
        /// </summary>
        public static string Label_ProductManager {
            get {
                return ResourceManager.GetString("Label_ProductManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品名称:.
        /// </summary>
        public static string Label_ProductName {
            get {
                return ResourceManager.GetString("Label_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品状态:.
        /// </summary>
        public static string Label_ProductStatus {
            get {
                return ResourceManager.GetString("Label_ProductStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择ProductGroup后操作！.
        /// </summary>
        public static string Msg_OnSelectProductGroup {
            get {
                return ResourceManager.GetString("Msg_OnSelectProductGroup", resourceCulture);
            }
        }
    }
}
