using System;
using System.Net;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Shapes;
using System.Collections.Generic;

namespace Newegg.Oversea.Silverlight.Controls.Data
{   
    public class ColorsHelper
    {
        private List<ColorDescription> PredefinedColors { get; set; }
       
        public ColorsHelper()
        {
            List<ColorDescription> list = new List<ColorDescription>();
            ColorDescription item = new ColorDescription();
            item.ColorName = "Aliceblue";
            item.ColorCode = 0xfff0f8ff;
            list.Add(item);
            ColorDescription color2 = new ColorDescription();
            color2.ColorName = "AntiqueWhite";
            color2.ColorCode = 0xfffaebd7;
            list.Add(color2);
            ColorDescription color3 = new ColorDescription();
            color3.ColorName = "Aqua";
            color3.ColorCode = 0xff00ffff;
            list.Add(color3);
            ColorDescription color4 = new ColorDescription();
            color4.ColorName = "Aquamarine";
            color4.ColorCode = 0xff7fffd4;
            list.Add(color4);
            ColorDescription color5 = new ColorDescription();
            color5.ColorName = "Azure";
            color5.ColorCode = 0xfff0ffff;
            list.Add(color5);
            ColorDescription color6 = new ColorDescription();
            color6.ColorName = "Beige";
            color6.ColorCode = 0xfff5f5dc;
            list.Add(color6);
            ColorDescription color7 = new ColorDescription();
            color7.ColorName = "Bisque";
            color7.ColorCode = 0xffffe4c4;
            list.Add(color7);
            ColorDescription color8 = new ColorDescription();
            color8.ColorName = "Black";
            color8.ColorCode = 0xff000000;
            list.Add(color8);
            ColorDescription color9 = new ColorDescription();
            color9.ColorName = "BlanchedAlmond";
            color9.ColorCode = 0xffffebcd;
            list.Add(color9);
            ColorDescription color10 = new ColorDescription();
            color10.ColorName = "Blue";
            color10.ColorCode = 0xff0000ff;
            list.Add(color10);
            ColorDescription color11 = new ColorDescription();
            color11.ColorName = "BlueViolet";
            color11.ColorCode = 0xff8a2be2;
            list.Add(color11);
            ColorDescription color12 = new ColorDescription();
            color12.ColorName = "Brown";
            color12.ColorCode = 0xffa52a2a;
            list.Add(color12);
            ColorDescription color13 = new ColorDescription();
            color13.ColorName = "BurlyWood";
            color13.ColorCode = 0xffdeb887;
            list.Add(color13);
            ColorDescription color14 = new ColorDescription();
            color14.ColorName = "CadetBlue";
            color14.ColorCode = 0xff5f9ea0;
            list.Add(color14);
            ColorDescription color15 = new ColorDescription();
            color15.ColorName = "Chartreuse";
            color15.ColorCode = 0xff7fff00;
            list.Add(color15);
            ColorDescription color16 = new ColorDescription();
            color16.ColorName = "Chocolate";
            color16.ColorCode = 0xffd2691e;
            list.Add(color16);
            ColorDescription color17 = new ColorDescription();
            color17.ColorName = "Coral";
            color17.ColorCode = 0xffff7f50;
            list.Add(color17);
            ColorDescription color18 = new ColorDescription();
            color18.ColorName = "CornflowerBlue";
            color18.ColorCode = 0xff6495ed;
            list.Add(color18);
            ColorDescription color19 = new ColorDescription();
            color19.ColorName = "Cornsilk";
            color19.ColorCode = 0xfffff8dc;
            list.Add(color19);
            ColorDescription color20 = new ColorDescription();
            color20.ColorName = "Crimson";
            color20.ColorCode = 0xffdc143c;
            list.Add(color20);
            ColorDescription color21 = new ColorDescription();
            color21.ColorName = "Cyan";
            color21.ColorCode = 0xff00ffff;
            list.Add(color21);
            ColorDescription color22 = new ColorDescription();
            color22.ColorName = "DarkBlue";
            color22.ColorCode = 0xff00008b;
            list.Add(color22);
            ColorDescription color23 = new ColorDescription();
            color23.ColorName = "DarkCyan";
            color23.ColorCode = 0xff008b8b;
            list.Add(color23);
            ColorDescription color24 = new ColorDescription();
            color24.ColorName = "DarkGoldenrod";
            color24.ColorCode = 0xffb8860b;
            list.Add(color24);
            ColorDescription color25 = new ColorDescription();
            color25.ColorName = "DarkGray";
            color25.ColorCode = 0xffa9a9a9;
            list.Add(color25);
            ColorDescription color26 = new ColorDescription();
            color26.ColorName = "DarkGreen";
            color26.ColorCode = 0xff006400;
            list.Add(color26);
            ColorDescription color27 = new ColorDescription();
            color27.ColorName = "DarkKhaki";
            color27.ColorCode = 0xffbdb76b;
            list.Add(color27);
            ColorDescription color28 = new ColorDescription();
            color28.ColorName = "DarkMagenta";
            color28.ColorCode = 0xff8b008b;
            list.Add(color28);
            ColorDescription color29 = new ColorDescription();
            color29.ColorName = "DarkOliveGreen";
            color29.ColorCode = 0xff556b2f;
            list.Add(color29);
            ColorDescription color30 = new ColorDescription();
            color30.ColorName = "DarkOrange";
            color30.ColorCode = 0xffff8c00;
            list.Add(color30);
            ColorDescription color31 = new ColorDescription();
            color31.ColorName = "DarkOrchid";
            color31.ColorCode = 0xff9932cc;
            list.Add(color31);
            ColorDescription color32 = new ColorDescription();
            color32.ColorName = "DarkRed";
            color32.ColorCode = 0xff8b0000;
            list.Add(color32);
            ColorDescription color33 = new ColorDescription();
            color33.ColorName = "DarkSalmon";
            color33.ColorCode = 0xffe9967a;
            list.Add(color33);
            ColorDescription color34 = new ColorDescription();
            color34.ColorName = "DarkSeaGreen";
            color34.ColorCode = 0xff8fbc8f;
            list.Add(color34);
            ColorDescription color35 = new ColorDescription();
            color35.ColorName = "DarkSlateBlue";
            color35.ColorCode = 0xff483d8b;
            list.Add(color35);
            ColorDescription color36 = new ColorDescription();
            color36.ColorName = "DarkSlateGray";
            color36.ColorCode = 0xff2f4f4f;
            list.Add(color36);
            ColorDescription color37 = new ColorDescription();
            color37.ColorName = "DarkTurquoise";
            color37.ColorCode = 0xff00ced1;
            list.Add(color37);
            ColorDescription color38 = new ColorDescription();
            color38.ColorName = "DarkViolet";
            color38.ColorCode = 0xff9400d3;
            list.Add(color38);
            ColorDescription color39 = new ColorDescription();
            color39.ColorName = "DeepPink";
            color39.ColorCode = 0xffff1493;
            list.Add(color39);
            ColorDescription color40 = new ColorDescription();
            color40.ColorName = "DeepSkyBlue";
            color40.ColorCode = 0xff00bfff;
            list.Add(color40);
            ColorDescription color41 = new ColorDescription();
            color41.ColorName = "DimGray";
            color41.ColorCode = 0xff696969;
            list.Add(color41);
            ColorDescription color42 = new ColorDescription();
            color42.ColorName = "DodgerBlue";
            color42.ColorCode = 0xff1e90ff;
            list.Add(color42);
            ColorDescription color43 = new ColorDescription();
            color43.ColorName = "Firebrick";
            color43.ColorCode = 0xffb22222;
            list.Add(color43);
            ColorDescription color44 = new ColorDescription();
            color44.ColorName = "FloralWhite";
            color44.ColorCode = 0xfffffaf0;
            list.Add(color44);
            ColorDescription color45 = new ColorDescription();
            color45.ColorName = "ForestGreen";
            color45.ColorCode = 0xff228b22;
            list.Add(color45);
            ColorDescription color46 = new ColorDescription();
            color46.ColorName = "Fuchsia";
            color46.ColorCode = 0xffff00ff;
            list.Add(color46);
            ColorDescription color47 = new ColorDescription();
            color47.ColorName = "Gainsboro";
            color47.ColorCode = 0xffdcdcdc;
            list.Add(color47);
            ColorDescription color48 = new ColorDescription();
            color48.ColorName = "GhostWhite";
            color48.ColorCode = 0xfff8f8ff;
            list.Add(color48);
            ColorDescription color49 = new ColorDescription();
            color49.ColorName = "Gold";
            color49.ColorCode = 0xffffd700;
            list.Add(color49);
            ColorDescription color50 = new ColorDescription();
            color50.ColorName = "Goldenrod";
            color50.ColorCode = 0xffdaa520;
            list.Add(color50);
            ColorDescription color51 = new ColorDescription();
            color51.ColorName = "Gray";
            color51.ColorCode = 0xff808080;
            list.Add(color51);
            ColorDescription color52 = new ColorDescription();
            color52.ColorName = "Green";
            color52.ColorCode = 0xff008000;
            list.Add(color52);
            ColorDescription color53 = new ColorDescription();
            color53.ColorName = "GreenYellow";
            color53.ColorCode = 0xffadff2f;
            list.Add(color53);
            ColorDescription color54 = new ColorDescription();
            color54.ColorName = "Honeydew";
            color54.ColorCode = 0xfff0fff0;
            list.Add(color54);
            ColorDescription color55 = new ColorDescription();
            color55.ColorName = "HotPink";
            color55.ColorCode = 0xffff69b4;
            list.Add(color55);
            ColorDescription color56 = new ColorDescription();
            color56.ColorName = "IndianRed";
            color56.ColorCode = 0xffcd5c5c;
            list.Add(color56);
            ColorDescription color57 = new ColorDescription();
            color57.ColorName = "Indigo";
            color57.ColorCode = 0xff4b0082;
            list.Add(color57);
            ColorDescription color58 = new ColorDescription();
            color58.ColorName = "Ivory";
            color58.ColorCode = 0xfffffff0;
            list.Add(color58);
            ColorDescription color59 = new ColorDescription();
            color59.ColorName = "Khaki";
            color59.ColorCode = 0xfff0e68c;
            list.Add(color59);
            ColorDescription color60 = new ColorDescription();
            color60.ColorName = "Lavender";
            color60.ColorCode = 0xffe6e6fa;
            list.Add(color60);
            ColorDescription color61 = new ColorDescription();
            color61.ColorName = "LavenderBlush";
            color61.ColorCode = 0xfffff0f5;
            list.Add(color61);
            ColorDescription color62 = new ColorDescription();
            color62.ColorName = "LawnGreen";
            color62.ColorCode = 0xff7cfc00;
            list.Add(color62);
            ColorDescription color63 = new ColorDescription();
            color63.ColorName = "LemonChiffon";
            color63.ColorCode = 0xfffffacd;
            list.Add(color63);
            ColorDescription color64 = new ColorDescription();
            color64.ColorName = "LightBlue";
            color64.ColorCode = 0xffadd8e6;
            list.Add(color64);
            ColorDescription color65 = new ColorDescription();
            color65.ColorName = "LightCoral";
            color65.ColorCode = 0xfff08080;
            list.Add(color65);
            ColorDescription color66 = new ColorDescription();
            color66.ColorName = "LightCyan";
            color66.ColorCode = 0xffe0ffff;
            list.Add(color66);
            ColorDescription color67 = new ColorDescription();
            color67.ColorName = "LightGoldenrodYellow";
            color67.ColorCode = 0xfffafad2;
            list.Add(color67);
            ColorDescription color68 = new ColorDescription();
            color68.ColorName = "LightGray";
            color68.ColorCode = 0xffd3d3d3;
            list.Add(color68);
            ColorDescription color69 = new ColorDescription();
            color69.ColorName = "LightGreen";
            color69.ColorCode = 0xff90ee90;
            list.Add(color69);
            ColorDescription color70 = new ColorDescription();
            color70.ColorName = "LightPink";
            color70.ColorCode = 0xffffb6c1;
            list.Add(color70);
            ColorDescription color71 = new ColorDescription();
            color71.ColorName = "LightSalmon";
            color71.ColorCode = 0xffffa07a;
            list.Add(color71);
            ColorDescription color72 = new ColorDescription();
            color72.ColorName = "LightSeaGreen";
            color72.ColorCode = 0xff20b2aa;
            list.Add(color72);
            ColorDescription color73 = new ColorDescription();
            color73.ColorName = "LightSkyBlue";
            color73.ColorCode = 0xff87cefa;
            list.Add(color73);
            ColorDescription color74 = new ColorDescription();
            color74.ColorName = "LightSlateGray";
            color74.ColorCode = 0xff778899;
            list.Add(color74);
            ColorDescription color75 = new ColorDescription();
            color75.ColorName = "LightSteelBlue";
            color75.ColorCode = 0xffb0c4de;
            list.Add(color75);
            ColorDescription color76 = new ColorDescription();
            color76.ColorName = "LightYellow";
            color76.ColorCode = 0xffffffe0;
            list.Add(color76);
            ColorDescription color77 = new ColorDescription();
            color77.ColorName = "Lime";
            color77.ColorCode = 0xff00ff00;
            list.Add(color77);
            ColorDescription color78 = new ColorDescription();
            color78.ColorName = "LimeGreen";
            color78.ColorCode = 0xff32cd32;
            list.Add(color78);
            ColorDescription color79 = new ColorDescription();
            color79.ColorName = "Linen";
            color79.ColorCode = 0xfffaf0e6;
            list.Add(color79);
            ColorDescription color80 = new ColorDescription();
            color80.ColorName = "Magenta";
            color80.ColorCode = 0xffff00ff;
            list.Add(color80);
            ColorDescription color81 = new ColorDescription();
            color81.ColorName = "Maroon";
            color81.ColorCode = 0xff800000;
            list.Add(color81);
            ColorDescription color82 = new ColorDescription();
            color82.ColorName = "MediumAquamarine";
            color82.ColorCode = 0xff66cdaa;
            list.Add(color82);
            ColorDescription color83 = new ColorDescription();
            color83.ColorName = "MediumBlue";
            color83.ColorCode = 0xff0000cd;
            list.Add(color83);
            ColorDescription color84 = new ColorDescription();
            color84.ColorName = "MediumOrchid";
            color84.ColorCode = 0xffba55d3;
            list.Add(color84);
            ColorDescription color85 = new ColorDescription();
            color85.ColorName = "MediumPurple";
            color85.ColorCode = 0xff9370db;
            list.Add(color85);
            ColorDescription color86 = new ColorDescription();
            color86.ColorName = "MediumSeaGreen";
            color86.ColorCode = 0xff3cb371;
            list.Add(color86);
            ColorDescription color87 = new ColorDescription();
            color87.ColorName = "MediumSlateBlue";
            color87.ColorCode = 0xff7b68ee;
            list.Add(color87);
            ColorDescription color88 = new ColorDescription();
            color88.ColorName = "MediumSpringGreen";
            color88.ColorCode = 0xff00fa9a;
            list.Add(color88);
            ColorDescription color89 = new ColorDescription();
            color89.ColorName = "MediumTurquoise";
            color89.ColorCode = 0xff48d1cc;
            list.Add(color89);
            ColorDescription color90 = new ColorDescription();
            color90.ColorName = "MediumVioletRed";
            color90.ColorCode = 0xffc71585;
            list.Add(color90);
            ColorDescription color91 = new ColorDescription();
            color91.ColorName = "MidnightBlue";
            color91.ColorCode = 0xff191970;
            list.Add(color91);
            ColorDescription color92 = new ColorDescription();
            color92.ColorName = "MintCream";
            color92.ColorCode = 0xfff5fffa;
            list.Add(color92);
            ColorDescription color93 = new ColorDescription();
            color93.ColorName = "MistyRose";
            color93.ColorCode = 0xffffe4e1;
            list.Add(color93);
            ColorDescription color94 = new ColorDescription();
            color94.ColorName = "Moccasin";
            color94.ColorCode = 0xffffe4b5;
            list.Add(color94);
            ColorDescription color95 = new ColorDescription();
            color95.ColorName = "NavajoWhite";
            color95.ColorCode = 0xffffdead;
            list.Add(color95);
            ColorDescription color96 = new ColorDescription();
            color96.ColorName = "Navy";
            color96.ColorCode = 0xff000080;
            list.Add(color96);
            ColorDescription color97 = new ColorDescription();
            color97.ColorName = "OldLace";
            color97.ColorCode = 0xfffdf5e6;
            list.Add(color97);
            ColorDescription color98 = new ColorDescription();
            color98.ColorName = "Olive";
            color98.ColorCode = 0xff808000;
            list.Add(color98);
            ColorDescription color99 = new ColorDescription();
            color99.ColorName = "OliveDrab";
            color99.ColorCode = 0xff6b8e23;
            list.Add(color99);
            ColorDescription color100 = new ColorDescription();
            color100.ColorName = "Orange";
            color100.ColorCode = 0xffffa500;
            list.Add(color100);
            ColorDescription color101 = new ColorDescription();
            color101.ColorName = "OrangeRed";
            color101.ColorCode = 0xffff4500;
            list.Add(color101);
            ColorDescription color102 = new ColorDescription();
            color102.ColorName = "Orchid";
            color102.ColorCode = 0xffda70d6;
            list.Add(color102);
            ColorDescription color103 = new ColorDescription();
            color103.ColorName = "PaleGoldenrod";
            color103.ColorCode = 0xffeee8aa;
            list.Add(color103);
            ColorDescription color104 = new ColorDescription();
            color104.ColorName = "PaleGreen";
            color104.ColorCode = 0xff98fb98;
            list.Add(color104);
            ColorDescription color105 = new ColorDescription();
            color105.ColorName = "PaleTurquoise";
            color105.ColorCode = 0xffafeeee;
            list.Add(color105);
            ColorDescription color106 = new ColorDescription();
            color106.ColorName = "PaleVioletRed";
            color106.ColorCode = 0xffdb7093;
            list.Add(color106);
            ColorDescription color107 = new ColorDescription();
            color107.ColorName = "PapayaWhip";
            color107.ColorCode = 0xffffefd5;
            list.Add(color107);
            ColorDescription color108 = new ColorDescription();
            color108.ColorName = "PeachPuff";
            color108.ColorCode = 0xffffdab9;
            list.Add(color108);
            ColorDescription color109 = new ColorDescription();
            color109.ColorName = "Peru";
            color109.ColorCode = 0xffcd853f;
            list.Add(color109);
            ColorDescription color110 = new ColorDescription();
            color110.ColorName = "Pink";
            color110.ColorCode = 0xffffc0cb;
            list.Add(color110);
            ColorDescription color111 = new ColorDescription();
            color111.ColorName = "Plum";
            color111.ColorCode = 0xffdda0dd;
            list.Add(color111);
            ColorDescription color112 = new ColorDescription();
            color112.ColorName = "PowderBlue";
            color112.ColorCode = 0xffb0e0e6;
            list.Add(color112);
            ColorDescription color113 = new ColorDescription();
            color113.ColorName = "Purple";
            color113.ColorCode = 0xff800080;
            list.Add(color113);
            ColorDescription color114 = new ColorDescription();
            color114.ColorName = "Red";
            color114.ColorCode = 0xffff0000;
            list.Add(color114);
            ColorDescription color115 = new ColorDescription();
            color115.ColorName = "RosyBrown";
            color115.ColorCode = 0xffbc8f8f;
            list.Add(color115);
            ColorDescription color116 = new ColorDescription();
            color116.ColorName = "RoyalBlue";
            color116.ColorCode = 0xff4169e1;
            list.Add(color116);
            ColorDescription color117 = new ColorDescription();
            color117.ColorName = "SaddleBrown";
            color117.ColorCode = 0xff8b4513;
            list.Add(color117);
            ColorDescription color118 = new ColorDescription();
            color118.ColorName = "Salmon";
            color118.ColorCode = 0xfffa8072;
            list.Add(color118);
            ColorDescription color119 = new ColorDescription();
            color119.ColorName = "SandyBrown";
            color119.ColorCode = 0xfff4a460;
            list.Add(color119);
            ColorDescription color120 = new ColorDescription();
            color120.ColorName = "SeaGreen";
            color120.ColorCode = 0xff2e8b57;
            list.Add(color120);
            ColorDescription color121 = new ColorDescription();
            color121.ColorName = "SeaShell";
            color121.ColorCode = 0xfffff5ee;
            list.Add(color121);
            ColorDescription color122 = new ColorDescription();
            color122.ColorName = "Sienna";
            color122.ColorCode = 0xffa0522d;
            list.Add(color122);
            ColorDescription color123 = new ColorDescription();
            color123.ColorName = "Silver";
            color123.ColorCode = 0xffc0c0c0;
            list.Add(color123);
            ColorDescription color124 = new ColorDescription();
            color124.ColorName = "SkyBlue";
            color124.ColorCode = 0xff87ceeb;
            list.Add(color124);
            ColorDescription color125 = new ColorDescription();
            color125.ColorName = "SlateBlue";
            color125.ColorCode = 0xff6a5acd;
            list.Add(color125);
            ColorDescription color126 = new ColorDescription();
            color126.ColorName = "SlateGray";
            color126.ColorCode = 0xff708090;
            list.Add(color126);
            ColorDescription color127 = new ColorDescription();
            color127.ColorName = "Snow";
            color127.ColorCode = 0xfffffafa;
            list.Add(color127);
            ColorDescription color128 = new ColorDescription();
            color128.ColorName = "SpringGreen";
            color128.ColorCode = 0xff00ff7f;
            list.Add(color128);
            ColorDescription color129 = new ColorDescription();
            color129.ColorName = "SteelBlue";
            color129.ColorCode = 0xff4682b4;
            list.Add(color129);
            ColorDescription color130 = new ColorDescription();
            color130.ColorName = "Tan";
            color130.ColorCode = 0xffd2b48c;
            list.Add(color130);
            ColorDescription color131 = new ColorDescription();
            color131.ColorName = "Teal";
            color131.ColorCode = 0xff008080;
            list.Add(color131);
            ColorDescription color132 = new ColorDescription();
            color132.ColorName = "Thistle";
            color132.ColorCode = 0xffd8bfd8;
            list.Add(color132);
            ColorDescription color133 = new ColorDescription();
            color133.ColorName = "Tomato";
            color133.ColorCode = 0xffff6347;
            list.Add(color133);
            ColorDescription color134 = new ColorDescription();
            color134.ColorName = "Transparent";
            color134.ColorCode = 0xffffff;
            list.Add(color134);
            ColorDescription color135 = new ColorDescription();
            color135.ColorName = "Turquoise";
            color135.ColorCode = 0xff40e0d0;
            list.Add(color135);
            ColorDescription color136 = new ColorDescription();
            color136.ColorName = "Violet";
            color136.ColorCode = 0xffee82ee;
            list.Add(color136);
            ColorDescription color137 = new ColorDescription();
            color137.ColorName = "Wheat";
            color137.ColorCode = 0xfff5deb3;
            list.Add(color137);
            ColorDescription color138 = new ColorDescription();
            color138.ColorName = "White";
            color138.ColorCode = uint.MaxValue;
            list.Add(color138);
            ColorDescription color139 = new ColorDescription();
            color139.ColorName = "WhiteSmoke";
            color139.ColorCode = 0xfff5f5f5;
            list.Add(color139);
            ColorDescription color140 = new ColorDescription();
            color140.ColorName = "Yellow";
            color140.ColorCode = 0xffffff00;
            list.Add(color140);
            ColorDescription color141 = new ColorDescription();
            color141.ColorName = "YellowGreen";
            color141.ColorCode = 0xff9acd32;
            list.Add(color141);
            //////////////////////////
            ColorDescription color142 = new ColorDescription();
            color141.ColorName = "OverseaBlue";
            color141.ColorCode = 0xFFF4F9FF;
            list.Add(color142);
            this.PredefinedColors = list;
        }

        public List<ColorDescription> GetColorSet()
        {
            List<ColorDescription> predefinedColors = new ColorsHelper().PredefinedColors;
            foreach (ColorDescription color in predefinedColors)
            {
                byte[] bytes = BitConverter.GetBytes(color.ColorCode);
                color.Value = Color.FromArgb(bytes[3], bytes[2], bytes[1], bytes[0]);
                color.ARGB = new SolidColorBrush(color.Value);
            }
            return predefinedColors;
        }
    }

    public class ColorDescription
    {
        public string ColorName { get; set; }
        public uint ColorCode { get; set; }
        public Color Value { get; set; }
        public Brush ARGB { get; set; }
    }
}
