//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECCentral.Portal.UI.Customer.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResCustomerQuery {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ResCustomerQuery()
        {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ECCentral.Portal.UI.Customer.Resources.ResCustomerQuery", typeof(ResCustomerQuery).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 批量显示头像 的本地化字符串。
        /// </summary>
        public static string Button_ActiveCustomerImage {
            get {
                return ResourceManager.GetString("Button_ActiveCustomerImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批量导入顾客 的本地化字符串。
        /// </summary>
        public static string Button_BatchImportCustomer {
            get {
                return ResourceManager.GetString("Button_BatchImportCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置顾客权限 的本地化字符串。
        /// </summary>
        public static string Button_CustomerRights {
            get {
                return ResourceManager.GetString("Button_CustomerRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string Button_EditCustomer {
            get {
                return ResourceManager.GetString("Button_EditCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 经验值历史 的本地化字符串。
        /// </summary>
        public static string Button_ExperienceLog {
            get {
                return ResourceManager.GetString("Button_ExperienceLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批量不显示头像 的本地化字符串。
        /// </summary>
        public static string Button_InactiveCustomerImage {
            get {
                return ResourceManager.GetString("Button_InactiveCustomerImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建 的本地化字符串。
        /// </summary>
        public static string Button_New {
            get {
                return ResourceManager.GetString("Button_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建订单 的本地化字符串。
        /// </summary>
        public static string Button_NewSo {
            get {
                return ResourceManager.GetString("Button_NewSo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 积分历史 的本地化字符串。
        /// </summary>
        public static string Button_PointLog {
            get {
                return ResourceManager.GetString("Button_PointLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 优惠券历史 的本地化字符串。
        /// </summary>
        public static string Button_Promotion {
            get {
                return ResourceManager.GetString("Button_Promotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 的本地化字符串。
        /// </summary>
        public static string Button_Search {
            get {
                return ResourceManager.GetString("Button_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看密保问题 的本地化字符串。
        /// </summary>
        public static string Button_SecurityQues {
            get {
                return ResourceManager.GetString("Button_SecurityQues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更改积分有效期 的本地化字符串。
        /// </summary>
        public static string Button_UpdateValidPoint {
            get {
                return ResourceManager.GetString("Button_UpdateValidPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 购买次数 的本地化字符串。
        /// </summary>
        public static string Ckb_BuyCount {
            get {
                return ResourceManager.GetString("Ckb_BuyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更多条件 的本地化字符串。
        /// </summary>
        public static string Ckb_QueryBuilder {
            get {
                return ResourceManager.GetString("Ckb_QueryBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册日期 的本地化字符串。
        /// </summary>
        public static string Ckb_RegisterTime {
            get {
                return ResourceManager.GetString("Ckb_RegisterTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 --所有-- 的本地化字符串。
        /// </summary>
        public static string ComboBox_All {
            get {
                return ResourceManager.GetString("ComboBox_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ---选择全部--- 的本地化字符串。
        /// </summary>
        public static string Combox_SelectAll {
            get {
                return ResourceManager.GetString("Combox_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string DataGrid_Column_Head_Opreation {
            get {
                return ResourceManager.GetString("DataGrid_Column_Head_Opreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置顾客权限 的本地化字符串。
        /// </summary>
        public static string Dialog_RightManage {
            get {
                return ResourceManager.GetString("Dialog_RightManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账户保护验证 的本地化字符串。
        /// </summary>
        public static string Dialog_ViewSecurityQues {
            get {
                return ResourceManager.GetString("Dialog_ViewSecurityQues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基本信息 的本地化字符串。
        /// </summary>
        public static string Expander_BaseInfo {
            get {
                return ResourceManager.GetString("Expander_BaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询条件 的本地化字符串。
        /// </summary>
        public static string Expander_QueryBuilder {
            get {
                return ResourceManager.GetString("Expander_QueryBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询结果 的本地化字符串。
        /// </summary>
        public static string Expander_QueryResult {
            get {
                return ResourceManager.GetString("Expander_QueryResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 头像 的本地化字符串。
        /// </summary>
        public static string Grid_AvtarImage {
            get {
                return ResourceManager.GetString("Grid_AvtarImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属渠道 的本地化字符串。
        /// </summary>
        public static string Grid_ChannelName {
            get {
                return ResourceManager.GetString("Grid_ChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建日期 的本地化字符串。
        /// </summary>
        public static string Grid_CreateDate {
            get {
                return ResourceManager.GetString("Grid_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电子邮箱 的本地化字符串。
        /// </summary>
        public static string Grid_CustomerEmail {
            get {
                return ResourceManager.GetString("Grid_CustomerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顾客账号 的本地化字符串。
        /// </summary>
        public static string Grid_CustomerID {
            get {
                return ResourceManager.GetString("Grid_CustomerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顾客名称 的本地化字符串。
        /// </summary>
        public static string Grid_CustomerName {
            get {
                return ResourceManager.GetString("Grid_CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等级 的本地化字符串。
        /// </summary>
        public static string Grid_CustomerRank {
            get {
                return ResourceManager.GetString("Grid_CustomerRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string Grid_CustomerStatus {
            get {
                return ResourceManager.GetString("Grid_CustomerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        public static string Grid_CustomerType {
            get {
                return ResourceManager.GetString("Grid_CustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 贵宾设置 的本地化字符串。
        /// </summary>
        public static string Grid_CustomerVip {
            get {
                return ResourceManager.GetString("Grid_CustomerVip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 来源 的本地化字符串。
        /// </summary>
        public static string Grid_FromLinkSource {
            get {
                return ResourceManager.GetString("Grid_FromLinkSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮件已验证 的本地化字符串。
        /// </summary>
        public static string Grid_IsEmailConfirmed {
            get {
                return ResourceManager.GetString("Grid_IsEmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机已验证 的本地化字符串。
        /// </summary>
        public static string Grid_IsPhoneConfirmed {
            get {
                return ResourceManager.GetString("Grid_IsPhoneConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最近购买时间 的本地化字符串。
        /// </summary>
        public static string Grid_LastBuyDate {
            get {
                return ResourceManager.GetString("Grid_LastBuyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推荐人 的本地化字符串。
        /// </summary>
        public static string Grid_RecommendedByCustomerID {
            get {
                return ResourceManager.GetString("Grid_RecommendedByCustomerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册日期 的本地化字符串。
        /// </summary>
        public static string Grid_RegisterTime {
            get {
                return ResourceManager.GetString("Grid_RegisterTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public static string Grid_Remark {
            get {
                return ResourceManager.GetString("Grid_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限名称 的本地化字符串。
        /// </summary>
        public static string Grid_RightName {
            get {
                return ResourceManager.GetString("Grid_RightName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        public static string Grid_SelectRow {
            get {
                return ResourceManager.GetString("Grid_SelectRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否学生 的本地化字符串。
        /// </summary>
        public static string Grid_StudentFlag {
            get {
                return ResourceManager.GetString("Grid_StudentFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 购买金额 的本地化字符串。
        /// </summary>
        public static string Grid_SumBuyAmt {
            get {
                return ResourceManager.GetString("Grid_SumBuyAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 购买次数 的本地化字符串。
        /// </summary>
        public static string Grid_SumBuyCount {
            get {
                return ResourceManager.GetString("Grid_SumBuyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 头像状态: 的本地化字符串。
        /// </summary>
        public static string Label_AvtarImageStatus {
            get {
                return ResourceManager.GetString("Label_AvtarImageStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 购买次数: 的本地化字符串。
        /// </summary>
        public static string Label_BuyCount {
            get {
                return ResourceManager.GetString("Label_BuyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 之间 的本地化字符串。
        /// </summary>
        public static string Label_BuyCountArea {
            get {
                return ResourceManager.GetString("Label_BuyCountArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区间值 的本地化字符串。
        /// </summary>
        public static string Label_BuyCountAreaValue {
            get {
                return ResourceManager.GetString("Label_BuyCountAreaValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端点值 的本地化字符串。
        /// </summary>
        public static string Label_BuyCountEndpointValue {
            get {
                return ResourceManager.GetString("Label_BuyCountEndpointValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属渠道: 的本地化字符串。
        /// </summary>
        public static string Label_ChannelSysNo {
            get {
                return ResourceManager.GetString("Label_ChannelSysNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属公司: 的本地化字符串。
        /// </summary>
        public static string Label_Company {
            get {
                return ResourceManager.GetString("Label_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建人: 的本地化字符串。
        /// </summary>
        public static string Label_CreateUser {
            get {
                return ResourceManager.GetString("Label_CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顾客地址: 的本地化字符串。
        /// </summary>
        public static string Label_CustomerAddress {
            get {
                return ResourceManager.GetString("Label_CustomerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电子邮箱: 的本地化字符串。
        /// </summary>
        public static string Label_CustomerEmail {
            get {
                return ResourceManager.GetString("Label_CustomerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顾客账号: 的本地化字符串。
        /// </summary>
        public static string Label_CustomerID {
            get {
                return ResourceManager.GetString("Label_CustomerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 贵宾设置: 的本地化字符串。
        /// </summary>
        public static string Label_CustomerIsVIP {
            get {
                return ResourceManager.GetString("Label_CustomerIsVIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顾客名称: 的本地化字符串。
        /// </summary>
        public static string Label_CustomerName {
            get {
                return ResourceManager.GetString("Label_CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顾客电话: 的本地化字符串。
        /// </summary>
        public static string Label_CustomerPhone {
            get {
                return ResourceManager.GetString("Label_CustomerPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顾客状态: 的本地化字符串。
        /// </summary>
        public static string Label_CustomerStatus {
            get {
                return ResourceManager.GetString("Label_CustomerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统编号: 的本地化字符串。
        /// </summary>
        public static string Label_CustomerSysNo {
            get {
                return ResourceManager.GetString("Label_CustomerSysNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顾客类型: 的本地化字符串。
        /// </summary>
        public static string Label_CustomerType {
            get {
                return ResourceManager.GetString("Label_CustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顾客来源: 的本地化字符串。
        /// </summary>
        public static string Label_FromLinkSource {
            get {
                return ResourceManager.GetString("Label_FromLinkSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱已验证: 的本地化字符串。
        /// </summary>
        public static string Label_IsEmailConfirmed {
            get {
                return ResourceManager.GetString("Label_IsEmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话已验证: 的本地化字符串。
        /// </summary>
        public static string Label_IsPhoneConfirmed {
            get {
                return ResourceManager.GetString("Label_IsPhoneConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 到 的本地化字符串。
        /// </summary>
        public static string Label_MaxBuyCount {
            get {
                return ResourceManager.GetString("Label_MaxBuyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在 的本地化字符串。
        /// </summary>
        public static string Label_MinBuyCount {
            get {
                return ResourceManager.GetString("Label_MinBuyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推 荐 人: 的本地化字符串。
        /// </summary>
        public static string Label_RecommendedByCustomerID {
            get {
                return ResourceManager.GetString("Label_RecommendedByCustomerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册日期: 的本地化字符串。
        /// </summary>
        public static string Label_RegisterTime {
            get {
                return ResourceManager.GetString("Label_RegisterTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 到 的本地化字符串。
        /// </summary>
        public static string Label_RegisterTimeEnd {
            get {
                return ResourceManager.GetString("Label_RegisterTimeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从 的本地化字符串。
        /// </summary>
        public static string Label_RegisterTimeFrom {
            get {
                return ResourceManager.GetString("Label_RegisterTimeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属社团: 的本地化字符串。
        /// </summary>
        public static string Label_Society {
            get {
                return ResourceManager.GetString("Label_Society", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审核人: 的本地化字符串。
        /// </summary>
        public static string Label_VerifyUser {
            get {
                return ResourceManager.GetString("Label_VerifyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您没有此功能的操作权限！ 的本地化字符串。
        /// </summary>
        public static string Msg_HasNoRight {
            get {
                return ResourceManager.GetString("Msg_HasNoRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择顾客后操作！ 的本地化字符串。
        /// </summary>
        public static string Msg_OnSelectCostomer {
            get {
                return ResourceManager.GetString("Msg_OnSelectCostomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作成功！ 的本地化字符串。
        /// </summary>
        public static string Msg_OperationOk {
            get {
                return ResourceManager.GetString("Msg_OperationOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批量导入顾客 的本地化字符串。
        /// </summary>
        public static string PopTitle_BatchImportCustomer {
            get {
                return ResourceManager.GetString("PopTitle_BatchImportCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 经验值历史 的本地化字符串。
        /// </summary>
        public static string PopTitle_ExperienceLog {
            get {
                return ResourceManager.GetString("PopTitle_ExperienceLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更改积分有效期 的本地化字符串。
        /// </summary>
        public static string PopTitle_UpdateValidPoint {
            get {
                return ResourceManager.GetString("PopTitle_UpdateValidPoint", resourceCulture);
            }
        }
    }
}
