//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECCentral.Portal.UI.Customer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResCustomerBaseInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ResCustomerBaseInfo()
        {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ECCentral.Portal.UI.Customer.Resources.ResCustomerBaseInfo", typeof(ResCustomerBaseInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顾客基本信息.
        /// </summary>
        public static string GroupBox_CustomerBaseInfo {
            get {
                return ResourceManager.GetString("GroupBox_CustomerBaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账户余额:.
        /// </summary>
        public static string Label_CustomerBalance {
            get {
                return ResourceManager.GetString("Label_CustomerBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顾客邮箱:.
        /// </summary>
        public static string Label_CustomerEmail {
            get {
                return ResourceManager.GetString("Label_CustomerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顾客帐号:.
        /// </summary>
        public static string Label_CustomerID {
            get {
                return ResourceManager.GetString("Label_CustomerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顾客名称:.
        /// </summary>
        public static string Label_CustomerName {
            get {
                return ResourceManager.GetString("Label_CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 联系方式:.
        /// </summary>
        public static string Label_CustomerPhone {
            get {
                return ResourceManager.GetString("Label_CustomerPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有效积分:.
        /// </summary>
        public static string Label_CustomerPoint {
            get {
                return ResourceManager.GetString("Label_CustomerPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顾客等级:.
        /// </summary>
        public static string Label_CustomerRank {
            get {
                return ResourceManager.GetString("Label_CustomerRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顾客性别:.
        /// </summary>
        public static string Label_CustomerSex {
            get {
                return ResourceManager.GetString("Label_CustomerSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统编号:.
        /// </summary>
        public static string Label_SysNo {
            get {
                return ResourceManager.GetString("Label_SysNo", resourceCulture);
            }
        }
    }
}
