//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECCentral.Portal.UI.RMA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResRefundMaintain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ResRefundMaintain() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ECCentral.Portal.UI.RMA.Resources.ResRefundMaintain", typeof(ResRefundMaintain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作废.
        /// </summary>
        public static string Button_Abandon {
            get {
                return ResourceManager.GetString("Button_Abandon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 计算.
        /// </summary>
        public static string Button_Calculate {
            get {
                return ResourceManager.GetString("Button_Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消提交审核.
        /// </summary>
        public static string Button_CancelSubmitAudit {
            get {
                return ResourceManager.GetString("Button_CancelSubmitAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 三费合计.
        /// </summary>
        public static string Button_GetShipFee {
            get {
                return ResourceManager.GetString("Button_GetShipFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置发票号.
        /// </summary>
        public static string Button_InvoiceNo {
            get {
                return ResourceManager.GetString("Button_InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打印.
        /// </summary>
        public static string Button_Print {
            get {
                return ResourceManager.GetString("Button_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退款.
        /// </summary>
        public static string Button_Refund {
            get {
                return ResourceManager.GetString("Button_Refund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退款调整单.
        /// </summary>
        public static string Button_RefundBalance {
            get {
                return ResourceManager.GetString("Button_RefundBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提交审核.
        /// </summary>
        public static string Button_SubmitAudit {
            get {
                return ResourceManager.GetString("Button_SubmitAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新.
        /// </summary>
        public static string Button_Update {
            get {
                return ResourceManager.GetString("Button_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新财务备注.
        /// </summary>
        public static string Button_UpdateFinanceNote {
            get {
                return ResourceManager.GetString("Button_UpdateFinanceNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扣回价保积分数.
        /// </summary>
        public static string CheckBox_HasPriceprotectPoint {
            get {
                return ResourceManager.GetString("CheckBox_HasPriceprotectPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否涉及现金.
        /// </summary>
        public static string CheckBox_IsRelateCash {
            get {
                return ResourceManager.GetString("CheckBox_IsRelateCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退款单详情.
        /// </summary>
        public static string Expander_RefundDetail {
            get {
                return ResourceManager.GetString("Expander_RefundDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单件列表.
        /// </summary>
        public static string Expander_Registers {
            get {
                return ResourceManager.GetString("Expander_Registers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初算退礼品卡.
        /// </summary>
        public static string Grid_OrgGiftCardAmt {
            get {
                return ResourceManager.GetString("Grid_OrgGiftCardAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 赠送积分.
        /// </summary>
        public static string Grid_OrgPoint {
            get {
                return ResourceManager.GetString("Grid_OrgPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 订单当时价格.
        /// </summary>
        public static string Grid_OrgPrice {
            get {
                return ResourceManager.GetString("Grid_OrgPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支付种类.
        /// </summary>
        public static string Grid_PayType {
            get {
                return ResourceManager.GetString("Grid_PayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品编号.
        /// </summary>
        public static string Grid_ProductID {
            get {
                return ResourceManager.GetString("Grid_ProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 产品名称.
        /// </summary>
        public static string Grid_ProductName {
            get {
                return ResourceManager.GetString("Grid_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品价值.
        /// </summary>
        public static string Grid_ProductValue {
            get {
                return ResourceManager.GetString("Grid_ProductValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初算退现金.
        /// </summary>
        public static string Grid_RefundCash {
            get {
                return ResourceManager.GetString("Grid_RefundCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初算退积分.
        /// </summary>
        public static string Grid_RefundPoint {
            get {
                return ResourceManager.GetString("Grid_RefundPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退款价值.
        /// </summary>
        public static string Grid_RefundPrice {
            get {
                return ResourceManager.GetString("Grid_RefundPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退款类型.
        /// </summary>
        public static string Grid_RefundType {
            get {
                return ResourceManager.GetString("Grid_RefundType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单件号.
        /// </summary>
        public static string Grid_RegisterSysNo {
            get {
                return ResourceManager.GetString("Grid_RegisterSysNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 促销价格.
        /// </summary>
        public static string Grid_UnitDiscount {
            get {
                return ResourceManager.GetString("Grid_UnitDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作成功 !.
        /// </summary>
        public static string Info_OperateSuccessfully {
            get {
                return ResourceManager.GetString("Info_OperateSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开户银行:.
        /// </summary>
        public static string Label_BankName {
            get {
                return ResourceManager.GetString("Label_BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 银行支行:.
        /// </summary>
        public static string Label_BranchBankName {
            get {
                return ResourceManager.GetString("Label_BranchBankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 银行卡号:.
        /// </summary>
        public static string Label_CardNumber {
            get {
                return ResourceManager.GetString("Label_CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 持卡人姓名:.
        /// </summary>
        public static string Label_CardOwnerName {
            get {
                return ResourceManager.GetString("Label_CardOwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退现金:.
        /// </summary>
        public static string Label_CashAmt {
            get {
                return ResourceManager.GetString("Label_CashAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 补偿运费:.
        /// </summary>
        public static string Label_CompensateShipPrice {
            get {
                return ResourceManager.GetString("Label_CompensateShipPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 联系人:.
        /// </summary>
        public static string Label_Contact {
            get {
                return ResourceManager.GetString("Label_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建时间:.
        /// </summary>
        public static string Label_CreateDate {
            get {
                return ResourceManager.GetString("Label_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建人:.
        /// </summary>
        public static string Label_CreateUser {
            get {
                return ResourceManager.GetString("Label_CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客户ID:.
        /// </summary>
        public static string Label_CustomerID {
            get {
                return ResourceManager.GetString("Label_CustomerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客户名称:.
        /// </summary>
        public static string Label_CustomerName {
            get {
                return ResourceManager.GetString("Label_CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客户发货日期:.
        /// </summary>
        public static string Label_CustomerSendDate {
            get {
                return ResourceManager.GetString("Label_CustomerSendDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从账户扣积分:.
        /// </summary>
        public static string Label_DeductPointFromAccount {
            get {
                return ResourceManager.GetString("Label_DeductPointFromAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本次退款扣积分:.
        /// </summary>
        public static string Label_DeductPointFromCurrentCash {
            get {
                return ResourceManager.GetString("Label_DeductPointFromCurrentCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取件日期.
        /// </summary>
        public static string Label_DeliveryDate {
            get {
                return ResourceManager.GetString("Label_DeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 财务备注:.
        /// </summary>
        public static string Label_FinanceNote {
            get {
                return ResourceManager.GetString("Label_FinanceNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退礼品卡:.
        /// </summary>
        public static string Label_GiftCardAmt {
            get {
                return ResourceManager.GetString("Label_GiftCardAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已退金额:.
        /// </summary>
        public static string Label_HistoryRefund {
            get {
                return ResourceManager.GetString("Label_HistoryRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 银行单备注:.
        /// </summary>
        public static string Label_IncomeNote {
            get {
                return ResourceManager.GetString("Label_IncomeNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发票所在地:.
        /// </summary>
        public static string Label_InvoiceLocation {
            get {
                return ResourceManager.GetString("Label_InvoiceLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发票号:.
        /// </summary>
        public static string Label_InvoiceNo {
            get {
                return ResourceManager.GetString("Label_InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 备注:.
        /// </summary>
        public static string Label_Memo {
            get {
                return ResourceManager.GetString("Label_Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初算退现金:.
        /// </summary>
        public static string Label_OrgCashAmt {
            get {
                return ResourceManager.GetString("Label_OrgCashAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初算退礼品卡:.
        /// </summary>
        public static string Label_OrgGiftCardAmt {
            get {
                return ResourceManager.GetString("Label_OrgGiftCardAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初算退积分:.
        /// </summary>
        public static string Label_OrgPointAmt {
            get {
                return ResourceManager.GetString("Label_OrgPointAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 手续费:.
        /// </summary>
        public static string Label_PayPrice {
            get {
                return ResourceManager.GetString("Label_PayPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退积分:.
        /// </summary>
        public static string Label_PointAmt {
            get {
                return ResourceManager.GetString("Label_PointAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮政汇款地址:.
        /// </summary>
        public static string Label_PostAddress {
            get {
                return ResourceManager.GetString("Label_PostAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保价费:.
        /// </summary>
        public static string Label_PremiumAmt {
            get {
                return ResourceManager.GetString("Label_PremiumAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 收款人姓名:.
        /// </summary>
        public static string Label_ReceiverName {
            get {
                return ResourceManager.GetString("Label_ReceiverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退款单编号:.
        /// </summary>
        public static string Label_RefundID {
            get {
                return ResourceManager.GetString("Label_RefundID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退款支付类型:.
        /// </summary>
        public static string Label_RefundPayType {
            get {
                return ResourceManager.GetString("Label_RefundPayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退款原因:.
        /// </summary>
        public static string Label_RefundReason {
            get {
                return ResourceManager.GetString("Label_RefundReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 运费:.
        /// </summary>
        public static string Label_ShippingCharge {
            get {
                return ResourceManager.GetString("Label_ShippingCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 积分支付比例:.
        /// </summary>
        public static string Label_SOCashPointRate {
            get {
                return ResourceManager.GetString("Label_SOCashPointRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 销售单编号:.
        /// </summary>
        public static string Label_SOSysNo {
            get {
                return ResourceManager.GetString("Label_SOSysNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状态:.
        /// </summary>
        public static string Label_Status {
            get {
                return ResourceManager.GetString("Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合计:.
        /// </summary>
        public static string Label_TotalAmt {
            get {
                return ResourceManager.GetString("Label_TotalAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮政编码:.
        /// </summary>
        public static string Label_Zip {
            get {
                return ResourceManager.GetString("Label_Zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 三费合计.
        /// </summary>
        public static string PopTitle_ShipFeeDetail {
            get {
                return ResourceManager.GetString("PopTitle_ShipFeeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字段不能为空.
        /// </summary>
        public static string Validation_RequiredField {
            get {
                return ResourceManager.GetString("Validation_RequiredField", resourceCulture);
            }
        }
    }
}
