//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECCentral.Portal.UI.PO.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResConsignAdjustNew {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ResConsignAdjustNew() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ECCentral.Portal.UI.PO.Resources.ResConsignAdjustNew", typeof(ResConsignAdjustNew).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定删除？.
        /// </summary>
        public static string AlertMsg_ConfirmDelDeduct {
            get {
                return ResourceManager.GetString("AlertMsg_ConfirmDelDeduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新失败.
        /// </summary>
        public static string AlertMsg_ModifyFailed {
            get {
                return ResourceManager.GetString("AlertMsg_ModifyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新成功.
        /// </summary>
        public static string AlertMsg_ModifySuc {
            get {
                return ResourceManager.GetString("AlertMsg_ModifySuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作废.
        /// </summary>
        public static string Button_Abandon {
            get {
                return ResourceManager.GetString("Button_Abandon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加扣款项.
        /// </summary>
        public static string Button_AddDeduct {
            get {
                return ResourceManager.GetString("Button_AddDeduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 审 核.
        /// </summary>
        public static string Button_Audit {
            get {
                return ResourceManager.GetString("Button_Audit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除扣款项.
        /// </summary>
        public static string Button_DeleteDeduct {
            get {
                return ResourceManager.GetString("Button_DeleteDeduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新.
        /// </summary>
        public static string Button_Modify {
            get {
                return ResourceManager.GetString("Button_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 记帐类型.
        /// </summary>
        public static string GridHeader_DeductAccountType {
            get {
                return ResourceManager.GetString("GridHeader_DeductAccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扣款金额.
        /// </summary>
        public static string GridHeader_DeductAmt {
            get {
                return ResourceManager.GetString("GridHeader_DeductAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扣款方式.
        /// </summary>
        public static string GridHeader_DeductMethod {
            get {
                return ResourceManager.GetString("GridHeader_DeductMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扣款名称.
        /// </summary>
        public static string GridHeader_DeductName {
            get {
                return ResourceManager.GetString("GridHeader_DeductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扣款类型.
        /// </summary>
        public static string GridHeader_DeductType {
            get {
                return ResourceManager.GetString("GridHeader_DeductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定更新？.
        /// </summary>
        public static string InfoMsg_ConfirmModify {
            get {
                return ResourceManager.GetString("InfoMsg_ConfirmModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基本信息.
        /// </summary>
        public static string Label_BasicInfo {
            get {
                return ResourceManager.GetString("Label_BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扣款项信息.
        /// </summary>
        public static string Label_DeductInfo {
            get {
                return ResourceManager.GetString("Label_DeductInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 产品经理：.
        /// </summary>
        public static string Label_PM {
            get {
                return ResourceManager.GetString("Label_PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 供应商：.
        /// </summary>
        public static string Label_Vendor {
            get {
                return ResourceManager.GetString("Label_Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所属年月：.
        /// </summary>
        public static string Lable_SettleRange {
            get {
                return ResourceManager.GetString("Lable_SettleRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结算单号：.
        /// </summary>
        public static string Lable_SettleSysNo {
            get {
                return ResourceManager.GetString("Lable_SettleSysNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建失败.
        /// </summary>
        public static string Msg_CreateFailed {
            get {
                return ResourceManager.GetString("Msg_CreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建成功.
        /// </summary>
        public static string Msg_CreateSuc {
            get {
                return ResourceManager.GetString("Msg_CreateSuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        public static string Msg_Title {
            get {
                return ResourceManager.GetString("Msg_Title", resourceCulture);
            }
        }
    }
}
