//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Newegg.Oversea.Silverlight.Controls.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public MessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Newegg.Oversea.Silverlight.Controls.Resources.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform operation..
        /// </summary>
        public static string Automation_OperationCannotBePerformed {
            get {
                return ResourceManager.GetString("Automation_OperationCannotBePerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot call Show() on a ChildWindow that is in the visual tree. ChildWindow should be the top-most element in the .xaml file..
        /// </summary>
        public static string ChildWindow_InvalidOperation {
            get {
                return ResourceManager.GetString("ChildWindow_InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Combox_ExtraAllText {
            get {
                return ResourceManager.GetString("Combox_ExtraAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select.
        /// </summary>
        public static string Combox_ExtraSelectText {
            get {
                return ResourceManager.GetString("Combox_ExtraSelectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Combox_Loading {
            get {
                return ResourceManager.GetString("Combox_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string ContextMenu_Copy {
            get {
                return ResourceManager.GetString("ContextMenu_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string ContextMenu_Cut {
            get {
                return ResourceManager.GetString("ContextMenu_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string ContextMenu_Paste {
            get {
                return ResourceManager.GetString("ContextMenu_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string ContextMenu_SelectAll {
            get {
                return ResourceManager.GetString("ContextMenu_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string DateRange_Button_Done_Text {
            get {
                return ResourceManager.GetString("DateRange_Button_Done_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Dates After.
        /// </summary>
        public static string DateRange_Calendar_AllDatesAfter_Title {
            get {
                return ResourceManager.GetString("DateRange_Calendar_AllDatesAfter_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Dates Before.
        /// </summary>
        public static string DateRange_Calendar_AllDatesBefore_Title {
            get {
                return ResourceManager.GetString("DateRange_Calendar_AllDatesBefore_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string DateRange_Calendar_EndDate_Title {
            get {
                return ResourceManager.GetString("DateRange_Calendar_EndDate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific Date.
        /// </summary>
        public static string DateRange_Calendar_SpecificDate_Title {
            get {
                return ResourceManager.GetString("DateRange_Calendar_SpecificDate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string DateRange_Calendar_StartDate_Title {
            get {
                return ResourceManager.GetString("DateRange_Calendar_StartDate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Dates After {0:MM/dd/yyyy}.
        /// </summary>
        public static string DateRange_DisplayAfterDateFormat {
            get {
                return ResourceManager.GetString("DateRange_DisplayAfterDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Dates Before {0:MM/dd/yyyy}.
        /// </summary>
        public static string DateRange_DisplayBeforeDateFormat {
            get {
                return ResourceManager.GetString("DateRange_DisplayBeforeDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:MM/dd/yyyy} to {1:MM/dd/yyyy}.
        /// </summary>
        public static string DateRange_DisplayRangeDateFormat {
            get {
                return ResourceManager.GetString("DateRange_DisplayRangeDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:MM/dd/yyyy}.
        /// </summary>
        public static string DateRange_DisplaySpecificDateFormat {
            get {
                return ResourceManager.GetString("DateRange_DisplaySpecificDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AD.
        /// </summary>
        public static string DateRange_RangeType_AfterDate_Code {
            get {
                return ResourceManager.GetString("DateRange_RangeType_AfterDate_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Dates After.
        /// </summary>
        public static string DateRange_RangeType_AfterDate_Text {
            get {
                return ResourceManager.GetString("DateRange_RangeType_AfterDate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BD.
        /// </summary>
        public static string DateRange_RangeType_BeforeDate_Code {
            get {
                return ResourceManager.GetString("DateRange_RangeType_BeforeDate_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Dates Before.
        /// </summary>
        public static string DateRange_RangeType_BeforeDate_Text {
            get {
                return ResourceManager.GetString("DateRange_RangeType_BeforeDate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD.
        /// </summary>
        public static string DateRange_RangeType_ClearDays_Code {
            get {
                return ResourceManager.GetString("DateRange_RangeType_ClearDays_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Specified.
        /// </summary>
        public static string DateRange_RangeType_ClearDays_Text {
            get {
                return ResourceManager.GetString("DateRange_RangeType_ClearDays_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L30.
        /// </summary>
        public static string DateRange_RangeType_Last30days_Code {
            get {
                return ResourceManager.GetString("DateRange_RangeType_Last30days_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 30 days.
        /// </summary>
        public static string DateRange_RangeType_Last30days_Text {
            get {
                return ResourceManager.GetString("DateRange_RangeType_Last30days_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L3.
        /// </summary>
        public static string DateRange_RangeType_Last3days_Code {
            get {
                return ResourceManager.GetString("DateRange_RangeType_Last3days_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 3 days.
        /// </summary>
        public static string DateRange_RangeType_Last3days_Text {
            get {
                return ResourceManager.GetString("DateRange_RangeType_Last3days_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L7.
        /// </summary>
        public static string DateRange_RangeType_Last7days_Code {
            get {
                return ResourceManager.GetString("DateRange_RangeType_Last7days_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 7 days.
        /// </summary>
        public static string DateRange_RangeType_Last7days_Text {
            get {
                return ResourceManager.GetString("DateRange_RangeType_Last7days_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RD.
        /// </summary>
        public static string DateRange_RangeType_RangeDate_Code {
            get {
                return ResourceManager.GetString("DateRange_RangeType_RangeDate_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Range.
        /// </summary>
        public static string DateRange_RangeType_RangeDate_Text {
            get {
                return ResourceManager.GetString("DateRange_RangeType_RangeDate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----------------------------------------.
        /// </summary>
        public static string DateRange_RangeType_Separator_Text {
            get {
                return ResourceManager.GetString("DateRange_RangeType_Separator_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SD.
        /// </summary>
        public static string DateRange_RangeType_SpecificDate_Code {
            get {
                return ResourceManager.GetString("DateRange_RangeType_SpecificDate_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific Date.
        /// </summary>
        public static string DateRange_RangeType_SpecificDate_Text {
            get {
                return ResourceManager.GetString("DateRange_RangeType_SpecificDate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        public static string DateRange_RangeType_Today_Code {
            get {
                return ResourceManager.GetString("DateRange_RangeType_Today_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string DateRange_RangeType_Today_Text {
            get {
                return ResourceManager.GetString("DateRange_RangeType_Today_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Specified.
        /// </summary>
        public static string DateRange_TextBox_Watermark {
            get {
                return ResourceManager.GetString("DateRange_TextBox_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help:.
        /// </summary>
        public static string MessageTip_Title_Help {
            get {
                return ResourceManager.GetString("MessageTip_Title_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string NotificationTip_Title {
            get {
                return ResourceManager.GetString("NotificationTip_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close All Tabs.
        /// </summary>
        public static string PageBrowser_CloseAllTabs_Title {
            get {
                return ResourceManager.GetString("PageBrowser_CloseAllTabs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page tab&apos;s total is more than maximum total!.
        /// </summary>
        public static string PageBrowser_Error_MoreThanMaxPageTabTotal {
            get {
                return ResourceManager.GetString("PageBrowser_Error_MoreThanMaxPageTabTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string PageBrowser_Home {
            get {
                return ResourceManager.GetString("PageBrowser_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string PageBrowser_LoadingSpin_Title {
            get {
                return ResourceManager.GetString("PageBrowser_LoadingSpin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string PageBrowser_MessageBox_Error {
            get {
                return ResourceManager.GetString("PageBrowser_MessageBox_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error：.
        /// </summary>
        public static string PageBrowser_MessageBox_Error_Title {
            get {
                return ResourceManager.GetString("PageBrowser_MessageBox_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string PageBrowser_MessageBox_Success {
            get {
                return ResourceManager.GetString("PageBrowser_MessageBox_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success：.
        /// </summary>
        public static string PageBrowser_MessageBox_Success_Title {
            get {
                return ResourceManager.GetString("PageBrowser_MessageBox_Success_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string PageBrowser_MessageBox_Warning {
            get {
                return ResourceManager.GetString("PageBrowser_MessageBox_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning：.
        /// </summary>
        public static string PageBrowser_MessageBox_Warning_Title {
            get {
                return ResourceManager.GetString("PageBrowser_MessageBox_Warning_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string PageBrowser_Refresh {
            get {
                return ResourceManager.GetString("PageBrowser_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input..
        /// </summary>
        public static string PhoneControl_InvalidNumber {
            get {
                return ResourceManager.GetString("PhoneControl_InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a required field..
        /// </summary>
        public static string PhoneControl_RequiredField {
            get {
                return ResourceManager.GetString("PhoneControl_RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string PopupBox_Button_Cancel {
            get {
                return ResourceManager.GetString("PopupBox_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string PopupBox_Button_Confirm {
            get {
                return ResourceManager.GetString("PopupBox_Button_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string PopupBox_Button_No {
            get {
                return ResourceManager.GetString("PopupBox_Button_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string PopupBox_Button_Yes {
            get {
                return ResourceManager.GetString("PopupBox_Button_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not found specific dialog..
        /// </summary>
        public static string PopupBox_CannotFoundPage {
            get {
                return ResourceManager.GetString("PopupBox_CannotFoundPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string PopupBox_Title_Confirm {
            get {
                return ResourceManager.GetString("PopupBox_Title_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string PopupBox_Title_Error {
            get {
                return ResourceManager.GetString("PopupBox_Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string PopupBox_Title_Information {
            get {
                return ResourceManager.GetString("PopupBox_Title_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string PopupBox_Title_Warning {
            get {
                return ResourceManager.GetString("PopupBox_Title_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Search.
        /// </summary>
        public static string SearchControl_AdvancedSearchHeader {
            get {
                return ResourceManager.GetString("SearchControl_AdvancedSearchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string SearchControl_Clear {
            get {
                return ResourceManager.GetString("SearchControl_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Name.
        /// </summary>
        public static string SearchControl_NameWaterMark {
            get {
                return ResourceManager.GetString("SearchControl_NameWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SearchControl_Save {
            get {
                return ResourceManager.GetString("SearchControl_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchControl_SearchButtonContent {
            get {
                return ResourceManager.GetString("SearchControl_SearchButtonContent", resourceCulture);
            }
        }
    }
}
