using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using ECCentral.BizEntity.Common;
using ECCentral.Service.Utility;
using ECCentral.Service.Utility.DataAccess;
using c = ECCentral.BizEntity.Common;

namespace ECCentral.Service.Common.SqlDataAccess
{
    public class EnumCodeMapRegister : IStartup
    {
        public void Start()
        {
            //EnumCodeMapper.AddMap<CustomerType>(new Dictionary<CustomerType, int>{
            //    { CustomerType.Personal, 0 },
            //    { CustomerType.Enterprise, 1 },
            //    { CustomerType.EnterpriseUnVerify, -1 },
            //    { CustomerType.Campus, 2 },
            //    { CustomerType.CampusUnVerify, -2 }
            //});

            //EnumCodeMapper.AddMap<AgentType>(new Dictionary<AgentType, string>{
            //    { AgentType.Personal, "P" },
            //    { AgentType.Enterprise, "E" },
            //    { AgentType.Campus, "C" }
            //});
            EnumCodeMapper.AddMap<DepartmentValidStatus>(new Dictionary<DepartmentValidStatus, string>{
                { DepartmentValidStatus.Active, "A" },
                { DepartmentValidStatus.DeActive, "D" }
            });

            EnumCodeMapper.AddMap<BizOperationUserType>(new Dictionary<BizOperationUserType, string>{
                { BizOperationUserType.InUser, "I" },
                { BizOperationUserType.EditUser, "E" },
                { BizOperationUserType.ConfirmUser, "C" },
                { BizOperationUserType.ApprovedUser, "A" },
                { BizOperationUserType.User, "U" },
                { BizOperationUserType.PM, "P" },
                { BizOperationUserType.RecvUserSysNo, "R" }
            });

            EnumCodeMapper.AddMap<BizOperationUserStatus>(new Dictionary<BizOperationUserStatus, int>{
                { BizOperationUserStatus.Active, 0 },
                { BizOperationUserStatus.InActive, -1 }
            });

            EnumCodeMapper.AddMap<HYNStatus>(new Dictionary<HYNStatus, string>{
                { HYNStatus.Hide, "Hide" },
                { HYNStatus.No,"No" },
                { HYNStatus.Yes, "Yes" }
            });

            EnumCodeMapper.AddMap<SYNStatus>(new Dictionary<SYNStatus, string>{
                { SYNStatus.No,"No" },
                { SYNStatus.Yes, "Yes" }
            });
            EnumCodeMapper.AddMap<IsSpecial>(new Dictionary<IsSpecial, string>{
                { IsSpecial.No,"N" },
                { IsSpecial.Yes, "Y" }
            });
            EnumCodeMapper.AddMap<DeliveryStatusFor24H>(new Dictionary<DeliveryStatusFor24H, string>{
                { DeliveryStatusFor24H.No,"0" },
                { DeliveryStatusFor24H.Yes, "24H" }
            });
            EnumCodeMapper.AddMap<AreaStatus>(new Dictionary<AreaStatus, int>{
                { AreaStatus.Active,0 },
                { AreaStatus.Deactive, -1 }
            });
            EnumCodeMapper.AddMap<ShipTypeProductType>(new Dictionary<ShipTypeProductType, string>{
                { ShipTypeProductType.Required,"D" },
                { ShipTypeProductType.Embargo, "E" }
            });
            EnumCodeMapper.AddMap<ProductRange>(new Dictionary<ProductRange, string>{
                { ProductRange.Goods,"P" },
                { ProductRange.GoodsType, "C" }
            });
            EnumCodeMapper.AddMap<CompanyCustomer>(new Dictionary<CompanyCustomer, int>{
                { CompanyCustomer.Default,0 },
                { CompanyCustomer.AstraZeneca,1 }
            });

            EnumCodeMapper.AddMap<LogSOStatus>(new Dictionary<LogSOStatus, int>{
             { LogSOStatus.Origin,0 },
            { LogSOStatus.WaitingOutStock,1 },
            { LogSOStatus.WaitingPay,2 },
            { LogSOStatus.WaitingManagerAudit,3 },
            { LogSOStatus.OutStock,4 },
            { LogSOStatus.SystemCancel,-4 },
            { LogSOStatus.ManagerCancel,-3 },
            { LogSOStatus.CustomerCancel,-2 },
            { LogSOStatus.EmployeeCancel,-1 }
            });

            EnumCodeMapper.AddMap<c.BizLogType>(new Dictionary<c.BizLogType, int>{
               { c.BizLogType.St_Transfer_Item_Delete,50143 },
                { c.BizLogType.RMA_Refund_CancelAudit,70505 },
                { c.BizLogType.Sys_User_Add,101010 },
                { c.BizLogType.Sys_User_Update,101011 },
                { c.BizLogType.Sys_User_Login,101012 },
                { c.BizLogType.Sys_Role_Add,101110 },
                { c.BizLogType.Sys_Role_Update,101111 },
                { c.BizLogType.Sys_UserRole_Add,101210 },
                { c.BizLogType.Sys_UserRole_Delete,101212 },
                { c.BizLogType.Sys_RolePrivilege_Add,101310 },
                { c.BizLogType.Sys_RolePrivilege_Delete,101312 },
                { c.BizLogType.Basic_Category1_Add,111310 },
                { c.BizLogType.Basic_Category1_Update,111311 },
                { c.BizLogType.Basic_Category1_CancelAudit,111313 },
                { c.BizLogType.Basic_Category1_Approved,111314 },
                { c.BizLogType.Basic_Category1_Declined,111315 },
                { c.BizLogType.Basic_Category2_Add,111410 },
                { c.BizLogType.Basic_Category2_Update,111411 },
                { c.BizLogType.Basic_Category2_CancelAudit,111413 },
                { c.BizLogType.Basic_Category2_Approved,111414 },
                { c.BizLogType.Basic_Category2_Declined,111415 },                
                { c.BizLogType.Basic_Category3_Add,111510 },
                { c.BizLogType.Basic_Category3_Update,111511 },
                { c.BizLogType.Basic_Category3_CancelAudit,111513 },
                { c.BizLogType.Basic_Category3_Approved,111514 },
                { c.BizLogType.Basic_Category3_Declined,111515 },                
                { c.BizLogType.Basic_CategoryAttribute_Init,111610 },
                { c.BizLogType.Basic_CategoryAttribute_Update,111611 },
                { c.BizLogType.Basic_CategoryAttribute_Top,111612 },
                { c.BizLogType.Basic_CategoryAttribute_Up,111613 },
                { c.BizLogType.Basic_CategoryAttribute_Down,111614 },
                { c.BizLogType.Basic_CategoryAttribute_Bottom,111615 },
                { c.BizLogType.Basic_Manufacturer_Add,111710 },
                { c.BizLogType.Basic_Manufacturer_Update,111711 },
                { c.BizLogType.Basic_Vendor_Add,111810 },
                { c.BizLogType.Basic_Vendor_Update,111811 },
                { c.BizLogType.Basic_Vendor_Hold,111812 },
                { c.BizLogType.Basic_Vendor_UnHold,111813 },
                { c.BizLogType.Basic_Stock_Add,111910 },
                { c.BizLogType.Basic_Stock_Update,111911 },
                { c.BizLogType.Basic_Currency_Add,112010 },
                { c.BizLogType.Basic_Currency_Update,112011 },
                { c.BizLogType.Basic_Customer_Add,113001 },           
                { c.BizLogType.Basic_Product_Basic_Update,113002 },
                { c.BizLogType.Basic_Product_Price_Update,113003 },
                { c.BizLogType.Basic_Product_PM_Update,113004 },
                { c.BizLogType.Basic_Product_Attribute_Update,113005 },
                { c.BizLogType.Basic_Product_Weight_Update,113006 },
                { c.BizLogType.Basic_Product_Pic_Update,113007 },
                { c.BizLogType.Basic_Product_NotPermitRefund,113008 },
                { c.BizLogType.Basic_Product_PermitRefund,113009 },
                { c.BizLogType.Basic_Product_JDItem_Update,113010 },
                { c.BizLogType.Ex_Product_TakePictures_Update,113011 },              
                { c.BizLogType.Basic_Customer_Invalid,113012 },
                { c.BizLogType.Basic_Customer_ManualSetVIPRank,113013 },
                { c.BizLogType.Basic_Product_Clone,113014 },
                { c.BizLogType.Basic_Product_Copy,113015 },
                { c.BizLogType.Basic_Product_Note_Update,113017 },
                { c.BizLogType.Basic_Product_Hold_Update,113018 },
                { c.BizLogType.Inventory_PurchaseQtyAdjust,113019 },
                { c.BizLogType.Basic_Product_Price_Update_Verify,113020 },
                { c.BizLogType.Basic_Product_Price_Update_CancelVerify,113021 },
                { c.BizLogType.Basic_Product_Price_Update_VerifyOK,113022 },
                { c.BizLogType.Basic_Product_Price_Update_VerifyCancel,113023 },
                { c.BizLogType.Basic_Product_Info_PublishOK,113024 },
                { c.BizLogType.Basic_Product_UnitCost_Update_Instalment,113025 },
                { c.BizLogType.Basic_Product_Price_Update_Instalment,113026 },
                { c.BizLogType.Basic_Product_Price_PMRequestMemo,113030 },
                { c.BizLogType.Basic_Product_Price_TLRequestMemo,113031 },
                { c.BizLogType.Basic_Product_TopCancelWithGoDown,113041 },
                { c.BizLogType.Basic_Product_TopSave,113042 },
                { c.BizLogType.Basic_Product_TopCancel,113043 },
                { c.BizLogType.Vendor_Update_Verify,114020 },
                { c.BizLogType.Vendor_Update_Cancel_Verify,114021 },
                { c.BizLogType.Vendor_Update_VerifyOK,114022 },
                { c.BizLogType.Vendor_Update__VerifyCancel,114023 },
                { c.BizLogType.Basic_Area_Add,116010 },
                { c.BizLogType.Basic_Area_Update,116011 },
                { c.BizLogType.Basic_PayType_Add,116012 },
                { c.BizLogType.Basic_PayType_Update,116013 },
                { c.BizLogType.Basic_ShipType_Add,116014 },
                { c.BizLogType.Basic_ShipType_Update,116015 },
                { c.BizLogType.Basic_ShipAreaUn_Add,116016 },
                { c.BizLogType.Basic_ShipAreaUn_Delete,116017 },
                { c.BizLogType.Basic_ShipPayUn_Add,116018 },
                { c.BizLogType.Basic_ShipPayUn_Delete,116019 },
                { c.BizLogType.Basic_ShipAreaPrice_Add,116020 },
                { c.BizLogType.Basic_ShipAreaPrice_Delete,116021 },
                { c.BizLogType.Purchase_Basket_Insert,201010 },
                { c.BizLogType.Purchase_Basket_Update,201011 },
                { c.BizLogType.Purchase_Basket_Delete,201012 },
                { c.BizLogType.Purchase_Create,201110 },
                { c.BizLogType.Purchase_Master_Update,201111 },
                { c.BizLogType.Purchase_Item_Insert,201112 },
                { c.BizLogType.Purchase_Item_Update,201113 },
                { c.BizLogType.Purchase_Item_Delete,201114 },            
                { c.BizLogType.Purchase_Verify_InStock,201116 },
                { c.BizLogType.Purchase_CancelVerify,201117 },
                { c.BizLogType.Purchase_InStock,201118 },
                { c.BizLogType.Purchase_CancelInStock,201119 },
                { c.BizLogType.Purchase_Abandon,201120 },
                { c.BizLogType.Purchase_CancelAbandon,201121 },
                { c.BizLogType.Purchase_ApportionMaster_Add,201122 },
                { c.BizLogType.Purchase_ApportionMaster_Delete,201123 },
                { c.BizLogType.Purchase_ApportionItem_Add,201124 },
                { c.BizLogType.Purchase_ApportionItem_Delete,201125 },
                { c.BizLogType.Purchase_Apportion_Export,201126 },
                { c.BizLogType.Purchase_InStockMemo,201127 },
                { c.BizLogType.Purchase_Item_Check,201128 },
                { c.BizLogType.Purchase_AutoAbandon,201129 },
                { c.BizLogType.POCToAcc_Add,201130 },
                { c.BizLogType.POC_VendorSettle_Create,201131 },
                { c.BizLogType.POC_VendorSettle_Master_Update,201132 },
                { c.BizLogType.POC_VendorSettle_Item_Add,201133 },
                { c.BizLogType.POC_VendorSettle_Item_Delete,201134 },
                { c.BizLogType.POC_VendorSettle_Item_Update,201135 },
                { c.BizLogType.POC_VendorSettle_Audit,201136 },
                { c.BizLogType.POC_VendorSettle_CancelAudit,201137 },
                { c.BizLogType.POC_VendorSettle_Settle,201138 },
                { c.BizLogType.POC_VendorSettle_CancelSettle,201139 },
                { c.BizLogType.POC_VendorSettle_Abandon,201140 },
                { c.BizLogType.POC_VendorSettle_CancelAbandon,201141 },
                { c.BizLogType.POC_FinanceSettle_Create,201142 },
                { c.BizLogType.POC_FinanceSettle_Abandon,201143 },
                { c.BizLogType.POC_FinanceSettle_CancelAbandon,201144 },
                { c.BizLogType.Purchase_PMRequestMemo,201145 },
                { c.BizLogType.Purchase_TLRequestMemo,201146 },
                { c.BizLogType.Finance_Pay_Item_Add,301110 },
                { c.BizLogType.Finance_Pay_Item_Update,301111 },
                { c.BizLogType.Finance_Pay_Item_Abandon,301112 },
                { c.BizLogType.Finance_Pay_Item_CancelAbandon,301113 },
                { c.BizLogType.Finance_Pay_Item_Pay,301114 },
                { c.BizLogType.Finance_Pay_Item_CancelPay,301115 },
                { c.BizLogType.Finance_Pay_Update,301116 },
                { c.BizLogType.Finance_SOIncome_Add,301201 },
                { c.BizLogType.Finance_SOIncome_Abandon,301202 },
                { c.BizLogType.Finance_SOIncome_Confirm,301203 },
                { c.BizLogType.Finance_SOIncome_UnConfirm,301204 },
                { c.BizLogType.Finance_SOIncome_UpdateIncomeAmt,301205 },
                { c.BizLogType.Finance_SOIncome_UpdateInvoiceNo,301206 },
                { c.BizLogType.Finance_NetPay_AddVerified,301310 },
                { c.BizLogType.Finance_NetPay_Verify,301311 },
                { c.BizLogType.Finance_NetPay_Abandon,301312 },
                { c.BizLogType.Finance_AdvancePay_Check,301313 },
                { c.BizLogType.FinanceRemitNoOwnerEdit,301314 },
                { c.BizLogType.FinanceRemitNoOwnerClaimAudit,301315 },
                { c.BizLogType.FinanceRemitNoOwnerDelete,301316 },
                { c.BizLogType.Add_NewEggAccounts_Point,301401 },
                { c.BizLogType.Online_Bulletin_Update,401001 },
                { c.BizLogType.Online_List_Insert,401002 },
                { c.BizLogType.Online_List_Delete,401003 },
                { c.BizLogType.Online_Poll_Insert,401004 },
                { c.BizLogType.Online_Poll_Update,401005 },
                { c.BizLogType.Online_Poll_InsertItem,401006 },
                { c.BizLogType.Online_Poll_UpdateItem,401007 },
                { c.BizLogType.Online_Poll_DeleteItem,401008 },
                { c.BizLogType.Online_Poll_Show,401009 },
                { c.BizLogType.Online_Poll_NotShow,401010 },
                { c.BizLogType.Online_FeedBack_Update,401011 },
                { c.BizLogType.Online_ProductQuestion_Reply,401012 },
                { c.BizLogType.PromotionAdd,402001 },
                { c.BizLogType.PromotionInvalid,402002 },
                { c.BizLogType.PromotionValid,402003 },
                { c.BizLogType.PromotionCodeAdd,402004 },
                { c.BizLogType.PromotionCodeInvalid,402005 },
                { c.BizLogType.PromotionCodeValid,402006 },
                { c.BizLogType.PromotionCodeDistribute,402007 },
                { c.BizLogType.PromotionCustomerDelete,402008 },
                { c.BizLogType.PromotionProductAdd,402009 },
                { c.BizLogType.PromotionProductDelete,402010 },
                { c.BizLogType.BetAdd,402011 },
                { c.BizLogType.BetUpdate,402012 },
                { c.BizLogType.BetOptionAdd,402013 },
                { c.BizLogType.BetOptionDelete,402014 },
                { c.BizLogType.BetAnswerSet,402015 },
                { c.BizLogType.BetOpen,402016 },
                { c.BizLogType.PromotionEdit,402017 },
                { c.BizLogType.PromotionLimitAdd,402018 },
                { c.BizLogType.PromotionLimitEdit,402019 },
                { c.BizLogType.PromotionLimitDelete,402020 },
                { c.BizLogType.PromotionCodeDelete,402021 },
                { c.BizLogType.PromotionCodeEdit,402022 },
                { c.BizLogType.Auction_Status_Update,405001 },
                { c.BizLogType.Auction_Detail_Update,405002 },
                { c.BizLogType.Auction_Detail_Insert,405003 },
                { c.BizLogType.AuctionComment_Status_Update,405004 },
                { c.BizLogType.Auction_Trubermaker_Insert,405005 },
                { c.BizLogType.Auction_Status_Confirm,405006 },
                { c.BizLogType.Auction_Status_Delete,405007 },
                { c.BizLogType.Auction_Reset_Status_Update,405008 },
                { c.BizLogType.Countdown_Insert,408001 },
                { c.BizLogType.Countdown_Update,408002 },
                { c.BizLogType.Countdown_Abandon,408003 },
                { c.BizLogType.Countdown_Interupt,408004 },
                { c.BizLogType.Countdown_Verify,408005 },
                { c.BizLogType.Countdown_VerifyPass,408006 },
                { c.BizLogType.Countdown_VerifyFaild,408007 },
                { c.BizLogType.Delivery_OK,409001 },
                { c.BizLogType.Delivery_Abandon,409002 },
                { c.BizLogType.Delivery_Failure,409003 },
                { c.BizLogType.Delivery_NoAction,409004 },
                { c.BizLogType.Delivery_ReAssign,409005 },
                { c.BizLogType.PO_Vendor_Invoice_Add,409006 },
                { c.BizLogType.PO_Vendor_Invoice_Update,409007 },
                { c.BizLogType.PO_Vendor_Invoice_Verify,409008 },
                { c.BizLogType.PO_Vendor_Invoice_CancelVerify,409009 },
                { c.BizLogType.PO_Vendor_Invoice_Abandon,409010 },
                { c.BizLogType.PO_Vendor_Invoice_CancelAbandon,409011 },
                { c.BizLogType.InvoiceInput_Add,500000 },
                { c.BizLogType.InvoiceInput_SubmitAudit,500001 },
                { c.BizLogType.InvoiceInput_CancelAudit,500002 },
                { c.BizLogType.InvoiceInput_PassAudit,500003 },
                { c.BizLogType.InvoiceInput_RefuseAudit,500004 },
                { c.BizLogType.St_Lend_Master_Insert,501110 },
                { c.BizLogType.St_Lend_Master_Update,501111 },
                { c.BizLogType.St_Lend_Item_Insert,501112 },
                { c.BizLogType.St_Lend_Item_Delete,501113 },
                { c.BizLogType.St_Lend_Item_Update,501114 },
                { c.BizLogType.St_Lend_Abandon,501115 },
                { c.BizLogType.St_Lend_CancelAbandon,501116 },
                { c.BizLogType.St_Lend_Verify,501117 },
                { c.BizLogType.St_Lend_CancelVerify,501118 },
                { c.BizLogType.St_Lend_OutStock,501119 },
                { c.BizLogType.St_Lend_CancelOutStock,501120 },
                { c.BizLogType.St_Lend_Return_Insert,501121 },
                { c.BizLogType.St_Lend_Return_Delete,501122 },
                { c.BizLogType.St_Adjust_Master_Insert,501210 },
                { c.BizLogType.St_Adjust_Master_Update,501211 },
                { c.BizLogType.St_Adjust_Item_Insert,501212 },
                { c.BizLogType.St_Adjust_Item_Delete,501213 },
                { c.BizLogType.St_Adjust_Item_Update,501214 },
                { c.BizLogType.St_Adjust_Abandon,501215 },
                { c.BizLogType.St_Adjust_CancelAbandon,501216 },
                { c.BizLogType.St_Adjust_Verify,501217 },
                { c.BizLogType.St_Adjust_CancelVerify,501218 },
                { c.BizLogType.St_Adjust_OutStock,501219 },
                { c.BizLogType.St_Adjust_CancelOutStock,501220 },
                { c.BizLogType.St_Shift_Master_Insert,501310 },
                { c.BizLogType.St_Shift_Master_Update,501311 },
                { c.BizLogType.St_Shift_Item_Insert,501312 },
                { c.BizLogType.St_Shift_Item_Delete,501313 },
                { c.BizLogType.St_Shift_Item_Update,501314 },
                { c.BizLogType.St_Shift_Abandon,501315 },
                { c.BizLogType.St_Shift_CancelAbandon,501316 },
                { c.BizLogType.St_Shift_Verify,501317 },
                { c.BizLogType.St_Shift_CancelVerify,501318 },
                { c.BizLogType.St_Shift_OutStock,501319 },
                { c.BizLogType.St_Shift_CancelOutStock,501320 },
                { c.BizLogType.St_Shift_InStock,501321 },
                { c.BizLogType.St_Shift_CancelInStock,501322 },
                { c.BizLogType.St_Shift_BatchInsert,501323 },
                { c.BizLogType.St_Transfer_Master_Insert,501410 },
                { c.BizLogType.St_Transfer_Master_Update,501411 },
                { c.BizLogType.St_Transfer_Item_Insert,501412 },
                { c.BizLogType.St_Transfer_Item_Update,501414 },
                { c.BizLogType.St_Transfer_Abandon,501415 },
                { c.BizLogType.St_Transfer_CancelAbandon,501416 },
                { c.BizLogType.St_Transfer_Verify,501417 },
                { c.BizLogType.St_Transfer_CancelVerify,501418 },
                { c.BizLogType.St_Transfer_OutStock,501419 },
                { c.BizLogType.St_Transfer_CancelOutStock,501420 },
                { c.BizLogType.St_Virtual_Insert,501510 },
                { c.BizLogType.St_SOVirtualItemRequest_Add,501511 },
                { c.BizLogType.St_SOVirtualItemRequest_Save,501512 },
                { c.BizLogType.St_SOVirtualItemRequest_Abandon,501513 },
                { c.BizLogType.St_SOVirtualItemRequest_UpdateCSMemo,501514 },
                { c.BizLogType.St_Category3SetRMAInfo_Update,501515 },
                { c.BizLogType.St_Inventory_SetPos,501610 },
                { c.BizLogType.AuditRefund_Update,600000 },
                { c.BizLogType.Sale_SO_WebSite_Create,0 },
                { c.BizLogType.Sale_SO_WebSite_Submit,200 },
                { c.BizLogType.Sale_SO_Create,600601 },
                { c.BizLogType.Sale_SO_Audit,600602 },
                { c.BizLogType.Sale_SO_CancelAudit,600603 },
                { c.BizLogType.Sale_SO_ManagerAudit,600604 },
                { c.BizLogType.Sale_SO_CustomerAbandon,600605 },
                { c.BizLogType.Sale_SO_EmployeeAbandon,600606 },
                { c.BizLogType.Sale_SO_ManagerAbandon,600607 },
                { c.BizLogType.Sale_SO_CancelAbandon,600608 },
                { c.BizLogType.Sale_SO_OutStock,600609 },
                { c.BizLogType.Sale_SO_CancelOutStock,600610 },
                { c.BizLogType.Sale_SO_PrintInvoice,600611 },
                { c.BizLogType.Sale_SO_Update,600612 },
                { c.BizLogType.Sale_SO_FastCashRebate,600613 },
                { c.BizLogType.Sale_SO_HoldSO,600614 },
                { c.BizLogType.Sale_SO_UnHoldSO,600615 },
                { c.BizLogType.Sale_SO_VoideSO,600616 },
                { c.BizLogType.Sale_SO_UpdateInvoiceNo,600617 },
                { c.BizLogType.Sale_SO_SplitInvoice,600618 },
                { c.BizLogType.Sale_SO_CancelSplitInvoice,600619 },
                { c.BizLogType.Sale_RMA_Create,600801 },
                { c.BizLogType.Sale_RMA_Abandon,600802 },
                { c.BizLogType.Sale_RMA_Audit,600803 },
                { c.BizLogType.Sale_RMA_CancelAudit,600804 },
                { c.BizLogType.Sale_RMA_Receive,600805 },
                { c.BizLogType.Sale_RMA_CancelReceive,600806 },
                { c.BizLogType.Sale_RMA_Handle,600807 },
                { c.BizLogType.Sale_RMA_CancelHandle,600808 },
                { c.BizLogType.Sale_RMA_Close,600809 },
                { c.BizLogType.Sale_RMA_Reopen,600810 },
                { c.BizLogType.Sale_RO_Create,600901 },
                { c.BizLogType.Sale_RO_Abandon,600902 },
                { c.BizLogType.Sale_RO_Audit,600903 },
                { c.BizLogType.Sale_RO_CancelAudit,600904 },
                { c.BizLogType.Sale_RO_Return,600905 },
                { c.BizLogType.Sale_RO_CancelReturn,600906 },
                { c.BizLogType.Sale_RO_PrintInvoice,600907 },
                { c.BizLogType.Sale_RMA_Create2,700801 },
                { c.BizLogType.Sale_RMA_Abandon2,700802 },
                { c.BizLogType.Sale_RMA_Audit2,700803 },
                { c.BizLogType.RMA_OutBound_Create,702001 },
                { c.BizLogType.RMA_OutBound_Update,702002 },
                { c.BizLogType.RMA_OutBound_OutStock,702003 },
                { c.BizLogType.RMA_OutBound_CancelOutStock,702004 },
                { c.BizLogType.RMA_OutBound_DeleteItem,702005 },
                { c.BizLogType.RMA_OutBound_InsertItem,702006 },
                { c.BizLogType.RMA_OutBound_Abandon,702007 },
                { c.BizLogType.RMA_Register_Check,703001 },
                { c.BizLogType.RMA_Register_Memo,703002 },
                { c.BizLogType.RMA_Register_Outbound,703003 },
                { c.BizLogType.RMA_Register_Revert,703004 },
                { c.BizLogType.RMA_Register_Refund,703005 },
                { c.BizLogType.RMA_Register_Return,703006 },
                { c.BizLogType.RMA_Register_Close,703007 },
                { c.BizLogType.RMA_Register_ToCC,703008 },
                { c.BizLogType.RMA_Register_ToRMA,703009 },
                { c.BizLogType.RMA_Register_RevertAudit,703010 },
                { c.BizLogType.RMA_Register_ResponseInfo,703011 },
                { c.BizLogType.RMA_Register_ToRegister,703012 },
                { c.BizLogType.RMA_Register_ToCheck,703013 },
                { c.BizLogType.RMA_Register_ToASK,703014 },
                { c.BizLogType.RMA_Register_ToRevert,703015 },
                { c.BizLogType.RMA_Register_ToReturn,703016 },
                { c.BizLogType.RMA_Register_ToECC,703017 },
                { c.BizLogType.RMA_Revert_Create,704001 },
                { c.BizLogType.RMA_Revert_Update,704002 },
                { c.BizLogType.RMA_Revert_Abandon,704003 },
                { c.BizLogType.RMA_Revert_Out,704004 },
                { c.BizLogType.RMA_Revert_CancelOut,704005 },
                { c.BizLogType.RMA_Refund_Create,705001 },
                { c.BizLogType.RMA_Refund_Upate,705002 },
                { c.BizLogType.RMA_Refund_Abandon,705003 },
                { c.BizLogType.RMA_Refund_Audit,705004 },
                { c.BizLogType.RMA_Refund_Refund,705006 },
                { c.BizLogType.AO_Refund_Refund,705008 },
                { c.BizLogType.RMA_Refund_CancelRefund,705007 },
                { c.BizLogType.RMA_Return_Create,706001 },
                { c.BizLogType.RMA_Return_Update,706002 },
                { c.BizLogType.RMA_Return_Abandon,706003 },
                { c.BizLogType.RMA_Return_Return,706004 },
                { c.BizLogType.RMA_Return_CancelReturn,706005 },
                { c.BizLogType.RMA_Return_Audit,706006 },
                { c.BizLogType.RMA_Request_Create,707001 },
                { c.BizLogType.RMA_Request_Update,707002 },
                { c.BizLogType.RMA_Request_Receive,707003 },
                { c.BizLogType.RMA_Request_CancelReceive,707004 },
                { c.BizLogType.RMA_Request_Abandon,707005 },
                { c.BizLogType.RMA_Request_Close,707006 },
                { c.BizLogType.RMA_Request_ReCreate,707007 },
                { c.BizLogType.RMA_Auto_Request,707008 },
                { c.BizLogType.RMA_Auto_Refund,707009 },
                { c.BizLogType.RMA_Auto_Return,707010 },
                { c.BizLogType.PO_SendMail,808001 },
                { c.BizLogType.InventoryBackUp,999998 },
                { c.BizLogType.ZZZZZ,999999 }
            });

            EnumCodeMapper.AddMap<FreeShippingAmountSettingStatus>(new Dictionary<FreeShippingAmountSettingStatus, string>{
                { FreeShippingAmountSettingStatus.Active, "A" },
                { FreeShippingAmountSettingStatus.DeActive, "D" }
            });
        }
    }
}